export const ONBOARDING_CHECKLIST_STEP_LABELS: Record<string, string> = {
  intake_questionnaire_completed: "Intake questionnaire completed and saved",
  org_config_confirmed: "Org config row confirmed in DynamoDB",
  agency_admin_created: "Agency admin account created",
  staff_users_invited: "Staff users invited with correct roles",
  mfa_enabled: "MFA enabled for all users",
  sms_number_registered: "SMS number registered and keyword confirmed",
  test_sms_sent: "Test SMS sent and incident created successfully",
  tenant_isolation_verified: "Tenant isolation verified (no cross-agency data visible)",
  audit_log_confirmed: "Audit log confirmed for test incident",
  staff_dashboard_walkthrough: "Staff dashboard walkthrough completed",
  campus_map_uploaded: "Campus map uploaded or zones entered in admin",
  rcli_locations_created: "RCLI locations created for all buildings in scope",
  qr_codes_downloaded: "QR codes downloaded for each location",
  signs_printed: "Signs printed and installation plan confirmed",
  nfc_tags_programmed: "NFC tags programmed with matching URLs (if applicable)",
  anonymous_reporting_confirmed: "Anonymous reporting setting confirmed",
  clery_contact_notified: "Clery compliance contact notified",
  tabletop_scenario_completed: "Tabletop scenario completed with security team",
  section_map_uploaded: "Section / gate map uploaded or zones entered in admin",
  event_calendar_entered: "Event calendar entered or expiry dates set on event codes",
  guest_services_routing_confirmed: "Guest services routing confirmed",
  ada_coordinator_notified: "ADA coordinator notified",
};
