/**
 * Response Continuity System (RCS) — life-safety call persistence types.
 * Silent monitor queue → unit geofence arrival confirmation → audio sentinel →
 * escalation engine → closure gate with supervisor override audit.
 * Addon: `rcs.module` ($3500/mo, `packages/shared/src/billing/addon-catalog.ts`).
 */

export const RCS_CALL_STATES = [
  "MONITORING",
  "UNIT_DISPATCHED",
  "UNIT_EN_ROUTE",
  "UNIT_ARRIVED",
  "AUDIO_ALERT",
  "ESCALATED",
  "SUPERVISOR_ACKNOWLEDGED",
  "CLOSED",
  "OVERRIDE_CLOSED",
] as const;
export type RcsCallState = (typeof RCS_CALL_STATES)[number];

/** Terminal states — no further mutation once reached. */
export const RCS_CLOSED_STATES: readonly RcsCallState[] = ["CLOSED", "OVERRIDE_CLOSED"];

export const RCS_ESCALATION_LEVELS = ["NONE", "LEVEL_1", "LEVEL_2", "LEVEL_3", "CRITICAL"] as const;
export type RcsEscalationLevel = (typeof RCS_ESCALATION_LEVELS)[number];

export const RCS_AUDIO_STATUSES = [
  "SILENT",
  "LISTENING",
  "ALERT",
  "CONFIRMED_SAFE",
  "CONFIRMED_DANGER",
] as const;
export type RcsAudioStatus = (typeof RCS_AUDIO_STATUSES)[number];

export interface RcsGeoPoint {
  latitude: number;
  longitude: number;
}

export interface RcsUnit {
  unitId: string;
  callSign?: string;
  latitude: number;
  longitude: number;
  updatedAt: string;
  /** True once the unit has been confirmed within the call's arrival geofence. */
  onScene: boolean;
  distanceMeters?: number;
}

export interface RcsClosureOverride {
  byUserId: string;
  byBadge: string;
  reason: string;
  at: string;
}

export interface RcsCall {
  callId: string;
  agencyId: string;
  incidentId?: string;
  callerPhone?: string;
  state: RcsCallState;
  escalationLevel: RcsEscalationLevel;
  audioStatus: RcsAudioStatus;
  location?: RcsGeoPoint;
  /** Meters from `location` a unit must be within to be considered on-scene. */
  arrivalRadiusMeters: number;
  units: RcsUnit[];
  createdAt: string;
  updatedAt: string;
  createdByUserId: string;
  assignedDispatcherId?: string;
  closedAt?: string;
  closedByUserId?: string;
  /** Present only when closed via supervisor override (state = OVERRIDE_CLOSED). */
  closureOverride?: RcsClosureOverride;
  supervisorAckByUserId?: string;
  supervisorAckAt?: string;
  notes?: string;
}

export interface RcsCallStartRequest {
  incidentId?: string;
  callerPhone?: string;
  location?: RcsGeoPoint;
  arrivalRadiusMeters?: number;
  notes?: string;
}

export interface RcsCallStateUpdateRequest {
  state: RcsCallState;
  notes?: string;
}

export interface RcsCallCloseRequest {
  /** Required to close a call that has not reached UNIT_ARRIVED. Dispatchers may not override. */
  supervisorOverride?: {
    badge: string;
    reason: string;
  };
}

export interface RcsAudioAlertRequest {
  audioStatus: RcsAudioStatus;
  detail?: string;
}

export interface RcsUnitPositionRequest {
  unitId: string;
  callSign?: string;
  latitude: number;
  longitude: number;
  /** When provided, the position is evaluated against this call's geofence. */
  callId?: string;
}

export interface RcsSupervisorAckRequest {
  note?: string;
}

/** EventBridge Scheduler payload delivered to the escalation trigger Lambda (no HTTP route). */
export interface RcsEscalationTriggerEvent {
  callId: string;
  agencyId: string;
  level: RcsEscalationLevel;
}

// ─── AI Summary (Intelligence Layer) ──────────────────────────────────────────

/**
 * AI-generated situational summary for an active RCS call.
 * Generated by the rcs-ai-summarizer Lambda and stored on the call record.
 * Refreshed every 60 seconds while the call is in a non-terminal state.
 */
export interface RcsAiSummary {
  /** Compact 1–2 sentence situational summary safe to display to any authorized user. */
  text: string;
  /** ISO timestamp when this summary was generated. */
  generatedAt: string;
  /**
   * Keywords of concern detected during summarization.
   * Examples: "weapon", "unconscious", "no_response", "fire", "children".
   */
  concernKeywords: string[];
  /** Confidence score 0–1. Below 0.6 show a caution indicator. */
  confidence: number;
}

// ─── Soft Handoff ─────────────────────────────────────────────────────────────

export const RCS_HANDOFF_STATES = ["REQUESTED", "ACTIVE", "CLEARED"] as const;
export type RcsHandoffState = (typeof RCS_HANDOFF_STATES)[number];

/**
 * Soft handoff record attached to an RcsCall when a dispatcher needs
 * secondary monitoring coverage for an open call.
 */
export interface RcsSoftHandoff {
  state: RcsHandoffState;
  requestedByUserId: string;
  requestedByDisplayName: string;
  requestedAt: string;
  acceptedByUserId?: string;
  acceptedByDisplayName?: string;
  acceptedAt?: string;
  note?: string;
}

export interface RcsSoftHandoffRequest {
  note?: string;
}

export interface RcsSoftHandoffAcceptRequest {
  /** Accepting user's display name for immediate UI rendering without a profile lookup. */
  acceptorDisplayName: string;
}

// ─── Escalation Rules ─────────────────────────────────────────────────────────

/**
 * Agency-configured thresholds that drive the escalation watchdog Lambda.
 * Stored as Dynamo item SK = RCS_ESCALATION_RULES under the RCS escalation table
 * (or dedicated rules table when provisioned).
 */
export interface RcsEscalationRules {
  agencyId: string;
  /** Seconds after UNIT_DISPATCHED / UNIT_EN_ROUTE without on-scene before LEVEL_1. Default 480. */
  dispatchedWithoutArrivalSeconds: number;
  /** Seconds at LEVEL_1 without supervisor ack before LEVEL_2. Default 300. */
  level1UnackedSeconds: number;
  /** Seconds at LEVEL_2 without supervisor ack before LEVEL_3. Default 300. */
  level2UnackedSeconds: number;
  /** Seconds of SILENT audio with no unit on scene before AUDIO_ALERT. Default 45. */
  audioSilenceAlertSeconds: number;
  /** When true, publish WebSocket push to agency on escalation. Default true. */
  supervisorPushOnEscalation: boolean;
  updatedAt: string;
  updatedByUserId: string;
}

export const RCS_ESCALATION_RULES_DEFAULTS: Omit<
  RcsEscalationRules,
  "agencyId" | "updatedAt" | "updatedByUserId"
> = {
  dispatchedWithoutArrivalSeconds: 480,
  level1UnackedSeconds: 300,
  level2UnackedSeconds: 300,
  audioSilenceAlertSeconds: 45,
  supervisorPushOnEscalation: true,
};

// ─── Floor Health ─────────────────────────────────────────────────────────────

export interface RcsFloorHealthCallEntry {
  callId: string;
  incidentId?: string;
  state: RcsCallState;
  escalationLevel: RcsEscalationLevel;
  audioStatus: RcsAudioStatus;
  assignedDispatcherDisplayName?: string;
  timeInStateSeconds: number;
  totalElapsedSeconds: number;
  aiSummaryText?: string;
  aiSummaryKeywords?: string[];
  softHandoffState?: RcsHandoffState;
  hasUnitOnScene: boolean;
  units: Pick<RcsUnit, "unitId" | "callSign" | "onScene" | "distanceMeters">[];
}

export interface RcsFloorHealthSnapshot {
  agencyId: string;
  generatedAt: string;
  activeCalls: RcsFloorHealthCallEntry[];
  totalOpenCalls: number;
  criticalCallCount: number;
  pendingHandoffCount: number;
  overdueArrivalCount: number;
}

// ─── Extended RcsCall fields (optional — base RcsCall unchanged) ───────────────

export interface RcsCallIntelligence {
  aiSummary?: RcsAiSummary;
  softHandoff?: RcsSoftHandoff;
  /** ISO timestamp when the current state was entered. */
  stateEnteredAt?: string;
  /** ISO timestamp when audio went SILENT. Cleared when status changes. */
  audioSilentSince?: string;
  /** Optional display name for floor health (denormalized). */
  assignedDispatcherDisplayName?: string;
}

/** Full enriched RCS call — base fields plus intelligence layer. */
export type RcsCallEnriched = RcsCall & RcsCallIntelligence;

// ─── WebSocket event payloads ─────────────────────────────────────────────────

export interface RcsWsSummaryUpdated {
  type: "rcs:summary:updated";
  callId: string;
  agencyId: string;
  summary: RcsAiSummary;
}

export interface RcsWsHandoffRequested {
  type: "rcs:handoff:requested";
  callId: string;
  agencyId: string;
  handoff: RcsSoftHandoff;
  incidentId?: string;
}

export interface RcsWsHandoffAccepted {
  type: "rcs:handoff:accepted";
  callId: string;
  agencyId: string;
  handoff: RcsSoftHandoff;
}

export interface RcsWsHandoffCleared {
  type: "rcs:handoff:cleared";
  callId: string;
  agencyId: string;
}

export interface RcsWsEscalationTriggered {
  type: "rcs:escalation:triggered";
  callId: string;
  agencyId: string;
  previousLevel: RcsEscalationLevel;
  newLevel: RcsEscalationLevel;
  reason: "dispatched_timeout" | "level1_unacked" | "level2_unacked" | "audio_silence";
}

export interface RcsWsArrivalConfirmed {
  type: "rcs:arrival:confirmed";
  callId: string;
  agencyId: string;
  unitId: string;
  callSign?: string;
  confirmedAt: string;
}

export interface RcsWsFloorHealthUpdated {
  type: "rcs:floor:health";
  snapshot: RcsFloorHealthSnapshot;
}

export type RcsWebSocketEvent =
  | RcsWsSummaryUpdated
  | RcsWsHandoffRequested
  | RcsWsHandoffAccepted
  | RcsWsHandoffCleared
  | RcsWsEscalationTriggered
  | RcsWsArrivalConfirmed
  | RcsWsFloorHealthUpdated;
