/** SEO release calendar — source: Rapid_Cortex_SEO_Blog_Release_Calendar_Mixed_Release_Order.pdf */

export type ContentHub =
  | "Leadership & Buying"
  | "Campus Safety"
  | "Venue Safety"
  | "911, PSAP & NG911"
  | "Airport Safety"
  | "Buyer Intent";

export interface CalendarEntry {
  releaseNumber: number;
  publishedAt: string;
  hub: ContentHub;
  title: string;
  slug: string;
  seoFocus: string;
}

export const calendarEntries: CalendarEntry[] = [
  {
    releaseNumber: 1,
    publishedAt: "2026-06-27",
    hub: "Leadership & Buying",
    title: "How to Modernize Emergency Communications Without Replacing CAD",
    slug: "modernize-emergency-communications-without-replacing-cad",
    seoFocus: "CAD modernization",
  },
  {
    releaseNumber: 2,
    publishedAt: "2026-06-30",
    hub: "Campus Safety",
    title: "Why Campus Safety Reporting Should Not Require Downloading Another App",
    slug: "campus-safety-no-app-reporting",
    seoFocus: "campus safety reporting",
  },
  {
    releaseNumber: 3,
    publishedAt: "2026-07-04",
    hub: "Venue Safety",
    title: "Why Stadium Safety Reporting Should Be as Easy as Sending a Text",
    slug: "stadium-safety-text-reporting",
    seoFocus: "stadium safety texting",
  },
  {
    releaseNumber: 4,
    publishedAt: "2026-07-07",
    hub: "911, PSAP & NG911",
    title: "Why 911 Call Takers Need Real-Time Transcription During High-Stress Calls",
    slug: "911-real-time-call-transcription",
    seoFocus: "911 call transcription",
  },
  {
    releaseNumber: 5,
    publishedAt: "2026-07-11",
    hub: "Airport Safety",
    title: "Why Airports Need Faster Ways for Travelers to Report Safety Concerns",
    slug: "airport-safety-reporting-platform",
    seoFocus: "airport safety reporting",
  },
  {
    releaseNumber: 6,
    publishedAt: "2026-07-14",
    hub: "Buyer Intent",
    title: "What Is an Incident Intelligence Platform for Public Safety?",
    slug: "what-is-incident-intelligence-platform",
    seoFocus: "incident intelligence platform",
  },
  {
    releaseNumber: 7,
    publishedAt: "2026-07-18",
    hub: "911, PSAP & NG911",
    title: "What Happens When a 911 Caller Cannot Safely Speak?",
    slug: "silent-911-text-chat",
    seoFocus: "silent 911 communication",
  },
  {
    releaseNumber: 8,
    publishedAt: "2026-07-21",
    hub: "Campus Safety",
    title: "Campus Safety Beyond Blue Light Phones: What Universities Need Next",
    slug: "beyond-blue-light-campus-safety",
    seoFocus: "blue light phone alternatives",
  },
  {
    releaseNumber: 9,
    publishedAt: "2026-07-25",
    hub: "Venue Safety",
    title: "What Happens When a Fan Needs Security but Does Not Know Who to Call?",
    slug: "fan-to-security-communication",
    seoFocus: "fan security communication",
  },
  {
    releaseNumber: 10,
    publishedAt: "2026-07-28",
    hub: "Leadership & Buying",
    title: 'What "CJIS-Aligned" Should Mean When Evaluating Public Safety Software',
    slug: "cjis-aligned-public-safety-software",
    seoFocus: "CJIS aligned software",
  },
  {
    releaseNumber: 11,
    publishedAt: "2026-08-01",
    hub: "911, PSAP & NG911",
    title: "The Role of Live Translation in Modern Emergency Communications Centers",
    slug: "live-translation-911-centers",
    seoFocus: "911 translation services",
  },
  {
    releaseNumber: 12,
    publishedAt: "2026-08-04",
    hub: "Campus Safety",
    title: "How QR Codes Can Create Faster Safety Reporting Across Campus",
    slug: "campus-safety-qr-code-reporting",
    seoFocus: "campus safety QR code",
  },
  {
    releaseNumber: 13,
    publishedAt: "2026-08-08",
    hub: "Venue Safety",
    title: "How Arenas Can Improve Fan Safety Without Hiring More Security Staff",
    slug: "arena-safety-without-more-staff",
    seoFocus: "arena security technology",
  },
  {
    releaseNumber: 14,
    publishedAt: "2026-08-11",
    hub: "Airport Safety",
    title: "How Airport Operations Teams Can Receive Passenger Reports in Real Time",
    slug: "airport-passenger-incident-reporting",
    seoFocus: "airport incident reporting",
  },
  {
    releaseNumber: 15,
    publishedAt: "2026-08-15",
    hub: "Buyer Intent",
    title: "What Is the Best Way to Receive Photos and Videos From Emergency Callers?",
    slug: "receive-caller-photos-videos-emergency",
    seoFocus: "emergency caller media intake",
  },
  {
    releaseNumber: 16,
    publishedAt: "2026-08-18",
    hub: "Campus Safety",
    title: "Improving Clery Act Documentation With Better Incident Reporting Workflows",
    slug: "clery-act-incident-reporting-workflows",
    seoFocus: "Clery Act reporting software",
  },
  {
    releaseNumber: 17,
    publishedAt: "2026-08-22",
    hub: "Venue Safety",
    title: "QR Codes, NFC Tags, and Text Messages: The Future of Venue Safety Reporting",
    slug: "venue-safety-qr-nfc-text",
    seoFocus: "venue safety QR code",
  },
  {
    releaseNumber: 18,
    publishedAt: "2026-08-25",
    hub: "Leadership & Buying",
    title: "How Agencies Can Pilot New Technology Without Disrupting Daily Operations",
    slug: "public-safety-technology-pilot-program",
    seoFocus: "public safety pilot program",
  },
  {
    releaseNumber: 19,
    publishedAt: "2026-08-29",
    hub: "911, PSAP & NG911",
    title: "How Real-Time Call Summaries Can Reduce Dispatcher Workload",
    slug: "real-time-call-summaries-dispatchers",
    seoFocus: "dispatcher workload reduction",
  },
  {
    releaseNumber: 20,
    publishedAt: "2026-09-01",
    hub: "Campus Safety",
    title: "Why Residence Halls Need Better Emergency Communication Options",
    slug: "residence-hall-emergency-reporting",
    seoFocus: "dorm safety technology",
  },
  {
    releaseNumber: 21,
    publishedAt: "2026-09-05",
    hub: "Venue Safety",
    title: "How Stadium Security Teams Can Receive Incident Photos and Location Details Faster",
    slug: "stadium-security-photo-location-reporting",
    seoFocus: "stadium incident reporting",
  },
  {
    releaseNumber: 22,
    publishedAt: "2026-09-08",
    hub: "Airport Safety",
    title: "Improving Security Communication Across Airport Terminals",
    slug: "airport-terminal-security-communication",
    seoFocus: "airport security communications",
  },
  {
    releaseNumber: 23,
    publishedAt: "2026-09-12",
    hub: "911, PSAP & NG911",
    title: "How PSAP Supervisors Can Improve Visibility Without Adding More Screens",
    slug: "psap-supervisor-visibility",
    seoFocus: "PSAP supervisor dashboard",
  },
  {
    releaseNumber: 24,
    publishedAt: "2026-09-15",
    hub: "Buyer Intent",
    title: "Rapid Cortex vs. Traditional CAD: What Is the Difference?",
    slug: "rapid-cortex-vs-traditional-cad",
    seoFocus: "Rapid Cortex vs CAD",
  },
  {
    releaseNumber: 25,
    publishedAt: "2026-09-19",
    hub: "Campus Safety",
    title: "How Universities Can Improve Student Safety Communication During Silent Emergencies",
    slug: "silent-campus-emergency-reporting",
    seoFocus: "campus emergency reporting",
  },
  {
    releaseNumber: 26,
    publishedAt: "2026-09-22",
    hub: "Venue Safety",
    title: "Why Venue Safety Is More Than Cameras and Metal Detectors",
    slug: "venue-safety-beyond-cameras",
    seoFocus: "venue security technology",
  },
  {
    releaseNumber: 27,
    publishedAt: "2026-09-26",
    hub: "Leadership & Buying",
    title: "A Public Safety Leader's Guide to Evaluating Real-Time Intelligence Platforms",
    slug: "public-safety-intelligence-platform-guide",
    seoFocus: "public safety intelligence platform",
  },
  {
    releaseNumber: 28,
    publishedAt: "2026-09-29",
    hub: "911, PSAP & NG911",
    title: "Why Every PSAP Should Have a Secure Way to Receive Caller Photos and Videos",
    slug: "psap-caller-photo-video-intake",
    seoFocus: "911 photo video intake",
  },
  {
    releaseNumber: 29,
    publishedAt: "2026-10-03",
    hub: "Campus Safety",
    title: "How Campus Police Can Receive Photos, Videos, and Location Information Faster",
    slug: "campus-police-media-intake",
    seoFocus: "campus police technology",
  },
  {
    releaseNumber: 30,
    publishedAt: "2026-10-06",
    hub: "Venue Safety",
    title: "How Event Security Teams Can Reduce the Time Between Report and Response",
    slug: "event-security-response-time",
    seoFocus: "event security response time",
  },
  {
    releaseNumber: 31,
    publishedAt: "2026-10-10",
    hub: "Airport Safety",
    title: "QR Code Safety Reporting for Airports: Benefits, Risks, and Best Practices",
    slug: "airport-qr-code-safety-reporting",
    seoFocus: "airport QR safety",
  },
  {
    releaseNumber: 32,
    publishedAt: "2026-10-13",
    hub: "Buyer Intent",
    title: "How Much Does Campus Safety Reporting Software Cost?",
    slug: "campus-safety-reporting-software-cost",
    seoFocus: "campus safety reporting software cost",
  },
  {
    releaseNumber: 33,
    publishedAt: "2026-10-17",
    hub: "911, PSAP & NG911",
    title: "Why CAD Alone Is Not Enough for Modern Incident Awareness",
    slug: "cad-vs-incident-awareness-platform",
    seoFocus: "CAD integration public safety",
  },
  {
    releaseNumber: 34,
    publishedAt: "2026-10-20",
    hub: "Campus Safety",
    title: "What a Modern University Safety Communication Layer Looks Like",
    slug: "university-safety-communication-layer",
    seoFocus: "university safety communications",
  },
  {
    releaseNumber: 35,
    publishedAt: "2026-10-24",
    hub: "Venue Safety",
    title: "What Every Sports Venue Should Include in Its Fan Safety Signage",
    slug: "fan-safety-signage-stadiums",
    seoFocus: "stadium safety signage",
  },
  {
    releaseNumber: 36,
    publishedAt: "2026-10-27",
    hub: "Leadership & Buying",
    title: "Why Interoperability Matters More Than Another Standalone Public Safety Tool",
    slug: "public-safety-interoperability",
    seoFocus: "public safety interoperability",
  },
  {
    releaseNumber: 37,
    publishedAt: "2026-10-31",
    hub: "911, PSAP & NG911",
    title: "How 911 Centers Can Prepare for Multimedia Emergency Calls",
    slug: "multimedia-911-call-preparedness",
    seoFocus: "multimedia 911",
  },
  {
    releaseNumber: 38,
    publishedAt: "2026-11-03",
    hub: "Campus Safety",
    title: "How Universities Can Improve Safety During Large Campus Events",
    slug: "campus-event-safety-technology",
    seoFocus: "university event safety",
  },
  {
    releaseNumber: 39,
    publishedAt: "2026-11-07",
    hub: "Venue Safety",
    title: "How Live Event Security Teams Can Improve Situational Awareness",
    slug: "live-event-security-situational-awareness",
    seoFocus: "event security situational awareness",
  },
  {
    releaseNumber: 40,
    publishedAt: "2026-11-10",
    hub: "Airport Safety",
    title: "How Airports Can Improve Incident Visibility Without Replacing Existing Systems",
    slug: "airport-incident-visibility",
    seoFocus: "airport security technology",
  },
  {
    releaseNumber: 41,
    publishedAt: "2026-11-14",
    hub: "Buyer Intent",
    title: "How Much Does Stadium Incident Reporting Technology Cost?",
    slug: "stadium-incident-reporting-software-cost",
    seoFocus: "stadium incident reporting cost",
  },
  {
    releaseNumber: 42,
    publishedAt: "2026-11-17",
    hub: "911, PSAP & NG911",
    title: "What NG911 Means for Smaller 911 Centers",
    slug: "ng911-for-small-psaps",
    seoFocus: "NG911 small PSAP",
  },
  {
    releaseNumber: 43,
    publishedAt: "2026-11-21",
    hub: "Campus Safety",
    title: "How Colleges Can Support Students Who Cannot Safely Make a Phone Call",
    slug: "silent-emergency-reporting-colleges",
    seoFocus: "silent emergency reporting",
  },
  {
    releaseNumber: 44,
    publishedAt: "2026-11-24",
    hub: "Venue Safety",
    title: "How Venue Security Can Route Fan Reports to the Right Team Faster",
    slug: "venue-security-incident-routing",
    seoFocus: "venue security dispatch",
  },
  {
    releaseNumber: 45,
    publishedAt: "2026-11-28",
    hub: "Leadership & Buying",
    title: "The Hidden Cost of Fragmented Emergency Communication Tools",
    slug: "fragmented-emergency-communication-tools",
    seoFocus: "emergency communications software",
  },
  {
    releaseNumber: 46,
    publishedAt: "2026-12-01",
    hub: "911, PSAP & NG911",
    title: "Why Incident Notes Get Lost Between Shifts — and How Continuity Logs Help",
    slug: "911-shift-handoff-continuity-log",
    seoFocus: "911 shift handoff",
  },
  {
    releaseNumber: 47,
    publishedAt: "2026-12-05",
    hub: "Campus Safety",
    title: "How Campus Safety Teams Can Improve Incident Visibility Across Departments",
    slug: "campus-safety-incident-visibility",
    seoFocus: "campus incident management",
  },
  {
    releaseNumber: 48,
    publishedAt: "2026-12-08",
    hub: "Venue Safety",
    title: "How NFC Safety Signs Can Improve Reporting Inside Large Venues",
    slug: "nfc-venue-safety-signage",
    seoFocus: "NFC venue safety",
  },
  {
    releaseNumber: 49,
    publishedAt: "2026-12-12",
    hub: "Airport Safety",
    title: "From Gate to Parking Deck: Modernizing Airport Safety Reporting",
    slug: "airport-safety-reporting-gate-parking",
    seoFocus: "airport safety reporting system",
  },
  {
    releaseNumber: 50,
    publishedAt: "2026-12-15",
    hub: "Buyer Intent",
    title: "What Should a University Look for in a Campus Safety Reporting Platform?",
    slug: "campus-safety-reporting-platform-buyers-guide",
    seoFocus: "campus safety reporting platform",
  },
  {
    releaseNumber: 51,
    publishedAt: "2026-12-19",
    hub: "911, PSAP & NG911",
    title: "How Supervisor Shadow Mode Can Support New Dispatchers",
    slug: "dispatcher-supervisor-shadow-mode",
    seoFocus: "dispatcher training technology",
  },
  {
    releaseNumber: 52,
    publishedAt: "2026-12-22",
    hub: "Campus Safety",
    title: "Why Anonymous Reporting Alone Is Not Enough for Campus Safety",
    slug: "anonymous-reporting-campus-safety",
    seoFocus: "anonymous campus reporting",
  },
  {
    releaseNumber: 53,
    publishedAt: "2026-12-26",
    hub: "Venue Safety",
    title: "Improving Safety Communication in Parking Lots, Entrances, and Concourse Areas",
    slug: "venue-parking-lot-safety-reporting",
    seoFocus: "parking lot incident reporting",
  },
  {
    releaseNumber: 54,
    publishedAt: "2026-12-29",
    hub: "Leadership & Buying",
    title: "10 Features Public Safety Agencies Should Look for in Incident Intelligence Software",
    slug: "incident-intelligence-software-features",
    seoFocus: "incident intelligence software",
  },
  {
    releaseNumber: 55,
    publishedAt: "2027-01-02",
    hub: "911, PSAP & NG911",
    title: "How Emergency Communications Centers Can Improve Documentation Without More Manual Typing",
    slug: "911-documentation-automation",
    seoFocus: "911 incident documentation",
  },
  {
    releaseNumber: 56,
    publishedAt: "2027-01-05",
    hub: "Campus Safety",
    title: "The Parent Perspective: What Families Expect From Campus Safety Programs",
    slug: "college-parent-campus-safety-expectations",
    seoFocus: "college campus safety",
  },
  {
    releaseNumber: 57,
    publishedAt: "2027-01-09",
    hub: "Venue Safety",
    title: "Why Every Venue Needs a Clear 911 Escalation Workflow",
    slug: "venue-911-escalation-workflow",
    seoFocus: "venue 911 escalation",
  },
  {
    releaseNumber: 58,
    publishedAt: "2027-01-12",
    hub: "Buyer Intent",
    title: "What Should a Stadium Look for in a Fan Safety Communication Platform?",
    slug: "fan-safety-platform-buyers-guide",
    seoFocus: "fan safety platform",
  },
  {
    releaseNumber: 59,
    publishedAt: "2027-01-16",
    hub: "911, PSAP & NG911",
    title: "Why Language Access Is Now a Public Safety Priority",
    slug: "language-access-public-safety",
    seoFocus: "public safety language access",
  },
  {
    releaseNumber: 60,
    publishedAt: "2027-01-19",
    hub: "Campus Safety",
    title: "Why Campus Safety Technology Must Work Alongside Existing Systems",
    slug: "campus-safety-system-integration",
    seoFocus: "campus safety integrations",
  },
  {
    releaseNumber: 61,
    publishedAt: "2027-01-23",
    hub: "Venue Safety",
    title: "Why Airports, Arenas, and Stadiums Need a Better Incident Reporting Layer",
    slug: "airport-arena-stadium-reporting",
    seoFocus: "venue incident reporting platform",
  },
  {
    releaseNumber: 62,
    publishedAt: "2027-01-26",
    hub: "Leadership & Buying",
    title: "Why Real-Time Operational Awareness Is Becoming a Public Safety Standard",
    slug: "real-time-operational-awareness-public-safety",
    seoFocus: "operational awareness platform",
  },
  {
    releaseNumber: 63,
    publishedAt: "2027-01-30",
    hub: "911, PSAP & NG911",
    title: "7 Questions Every 911 Director Should Ask Before Buying New Technology",
    slug: "911-technology-buying-guide",
    seoFocus: "911 technology purchasing",
  },
  {
    releaseNumber: 64,
    publishedAt: "2027-02-02",
    hub: "Buyer Intent",
    title: "How Long Does It Take to Deploy Public Safety Communication Software?",
    slug: "public-safety-software-deployment-time",
    seoFocus: "public safety software deployment",
  },
  {
    releaseNumber: 65,
    publishedAt: "2027-02-06",
    hub: "Campus Safety",
    title: "What Students Expect From Modern Campus Safety Technology",
    slug: "modern-campus-safety-technology",
    seoFocus: "campus safety technology",
  },
  {
    releaseNumber: 66,
    publishedAt: "2027-02-09",
    hub: "Buyer Intent",
    title: "Can Public Safety Technology Integrate With Existing CAD and Telephony Systems?",
    slug: "public-safety-cad-telephony-integration",
    seoFocus: "CAD telephony integration",
  },
  {
    releaseNumber: 67,
    publishedAt: "2027-02-13",
    hub: "911, PSAP & NG911",
    title: "From Voice Call to Video: The Future of Emergency Communications",
    slug: "voice-to-video-emergency-communications",
    seoFocus: "emergency video intake",
  },
];
