/** LiveLocation — caller GPS via time-limited SMS link. */
export const PINPOINT_CONFIG = {
  LINK_EXPIRY_MINUTES: 30,
  MAX_LINKS_PER_HOUR: 100,
  LOCATION_UPDATE_RATE_LIMIT_SECONDS: 1,
  MIN_ACCURACY_METERS: 5,
  MAX_ACCURACY_METERS: 1000,
  HIGH_CONFIDENCE_THRESHOLD_METERS: 25,
  MEDIUM_CONFIDENCE_THRESHOLD_METERS: 100,
} as const;

/** Surge View — duplicate-call clustering heuristics. */
export const SURGE_CONFIG = {
  MAX_TIME_WINDOW_MINUTES: 10,
  MAX_DISTANCE_MILES: 0.5,
  MIN_KEYWORD_MATCHES: 2,
  MIN_CONFIDENCE: 0.6,
  MIN_CLUSTER_SIZE: 2,
  MAX_CLUSTER_SIZE: 50,
  CLUSTER_TTL_HOURS: 24,
} as const;
