import type { ComponentType } from "react";
import type { WidgetId } from "@/lib/dashboards/widget-layout-config";
import type { WidgetProps } from "./widget-primitives";
import {
  ActiveCallsGridWidget,
  CapacityQuickUpdateWidget,
  CapacityStatusWidget,
  CampusZoneStatusWidget,
  GuestReportsFeedWidget,
  IncidentQueueWidget,
  IntegrationHealthWidget,
  PlatformHealthBarWidget,
  QaReviewQueueWidget,
  QuickLinksAdminWidget,
  RecentActivityWidget,
  SLABarWidget,
  VenueLiveStatsRowWidget,
} from "./widget-core";
import {
  StatActiveCallsWidget,
  StatAgencyCountWidget,
  StatBedsAvailableWidget,
  StatCamerasOnlineWidget,
  StatIntegrationErrorsWidget,
  StatMrrWidget,
  StatOpenGuestReportsWidget,
  StatOpenIncidentsWidget,
  StatOpenInvoicesWidget,
  StatPendingReviewsWidget,
  StatQrScansTodayWidget,
  StatSlaAnswerTimeWidget,
  StatStaffOnDutyWidget,
  StatUnitsAvailableWidget,
} from "./widget-stats";
import {
  AccessReportsSummaryWidget,
  ActiveGrantsWidget,
  AgencyPipelineWidget,
  ApiKeyStatusWidget,
  ApiPollerStatusWidget,
  AuditActivityWidget,
  BillingHealthWidget,
  CadAdapterStatusWidget,
  CadApprovalQueueWidget,
  CadWritebackAuditWidget,
  ComplianceStatusWidget,
  EscalatedIncidentsWidget,
  FailedAuthEventsWidget,
  FlaggedCallsWidget,
  PlatformNoticesSentWidget,
  QualityTrendChartWidget,
  ReportsSummaryWidget,
  RevenueSnapshotWidget,
  ScorecardStatsWidget,
  ServiceCatalogSummaryWidget,
  SystemAlertsWidget,
  TeamWorkloadWidget,
  TrendOverviewWidget,
  UserLoginActivityWidget,
  WarRoomsActiveWidget,
  WebhookDeliveryWidget,
} from "./widget-panels";
import {
  CameraGridWidget,
  CampusIncidentQueueWidget,
  CampusUserActivityWidget,
  CapacityTrendWidget,
  MyCapacityHistoryWidget,
  QrScanActivityWidget,
  RegionalCapacityMapWidget,
  RoutingEventsWidget,
  StaffBoardWidget,
  VenueHeatmapWidget,
} from "./widget-vertical";

/** Complete registry — every WidgetId must have an implementation. */
export const WIDGET_REGISTRY: Record<WidgetId, ComponentType<WidgetProps>> = {
  "sla-bar": SLABarWidget,
  "active-calls-grid": ActiveCallsGridWidget,
  "incident-queue": IncidentQueueWidget,
  "integration-health": IntegrationHealthWidget,
  "platform-health-bar": PlatformHealthBarWidget,
  "recent-activity": RecentActivityWidget,
  "qa-review-queue": QaReviewQueueWidget,
  "capacity-status": CapacityStatusWidget,
  "capacity-quick-update": CapacityQuickUpdateWidget,
  "guest-reports-feed": GuestReportsFeedWidget,
  "venue-live-stats-row": VenueLiveStatsRowWidget,
  "campus-zone-status": CampusZoneStatusWidget,
  "zone-status": CampusZoneStatusWidget,
  "quick-links-admin": QuickLinksAdminWidget,
  "stat-open-incidents": StatOpenIncidentsWidget,
  "stat-active-calls": StatActiveCallsWidget,
  "stat-units-available": StatUnitsAvailableWidget,
  "stat-sla-answer-time": StatSlaAnswerTimeWidget,
  "stat-agency-count": StatAgencyCountWidget,
  "stat-mrr": StatMrrWidget,
  "stat-open-invoices": StatOpenInvoicesWidget,
  "stat-pending-reviews": StatPendingReviewsWidget,
  "stat-integration-errors": StatIntegrationErrorsWidget,
  "stat-beds-available": StatBedsAvailableWidget,
  "stat-staff-on-duty": StatStaffOnDutyWidget,
  "stat-cameras-online": StatCamerasOnlineWidget,
  "stat-open-guest-reports": StatOpenGuestReportsWidget,
  "stat-qr-scans-today": StatQrScansTodayWidget,
  "cad-approval-queue": CadApprovalQueueWidget,
  "escalated-incidents": EscalatedIncidentsWidget,
  "team-workload": TeamWorkloadWidget,
  "war-rooms-active": WarRoomsActiveWidget,
  "compliance-status": ComplianceStatusWidget,
  "api-key-status": ApiKeyStatusWidget,
  "cad-adapter-status": CadAdapterStatusWidget,
  "user-login-activity": UserLoginActivityWidget,
  "webhook-delivery": WebhookDeliveryWidget,
  "agency-pipeline": AgencyPipelineWidget,
  "billing-health": BillingHealthWidget,
  "platform-notices-sent": PlatformNoticesSentWidget,
  "service-catalog-summary": ServiceCatalogSummaryWidget,
  "system-alerts": SystemAlertsWidget,
  "active-grants": ActiveGrantsWidget,
  "revenue-snapshot": RevenueSnapshotWidget,
  "api-poller-status": ApiPollerStatusWidget,
  "failed-auth-events": FailedAuthEventsWidget,
  "scorecard-stats": ScorecardStatsWidget,
  "quality-trend-chart": QualityTrendChartWidget,
  "reports-summary": ReportsSummaryWidget,
  "flagged-calls": FlaggedCallsWidget,
  "audit-activity": AuditActivityWidget,
  "access-reports-summary": AccessReportsSummaryWidget,
  "cad-writeback-audit": CadWritebackAuditWidget,
  "trend-overview": TrendOverviewWidget,
  "campus-incident-queue": CampusIncidentQueueWidget,
  "qr-scan-activity": QrScanActivityWidget,
  "campus-user-activity": CampusUserActivityWidget,
  "capacity-trend": CapacityTrendWidget,
  "regional-capacity-map": RegionalCapacityMapWidget,
  "routing-events": RoutingEventsWidget,
  "my-capacity-history": MyCapacityHistoryWidget,
  "staff-board": StaffBoardWidget,
  "camera-grid": CameraGridWidget,
  "venue-heatmap": VenueHeatmapWidget,
};
