import { FEATURE_NARRATIVES } from "./feature-narratives.data";

export const RAPID_CORTEX_PLANS = [
  "essential",
  "professional",
  "command",
  "enterprise",
] as const;

export type RapidCortexPlan = (typeof RAPID_CORTEX_PLANS)[number];

export const FEATURE_AVAILABILITY = [
  "included",
  "limited",
  "add_on",
  "unavailable",
] as const;

export type FeatureAvailability = (typeof FEATURE_AVAILABILITY)[number];

export const FEATURE_CATEGORIES = [
  "core_platform",
  "call_handling_operations",
  "language_communication",
  "media_evidence",
  "supervisor_qa",
  "incident_command_collaboration",
  "reliability_technical_operations",
  "deployment_support",
  "cad_integration",
  "ai_call_intelligence",
  "security_compliance",
  "support",
] as const;

export type FeatureCategory = (typeof FEATURE_CATEGORIES)[number];

export type PlanAvailability = Record<RapidCortexPlan, FeatureAvailability>;

export type RapidCortexFeatureExplanations = {
  /** 1 sentence, plain-English summary suitable for matrix/tooltips. */
  shortDescription: string;
  /** 1-2 sentence explanation for dispatch/supervisor/admin operators. */
  operatorExplanation: string;
  /** 1-2 sentence explanation for agency admin / IT configuration owners. */
  adminExplanation: string;
  /** 1-2 sentence explanation for internal proposal/sales context. */
  salesExplanation: string;
};

export type RapidCortexFeature = {
  id: string;
  label: string;
  category: FeatureCategory;
  description: string;
  shortDescription: string;
  operatorExplanation: string;
  adminExplanation: string;
  salesExplanation: string;
  planAvailability: PlanAvailability;
  requiresBackend: boolean;
  requiresSecrets: boolean;
  requiresAgencyApproval: boolean;
  requiresCadVendor: boolean;
  requiresAuditLog: boolean;
  defaultEnabled: boolean;
  routePath?: string;
  apiEndpoints?: string[];
  envVars?: string[];
  rolloutNotes: string;
};

type RapidCortexFeatureBase = Omit<
  RapidCortexFeature,
  "shortDescription" | "operatorExplanation" | "adminExplanation" | "salesExplanation"
>;

const allIncluded: PlanAvailability = {
  essential: "included",
  professional: "included",
  command: "included",
  enterprise: "included",
};

const allUnavailable: PlanAvailability = {
  essential: "unavailable",
  professional: "unavailable",
  command: "unavailable",
  enterprise: "unavailable",
};

const fromPricing = (
  essential: FeatureAvailability,
  professional: FeatureAvailability,
  command: FeatureAvailability,
  enterprise: FeatureAvailability,
): PlanAvailability => ({ essential, professional, command, enterprise });

function mergeFeatureExplanations(feature: RapidCortexFeatureBase): RapidCortexFeatureExplanations {
  const n = FEATURE_NARRATIVES[feature.id];
  if (!n) {
    throw new Error(`Missing FEATURE_NARRATIVES entry for feature id '${feature.id}'`);
  }
  return n;
}

function assertFeatureExplanations(feature: RapidCortexFeature): RapidCortexFeature {
  const fields: Array<keyof RapidCortexFeatureExplanations> = [
    "shortDescription",
    "operatorExplanation",
    "adminExplanation",
    "salesExplanation",
  ];
  for (const field of fields) {
    if (!feature[field] || feature[field].trim().length === 0) {
      throw new Error(`Feature '${feature.id}' is missing '${field}'.`);
    }
  }
  return feature;
}

const RAPID_CORTEX_FEATURES_BASE: RapidCortexFeatureBase[] = [
  // Core platform
  {
    id: "web_application_access",
    label: "Web application access",
    category: "core_platform",
    description: "Browser access to dispatcher, supervisor, and admin surfaces.",
    planAvailability: allIncluded,
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/dashboard",
    rolloutNotes: "Enabled by default for authenticated users.",
  },
  {
    id: "desktop_application_access",
    label: "Desktop application access",
    category: "core_platform",
    description: "Native desktop entry points for operator workflows.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: true,
    rolloutNotes: "Desktop requires per-platform packaging and auth setup.",
  },
  {
    id: "role_based_access_control",
    label: "Role-based access control",
    category: "core_platform",
    description: "Role-scoped permissions for dispatcher, supervisor, admin, and platform roles.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/roles",
    apiEndpoints: ["/api/agency/config"],
    rolloutNotes: "Uses Cognito and agency role mapping.",
  },
  {
    id: "agency_admin_console",
    label: "Agency admin console",
    category: "core_platform",
    description: "Administrative controls for users, settings, and integrations.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin",
    apiEndpoints: ["/api/features", "/api/agency/config"],
    rolloutNotes: "Admin role required.",
  },
  {
    id: "core_reporting",
    label: "Core reporting",
    category: "core_platform",
    description: "Baseline operational reporting and trend views.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/supervisor/team-performance",
    apiEndpoints: ["/api/reliability/slo"],
    rolloutNotes: "Advanced custom reporting can be add-on scoped.",
  },
  {
    id: "audit_logs",
    label: "Audit logs",
    category: "core_platform",
    description: "Audit trail for sensitive actions and operational controls.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/audit-logs",
    apiEndpoints: ["/api/audit-logs"],
    rolloutNotes: "Required for CAD write-back and admin changes.",
  },

  // Call handling / operations
  {
    id: "ai_assisted_intake",
    label: "AI-assisted intake",
    category: "call_handling_operations",
    description: "Assistant support during call intake.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/dispatcher/intake",
    apiEndpoints: ["/api/intake/session", "/api/triage/analyze"],
    envVars: ["PRIMARY_PROVIDER", "SECONDARY_PROVIDER"],
    rolloutNotes: "Provider credentials must be configured for non-mock behavior.",
  },
  {
    id: "live_transcription",
    label: "Live transcription",
    category: "call_handling_operations",
    description: "Live transcription controls and transcript capture.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/dispatcher/transcription",
    apiEndpoints: ["/api/transcription/start", "/api/transcription/stop"],
    rolloutNotes: "Speech provider config required for production quality.",
  },
  {
    id: "call_triage_workflows",
    label: "Call triage workflows",
    category: "call_handling_operations",
    description: "Structured triage and prioritization workflows.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/dispatcher/triage",
    apiEndpoints: ["/api/triage/analyze"],
    rolloutNotes: "Always human-in-the-loop.",
  },
  {
    id: "call_session_history",
    label: "Call session history",
    category: "call_handling_operations",
    description: "Review previously handled sessions.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/history",
    apiEndpoints: ["/api/incidents", "/api/incidents/:id"],
    rolloutNotes: "Uses agency-scoped incident history.",
  },
  {
    id: "active_incident_view",
    label: "Active incident view",
    category: "call_handling_operations",
    description: "Current active incident list and details.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/dispatcher/incidents",
    apiEndpoints: ["/api/incidents", "/api/incidents/:id"],
    rolloutNotes: "Do not imply direct CAD control when CAD mode is disabled.",
  },
  {
    id: "dispatcher_console",
    label: "Dispatcher console",
    category: "call_handling_operations",
    description: "Primary operator console for real-time tasks.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/dispatcher",
    rolloutNotes: "Essential tier may be constrained by policy and seat count.",
  },
  {
    id: "livelocation_secure_caller_share",
    label: "LiveLocation SMS secure link",
    category: "call_handling_operations",
    description:
      "Time-limited SMS link workflows so callers can approve sharing GPS, accuracy estimates, updates, and short history into the incident record.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/pinpoint/t/:token",
    apiEndpoints: ["/api/incidents/:id/pinpoint/links", "/api/public/pinpoint/:token"],
    envVars: ["ENABLE_PINPOINT"],
    rolloutNotes:
      "Gated by agency policy, SMS gateway configuration, and ENABLE_PINPOINT; caller consent workflows are agency-owned.",
  },
  {
    id: "surge_view_related_calls",
    label: "Surge View related-call clustering",
    category: "call_handling_operations",
    description:
      "Heuristic grouping of contemporaneous incidents using proximity, timeframe, overlapping language, call type metadata, and location hints — human interpretation remains authoritative.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    apiEndpoints: ["/api/incidents/:id/surge/clusters", "/api/incidents/:id/surge/analyze"],
    envVars: ["ENABLE_SURGE"],
    rolloutNotes: "Expose gradually in pilot environments; gated by ENABLE_SURGE.",
  },
  {
    id: "operational_maps_mapbox",
    label: "Operational Mapbox workspaces",
    category: "cad_integration",
    description:
      "Embedded Mapbox views that mirror Rapid Cortex’s dark command aesthetic for overlays such as caller-shared pins or incident markers.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    envVars: ["NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN"],
    rolloutNotes:
      "Public Mapbox access tokens are constrained in production; disabling the env var degrades previews without breaking consoles.",
  },
  {
    id: "channel_talk_group_monitoring",
    label: "Channel / talk group monitoring",
    category: "call_handling_operations",
    description: "Monitoring for channels/talk groups with operator context.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/dispatcher",
    rolloutNotes: "Add-on for Essential; vendor radio integration may be required.",
  },
  {
    id: "non_emergency_intake_queue",
    label: "Non-emergency intake queue",
    category: "call_handling_operations",
    description: "Queueing and handling of non-emergency tasks.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/dispatcher/non-emergency",
    rolloutNotes: "Enable when operational policy is approved.",
  },
  {
    id: "backlog_sla_tracking",
    label: "Backlog and SLA tracking",
    category: "call_handling_operations",
    description: "SLA and backlog metrics for intake queues.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/dispatcher/non-emergency",
    rolloutNotes: "Often paired with non-emergency intake queue enablement.",
  },

  // Language / communication
  {
    id: "multilingual_intake",
    label: "Multilingual intake",
    category: "language_communication",
    description: "Multilingual call intake support.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/dispatcher/intake",
    apiEndpoints: ["/api/language/detect", "/api/language/translate"],
    envVars: ["LANGUAGE_PROVIDER"],
    rolloutNotes: "Limited on Essential.",
  },
  {
    id: "live_translation",
    label: "Live translation",
    category: "language_communication",
    description: "Real-time language translation in workflows.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    apiEndpoints: ["/api/language/translate"],
    envVars: ["LANGUAGE_PROVIDER"],
    rolloutNotes: "Essential requires add-on enablement.",
  },
  {
    id: "text_to_voice_support",
    label: "Text-to-voice support",
    category: "language_communication",
    description: "Convert text prompts to voice where enabled.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    apiEndpoints: ["/api/language/text-to-voice"],
    rolloutNotes: "Provider-specific secrets and voice configuration required.",
  },
  {
    id: "language_auto_detection",
    label: "Language auto-detection",
    category: "language_communication",
    description: "Automatic language detection during intake.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    apiEndpoints: ["/api/language/detect"],
    envVars: ["LANGUAGE_PROVIDER"],
    rolloutNotes: "Limited coverage on Essential.",
  },
  {
    id: "text_based_multilingual_workflows",
    label: "Text-based multilingual workflows",
    category: "language_communication",
    description: "Text-first multilingual workflows for silent/text channels.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/dispatcher/intake",
    envVars: ["LANGUAGE_PROVIDER"],
    rolloutNotes: "Pilot in limited mode on Essential.",
  },

  // Media / evidence
  {
    id: "caller_photo_upload",
    label: "Caller photo upload",
    category: "media_evidence",
    description: "Photo upload from caller flows.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/dispatcher/media",
    apiEndpoints: ["/api/media/upload-url", "/api/media/:id"],
    rolloutNotes: "Requires media retention and policy review.",
  },
  {
    id: "caller_video_upload",
    label: "Caller video upload",
    category: "media_evidence",
    description: "Video upload and retrieval for incidents.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/dispatcher/media",
    apiEndpoints: ["/api/media/upload-url", "/api/media/:id"],
    rolloutNotes: "Essential requires add-on enablement.",
  },
  {
    id: "live_caller_media_streaming",
    label: "Live caller media streaming",
    category: "media_evidence",
    description: "Live streaming from caller devices into dispatcher views.",
    planAvailability: fromPricing("add_on", "limited", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/dispatcher/media",
    rolloutNotes: "Professional may require scoped limits.",
  },
  {
    id: "media_audit_trail",
    label: "Media audit trail",
    category: "media_evidence",
    description: "Audit records for media access and updates.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    apiEndpoints: ["/api/media/:id/audit-event"],
    rolloutNotes: "Required for evidentiary media workflows.",
  },
  {
    id: "retention_controls",
    label: "Retention controls",
    category: "media_evidence",
    description: "Configurable retention controls for media/transcript artifacts.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/retention",
    apiEndpoints: ["/api/media/:id/retention"],
    rolloutNotes: "Align with agency retention policy and legal hold process.",
  },

  // Supervisor / QA
  {
    id: "qa_review_tools",
    label: "QA review tools",
    category: "supervisor_qa",
    description: "Supervisor QA review workflows.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/supervisor/qa",
    apiEndpoints: ["/api/qa/reviews"],
    rolloutNotes: "Limited in Essential tier.",
  },
  {
    id: "scorecards",
    label: "Scorecards",
    category: "supervisor_qa",
    description: "Scorecard creation and review.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/supervisor/scorecards",
    apiEndpoints: ["/api/qa/scorecards"],
    rolloutNotes: "Essential requires add-on enablement.",
  },
  {
    id: "coaching_notes",
    label: "Coaching notes",
    category: "supervisor_qa",
    description: "Supervisor coaching notes and follow-up tracking.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/supervisor/coaching",
    apiEndpoints: ["/api/qa/coaching-note"],
    rolloutNotes: "Requires supervisor role.",
  },
  {
    id: "team_performance_dashboards",
    label: "Team performance dashboards",
    category: "supervisor_qa",
    description: "Performance dashboard for teams and dispatchers.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/supervisor/team-performance",
    rolloutNotes: "Includes comparative metrics when data is available.",
  },
  {
    id: "call_quality_trends",
    label: "Call quality trends",
    category: "supervisor_qa",
    description: "Longitudinal quality and trend analytics.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/supervisor/team-performance",
    rolloutNotes: "Best with sustained QA data.",
  },

  // Incident command / collaboration
  {
    id: "major_incident_management",
    label: "Major incident management",
    category: "incident_command_collaboration",
    description: "Large-incident management controls and context.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/command",
    rolloutNotes: "Unavailable on Essential.",
  },
  {
    id: "command_dashboard",
    label: "Command dashboard",
    category: "incident_command_collaboration",
    description: "Unified command-level dashboard view.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/command/dashboard",
    rolloutNotes: "Professional add-on.",
  },
  {
    id: "war_rooms",
    label: "War rooms",
    category: "incident_command_collaboration",
    description: "Collaborative incident war-room workflows.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/command/war-room",
    rolloutNotes: "Not for early Essential deployments.",
  },
  {
    id: "runbooks_playbooks",
    label: "Runbooks / playbooks",
    category: "incident_command_collaboration",
    description: "Operational runbooks and playbooks for incidents.",
    planAvailability: fromPricing("unavailable", "limited", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/command/runbooks",
    rolloutNotes: "Professional access may be limited.",
  },
  {
    id: "incident_timeline_reconstruction",
    label: "Incident timeline reconstruction",
    category: "incident_command_collaboration",
    description: "Timeline reconstruction across incident events.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/command/timeline",
    rolloutNotes: "Essential offers limited capability.",
  },
  {
    id: "post_incident_reviews",
    label: "Post-incident reviews",
    category: "incident_command_collaboration",
    description: "Post-incident review and lessons workflow.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/command/post-incident-review",
    rolloutNotes: "Essential requires add-on.",
  },
  {
    id: "stakeholder_status_pages",
    label: "Stakeholder status pages",
    category: "incident_command_collaboration",
    description: "Status pages for stakeholders and leadership.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/command/dashboard",
    rolloutNotes: "Requires communication governance and approvals.",
  },

  // Reliability / technical operations
  {
    id: "monitoring_integrations",
    label: "Monitoring integrations",
    category: "reliability_technical_operations",
    description: "Monitoring integrations and health surfaces.",
    planAvailability: fromPricing("add_on", "limited", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/reliability/monitoring",
    apiEndpoints: ["/api/reliability/monitoring"],
    envVars: ["OBSERVABILITY_ENDPOINT", "OBSERVABILITY_API_KEY_SECRET_ARN"],
    rolloutNotes: "Command+ baseline; Professional limited.",
  },
  {
    id: "alert_correlation",
    label: "Alert correlation",
    category: "reliability_technical_operations",
    description: "Correlate alerts across operational signals.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/reliability/alerts",
    apiEndpoints: ["/api/reliability/alerts"],
    rolloutNotes: "Unavailable on Essential.",
  },
  {
    id: "escalation_engine",
    label: "Escalation engine",
    category: "reliability_technical_operations",
    description: "Escalation workflows for active incidents.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/reliability/escalation",
    apiEndpoints: ["/api/reliability/escalation"],
    rolloutNotes: "Requires agency escalation policy mapping.",
  },
  {
    id: "on_call_routing",
    label: "On-call routing",
    category: "reliability_technical_operations",
    description: "On-call routing and handoff controls.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/reliability/on-call",
    apiEndpoints: ["/api/reliability/on-call"],
    rolloutNotes: "Command+ baseline.",
  },
  {
    id: "slo_dashboards",
    label: "SLO dashboards",
    category: "reliability_technical_operations",
    description: "SLO dashboards for service reliability.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/reliability/slo",
    apiEndpoints: ["/api/reliability/slo"],
    rolloutNotes: "Unavailable on Essential.",
  },
  {
    id: "reliability_reporting",
    label: "Reliability reporting",
    category: "reliability_technical_operations",
    description: "Reliability reporting and review packs.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/reliability",
    rolloutNotes: "Professional requires add-on.",
  },

  // Deployment / support
  {
    id: "standard_onboarding",
    label: "Standard onboarding",
    category: "deployment_support",
    description: "Baseline onboarding and rollout support.",
    planAvailability: allIncluded,
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Available for all plans.",
  },
  {
    id: "premium_onboarding",
    label: "Premium onboarding",
    category: "deployment_support",
    description: "Expanded onboarding coverage and hypercare.",
    planAvailability: fromPricing("add_on", "limited", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Typically scoped contractually.",
  },
  {
    id: "integration_assistance",
    label: "Integration assistance",
    category: "deployment_support",
    description: "Implementation guidance for integrations.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: true,
    requiresAuditLog: false,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/integrations",
    rolloutNotes: "Vendor involvement required for CAD/RMS specifics.",
  },
  {
    id: "priority_support",
    label: "Priority support",
    category: "deployment_support",
    description: "Priority support workflow and response SLA.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Essential as add-on.",
  },
  {
    id: "dedicated_rollout_planning",
    label: "Dedicated rollout planning",
    category: "deployment_support",
    description: "Structured rollout planning by program stage.",
    planAvailability: fromPricing("add_on", "limited", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Often tied to command/enterprise launches.",
  },
  {
    id: "multi_site_deployment_support",
    label: "Multi-site deployment support",
    category: "deployment_support",
    description: "Support for multi-site and regional deployment rollouts.",
    planAvailability: fromPricing("unavailable", "add_on", "limited", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Primary for enterprise programs.",
  },
  {
    id: "custom_security_compliance_review",
    label: "Custom security/compliance review",
    category: "deployment_support",
    description: "Security/compliance review package (CJIS-aligned controls focus).",
    planAvailability: fromPricing("add_on", "add_on", "limited", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/admin/security",
    rolloutNotes: "Do not claim CJIS certification unless formally completed.",
  },

  // CAD integration safety defaults
  {
    id: "cad_disabled_mode",
    label: "CAD disabled mode",
    category: "cad_integration",
    description: "Rapid Cortex running without direct CAD integration.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/cad",
    apiEndpoints: ["/api/cad/health"],
    envVars: ["CAD_INTEGRATION_MODE"],
    rolloutNotes: "Default and safest starting mode.",
  },
  {
    id: "cad_discovery_workshop",
    label: "CAD discovery workshop",
    category: "cad_integration",
    description: "Discovery and mapping workshop with vendor/agency contacts.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: false,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/cad",
    rolloutNotes: "Required before any write-back plan.",
  },
  {
    id: "cad_read_only_integration",
    label: "CAD read-only integration",
    category: "cad_integration",
    description: "Read-only CAD incident metadata integration.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/admin/cad",
    apiEndpoints: ["/api/cad/health", "/api/cad/incidents/:id"],
    envVars: ["CAD_INTEGRATION_MODE", "CAD_API_BASE_URL"],
    rolloutNotes: "Preferred first live integration mode.",
  },
  {
    id: "cad_assisted_writeback",
    label: "CAD assisted write-back",
    category: "cad_integration",
    description: "Dispatcher-approved write-back submissions to CAD.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/admin/cad",
    apiEndpoints: ["/api/cad/draft-update", "/api/cad/submit-approved-update"],
    envVars: ["CAD_INTEGRATION_MODE", "CAD_WRITEBACK_ENABLED"],
    rolloutNotes: "Must include explicit dispatcher approval and audit logs.",
  },
  {
    id: "cad_automated_writeback",
    label: "CAD automated write-back",
    category: "cad_integration",
    description: "Automated CAD write-back without per-action dispatcher submission.",
    planAvailability: fromPricing("unavailable", "unavailable", "add_on", "limited"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/admin/cad",
    apiEndpoints: ["/api/cad/submit-approved-update"],
    envVars: ["CAD_INTEGRATION_MODE", "CAD_WRITEBACK_ENABLED"],
    rolloutNotes: "Blocked by default; not recommended for early pilots.",
  },
  {
    id: "cad_vendor_adapter",
    label: "CAD vendor adapter",
    category: "cad_integration",
    description: "Vendor-specific adapter implementation behind shared CAD interface.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: true,
    defaultEnabled: false,
    rolloutNotes:
      "CAD integration is deployment-specific — vendor connectors require credentials and explicit packaging for each RMS/CAD lineage.",
  },
  {
    id: "cad_delivery_latency_profiles",
    label: "CAD delivery latency shaping",
    category: "cad_integration",
    description:
      "Contract-scoped ingestion modes (polling, push webhooks, or vendor streaming adapters) layered on CAD read paths where supported.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: true,
    defaultEnabled: false,
    rolloutNotes:
      "Vendor APIs, integration cadence, tenancy throttles, and agency network controls determine observed latency—not a universal millisecond guarantee.",
    apiEndpoints: ["/api/cad/incidents/:id"],
  },
  {
    id: "cad_map_unit_overlay",
    label: "Map unit overlays (CAD / AVL–dependent)",
    category: "cad_integration",
    description:
      "Renders apparatus/unit markers when downstream CAD or AVL feeds expose coordinates that Rapid Cortex ingests through approved adapters.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: true,
    defaultEnabled: false,
    rolloutNotes:
      "No ubiquitous AVL overlays without integration packages, contractual feed delivery, and QA with your CAD vendor.",
    apiEndpoints: ["/api/cad/incidents/:id"],
  },
  {
    id: "cad_field_mapping",
    label: "CAD field mapping",
    category: "cad_integration",
    description: "Field-level read/write mapping governance for CAD payloads.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/admin/cad",
    rolloutNotes: "Agency and vendor signoff required before write mode.",
  },
  {
    id: "cad_audit_logging",
    label: "CAD audit logging",
    category: "cad_integration",
    description: "Audit log entries for CAD reads and write attempts.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/audit-logs",
    apiEndpoints: ["/api/audit-logs"],
    rolloutNotes: "Mandatory for assisted/automated write workflows.",
  },
  {
    id: "cad_rollback_plan",
    label: "CAD rollback plan",
    category: "cad_integration",
    description: "Operational rollback procedure for CAD connector incidents.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/cad",
    apiEndpoints: ["/api/cad/rollback-test"],
    rolloutNotes: "Required before production cutover.",
  },

  // AI / call intelligence
  {
    id: "primary_ai_model",
    label: "Primary AI model",
    category: "ai_call_intelligence",
    description: "Primary model path for analysis and recommendations.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    envVars: ["PRIMARY_PROVIDER"],
    rolloutNotes: "Defaults by deployment stage.",
  },
  {
    id: "secondary_ai_model_review",
    label: "Secondary AI model review",
    category: "ai_call_intelligence",
    description: "Secondary model support for fallback/review workflows.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    envVars: ["SECONDARY_PROVIDER"],
    rolloutNotes: "Can be disabled in lower-risk deployments.",
  },
  {
    id: "tertiary_ai_model_fallback",
    label: "Tertiary AI model fallback",
    category: "ai_call_intelligence",
    description: "Tertiary fallback path for degraded AI availability.",
    planAvailability: fromPricing("add_on", "limited", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    envVars: ["TERTIARY_PROVIDER"],
    rolloutNotes: "Used in resilience-focused deployments.",
  },
  {
    id: "ai_confidence_scoring",
    label: "AI confidence scoring",
    category: "ai_call_intelligence",
    description: "Confidence metadata for AI-generated outputs.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    rolloutNotes:
      "Surfaces calibrated confidence ribbons in dispatcher UI; deployment toggles expose metrics gradually.",
  },
  {
    id: "ai_incident_summarization",
    label: "AI incident summarization",
    category: "ai_call_intelligence",
    description: "AI-generated incident summarization for dispatcher review.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    apiEndpoints: ["/api/incidents/:id/summary"],
    rolloutNotes: "Human review required before external sharing.",
  },
  {
    id: "ai_dispatcher_recommendation_engine",
    label: "AI dispatcher recommendation engine",
    category: "ai_call_intelligence",
    description: "Recommendation engine for dispatcher decisions.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    rolloutNotes: "Assistive only; does not replace dispatcher authority.",
  },
  {
    id: "custom_agency_ai_prompts",
    label: "Custom agency AI prompts",
    category: "ai_call_intelligence",
    description: "Agency-scoped prompt customization and governance.",
    planAvailability: fromPricing("add_on", "limited", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    rolloutNotes: "Governance + regression suites gate each deployment rollout milestone.",
  },
  {
    id: "custom_emergency_workflow_tuning",
    label: "Custom emergency workflow tuning",
    category: "ai_call_intelligence",
    description: "Agency-specific workflow tuning for emergency operations.",
    planAvailability: fromPricing("add_on", "limited", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    rolloutNotes: "Handled through controlled rollout plans.",
  },
  {
    id: "ai_qa_scoring",
    label: "AI QA scoring",
    category: "ai_call_intelligence",
    description: "AI-assisted QA scoring pipeline.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    apiEndpoints: ["/api/qa/scorecards"],
    rolloutNotes:
      "Enable only after QA leadership signs rubrics; KMS-wrapped credentials gate training exports.",
  },
  {
    id: "ai_post_incident_review",
    label: "AI post-incident review",
    category: "ai_call_intelligence",
    description: "AI support for post-incident review workflows.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/command/post-incident-review",
    rolloutNotes: "Subject to post-incident governance policy.",
  },

  // Security / compliance
  {
    id: "secrets_manager_integration",
    label: "Secrets Manager integration",
    category: "security_compliance",
    description: "Secrets handling via AWS Secrets Manager.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    rolloutNotes: "No credentials in frontend code paths.",
  },
  {
    id: "cloudwatch_logging",
    label: "CloudWatch logging",
    category: "security_compliance",
    description: "Operational logs in CloudWatch.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: true,
    rolloutNotes: "Sanitize sensitive data in logs.",
  },
  {
    id: "audit_event_trail",
    label: "Audit event trail",
    category: "security_compliance",
    description: "Audit event capture for sensitive workflows.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    rolloutNotes: "Required for write-back and admin controls.",
  },
  {
    id: "data_retention_policy_controls",
    label: "Data retention policy controls",
    category: "security_compliance",
    description: "Retention policy controls and configuration surfaces.",
    planAvailability: fromPricing("limited", "included", "included", "included"),
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/admin/retention",
    rolloutNotes: "Align to agency legal and policy requirements.",
  },
  {
    id: "role_based_permissions",
    label: "Role-based permissions",
    category: "security_compliance",
    description: "Role-based access permission enforcement.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    rolloutNotes: "AuthN/AuthZ guards required on all protected APIs.",
  },
  {
    id: "tenant_isolation",
    label: "Tenant isolation",
    category: "security_compliance",
    description: "Agency-level isolation of data and access.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    rolloutNotes: "Required for every pilot and production deployment.",
  },
  {
    id: "production_secret_validation",
    label: "Production secret validation",
    category: "security_compliance",
    description: "Validation of production secret configuration before go-live.",
    planAvailability: allIncluded,
    requiresBackend: true,
    requiresSecrets: true,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: true,
    defaultEnabled: true,
    rolloutNotes: "Fail closed where secrets are missing.",
  },

  // Support
  {
    id: "standard_support",
    label: "Standard support",
    category: "support",
    description: "Standard support package.",
    planAvailability: allIncluded,
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: true,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Baseline support path for all plans.",
  },
  {
    id: "priority_support_package",
    label: "Priority support package",
    category: "support",
    description: "Priority support package and faster response.",
    planAvailability: fromPricing("add_on", "included", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: false,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Matches quote-based support terms.",
  },
  {
    id: "mission_support_package",
    label: "Mission support package",
    category: "support",
    description: "Mission support for higher criticality operations.",
    planAvailability: fromPricing("unavailable", "add_on", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Command+ and scoped professional programs.",
  },
  {
    id: "dedicated_support_engineer",
    label: "Dedicated support engineer",
    category: "support",
    description: "Dedicated support engineer assignment.",
    planAvailability: fromPricing("unavailable", "add_on", "limited", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Enterprise-focused support model.",
  },
  {
    id: "dedicated_customer_success_manager",
    label: "Dedicated customer success manager",
    category: "support",
    description: "Dedicated customer success manager engagement.",
    planAvailability: fromPricing("unavailable", "limited", "included", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: false,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Common in command/enterprise rollouts.",
  },
  {
    id: "dedicated_solution_architect",
    label: "Dedicated solution architect",
    category: "support",
    description: "Solution architect support for complex deployments.",
    planAvailability: fromPricing("unavailable", "add_on", "limited", "included"),
    requiresBackend: false,
    requiresSecrets: false,
    requiresAgencyApproval: true,
    requiresCadVendor: true,
    requiresAuditLog: false,
    defaultEnabled: false,
    routePath: "/[jurisdiction]/support",
    rolloutNotes: "Required for complex integrations and multi-site programs.",
  },
];

export const RAPID_CORTEX_FEATURES: RapidCortexFeature[] = RAPID_CORTEX_FEATURES_BASE.map(
  (feature) =>
    assertFeatureExplanations({
      ...feature,
      ...mergeFeatureExplanations(feature),
    }),
);

const byId = new Map(RAPID_CORTEX_FEATURES.map((feature) => [feature.id, feature]));

export function getRapidCortexFeatureById(featureId: string): RapidCortexFeature | null {
  return byId.get(featureId) ?? null;
}

export function listRapidCortexFeaturesByCategory(
  category: FeatureCategory,
): RapidCortexFeature[] {
  return RAPID_CORTEX_FEATURES.filter((feature) => feature.category === category);
}

export { allUnavailable };
