import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Bell,
  Building2,
  ClipboardList,
  CreditCard,
  FileKey,
  FileText,
  Globe,
  Headphones,
  History,
  Image as ImageIcon,
  KeyRound,
  LayoutDashboard,
  LineChart,
  ListChecks,
  Map,
  Megaphone,
  Phone,
  Radio,
  Scale,
  ScrollText,
  Settings,
  Shield,
  Sparkles,
  StickyNote,
  Users,
  Video,
  Languages,
} from "lucide-react";

const FALLBACK: LucideIcon = LayoutDashboard;

const TAB_ICONS: Record<string, LucideIcon> = {
  overview: LayoutDashboard,
  infrastructure: Activity,
  "system-health": Activity,
  integrations: Globe,
  "service-catalog": ListChecks,
  "feature-flags": Shield,
  "system-settings": Settings,
  "cad-admin": Radio,
  security: Shield,
  "location-qr": Map,
  support: Megaphone,
  operations: Megaphone,
  billing: CreditCard,
  plans: ListChecks,
  "api-clients": KeyRound,
  agencies: Building2,
  "feature-access": Shield,
  usage: BarChart3,
  invoices: FileText,
  "add-ons": Sparkles,
  overrides: Shield,
  "api-access": Globe,
  users: Users,
  departments: Building2,
  incidents: History,
  cad: Radio,
  "caller-links": Phone,
  reports: LineChart,
  settings: Settings,
  "active-incident": Activity,
  "caller-information": Users,
  "ai-summary": Sparkles,
  transcription: ScrollText,
  translation: Languages,
  "caller-media": ImageIcon,
  "cad-entry": ClipboardList,
  "safety-alerts": Bell,
  "supervisor-assist": Headphones,
  "recent-calls": History,
  "shift-notes": StickyNote,
  active: Activity,
  escalations: Megaphone,
  map: Map,
  team: Users,
  media: Video,
  shifts: BarChart3,
  transcripts: ScrollText,
  summaries: FileText,
  scorecards: ListChecks,
  coaching: Users,
  training: ClipboardList,
  protocol: Scale,
  access: Shield,
  auth: KeyRound,
  mfa: Shield,
  "api-keys": FileKey,
  "cad-health": Activity,
  audit: ScrollText,
  retention: History,
  detail: FileText,
  safety: Shield,
  command: Radio,
  status: Activity,
  trends: LineChart,
  response: Activity,
  qa: ListChecks,
  grants: FileText,
  export: FileText,
};

export function sidebarIconForTab(tabId: string): LucideIcon {
  return TAB_ICONS[tabId] ?? FALLBACK;
}
