export {
  venueCameraRequestBodySchema,
  venueIntelligenceQuerySchema,
  streamViewerTokenRequestSchema,
  type VenueCameraRequestBody,
  type VenueIntelligenceQuery,
  type StreamViewerTokenRequest,
} from "./schemas.js";

export {
  venueCameraVendorSchema,
  venueCameraStatusSchema,
  venueCameraSchema,
  venueCameraUpsertBodySchema,
  venueCamerasQuerySchema,
  campusCamerasQuerySchema,
  transitCamerasQuerySchema,
  venueIncidentCameraSummarySchema,
  venueIncidentUpdateBodySchema,
  venueIncidentStatusPatchSchema,
  venueCameraViewerTokenQuerySchema,
  venueCameraPtzBodySchema,
  venueCameraDiscoverBodySchema,
  venueCameraDiscoverResponseSchema,
  isRtspProducerVendor,
  venueKvsChannelName,
  RTSP_PRODUCER_VENDORS,
  type VenueCameraDiscoverBody,
  type VenueCameraDiscoverResponse,
  type VenueCamera,
  type VenueCameraUpsertBody,
  type VenueIncidentCameraSummary,
  type VenueIncidentUpdateBody,
  type VenueIncidentStatusPatch,
} from "./camera-registry-schemas.js";

export * from "./operational-map-types.js";

export {
  venueSectionLevelSchema,
  venueSectionStatusSchema,
  venueTypeSchema,
  venueSectionSchema,
  venueSectionUpsertBodySchema,
  venueSectionStatusPatchSchema,
  venueProfileSchema,
  venueProfilePatchSchema,
  type VenueSectionLevel,
  type VenueSectionStatus,
  type VenueType,
  type VenueSection,
  type VenueSectionUpsertBody,
  type VenueSectionStatusPatch,
  type VenueProfile,
  type VenueProfilePatch,
} from "./section-schemas.js";

/** RFP 2396IP — digital incident reporting (case, evidence CoC, form schema, imports). */
export {
  venueCaseStatusSchema,
  venueCaseActionSchema,
  venueCaseActionBodySchema,
  venueEvidenceUploadBodySchema,
  venueEvidenceConfirmBodySchema,
  venueCustodyTransferBodySchema,
  venueSecureShareBodySchema,
  venueFormFieldSchema,
  venueFormSchemaConfigSchema,
  venueFormSchemaPutBodySchema,
  venueIntegrationImportBodySchema,
  DEFAULT_VENUE_FORM_SCHEMA,
  type VenueCaseStatus,
  type VenueCaseAction,
  type VenueCaseActionBody,
  type VenueEvidenceUploadBody,
  type VenueEvidenceConfirmBody,
  type VenueCustodyTransferBody,
  type VenueSecureShareBody,
  type VenueFormSchemaConfig,
  type VenueIntegrationImportBody,
  type VenueFormSchemaPutBody,
} from "./case-management-schemas.js";
