import { RING_AUDIT_EVENT_TYPES } from "rapid-cortex-shared/audit-schema";

/**
 * CJIS-aligned audit vocabulary — align API `AuditEvent.type` strings with these constants.
 * Extend as new sensitive actions are instrumented.
 */
export const AUDIT_EVENT_TYPES = {
  LOGIN_SUCCESS: "auth.login.success",
  LOGIN_FAILURE: "auth.login.failure",
  LOGOUT: "auth.logout",
  INCIDENT_CREATED: "incident.created",
  INCIDENT_ACCESSED: "incident.accessed",
  INCIDENT_CLOSED: "incident.closed",
  INCIDENT_TIMELINE_NOTE: "incident.timeline.note",
  SLA_THRESHOLDS_UPDATED: "sla.thresholds.updated",
  WAR_ROOM_CREATED: "war_room.created",
  WAR_ROOM_JOINED: "war_room.joined",
  WAR_ROOM_LEFT: "war_room.left",
  WAR_ROOM_MESSAGE_POSTED: "war_room.message.posted",
  WAR_ROOM_MESSAGE_PINNED: "war_room.message.pinned",
  WAR_ROOM_CLOSED: "war_room.closed",
  STAKEHOLDER_PAGE_CREATED: "stakeholder_page.created",
  STAKEHOLDER_PAGE_UPDATED: "stakeholder_page.updated",
  STAKEHOLDER_PAGE_DELETED: "stakeholder_page.deleted",
  POST_INCIDENT_REVIEW_CREATED: "post_incident_review.created",
  POST_INCIDENT_REVIEW_UPDATED: "post_incident_review.updated",
  POST_INCIDENT_REVIEW_FINALIZED: "post_incident_review.finalized",
  REPORT_GENERATED: "report.generated",
  TRANSCRIPT_APPEND: "transcript.segment_added",
  TRANSCRIPT_EXPORT: "transcript.export",
  ANALYSIS_CREATED: "analysis.created",
  ANALYSIS_FAILED: "analysis.failed",
  ANALYSIS_SKIPPED: "analysis.skipped",
  VOICE_SESSION_STARTED: "voice.session.started",
  VOICE_SESSION_FINALIZED: "voice.session.finalized",
  VOICE_AUDIO_CHUNK_PROCESSED: "voice.audio_chunk.processed",
  VOICE_LANGUAGE_DETECTED: "voice.language.detected",
  VOICE_TRANSLATION_APPLIED: "voice.translation.applied",
  VOICE_PIPELINE_FAILED: "voice.pipeline.failed",
  ESCALATION_RAISED: "escalation.raised",
  DISPATCHER_REVIEW_ACK: "dispatcher.review_acknowledged",
  ADMIN_USER_CREATE: "admin.user.create",
  ADMIN_USER_UPDATE: "admin.user.update",
  ADMIN_USER_DEACTIVATE: "admin.user.deactivate",
  /** Agency admin / IT admin / RC Admin requires target user password rotation at next sign-in. */
  PASSWORD_CHANGE_REQUIRED_SET: "password_change_required_set",
  AUDIT_EXPORT: "audit.export",
  INTEGRATION_STATE: "integration.state",
  QR_NFC_CODE_CREATED: "qr_nfc.code.created",
  QR_NFC_CODE_UPDATED: "qr_nfc.code.updated",
  QR_NFC_CODE_DEACTIVATED: "qr_nfc.code.deactivated",
  QR_CODE_CREATED: "qr_code.created",
  QR_CODE_DEACTIVATED: "qr_code.deactivated",
  SMS_ROUTING_REGISTERED: "sms.routing.registered",
  SMS_ROUTING_UPDATED: "sms.routing.updated",
  SMS_ROUTING_DEACTIVATED: "sms.routing.deactivated",
  SMS_INBOUND_UNROUTED: "sms.inbound.unrouted",
  PUBLIC_REPORT_SUBMITTED: "public.report.submitted",
  AGENCY_CREATED: "agency.created",
  AGENCY_UPDATED: "agency.updated",
  PLATFORM_NOTICE_CREATED: "platform_notice.created",
  PLATFORM_NOTICE_CANCELLED: "platform_notice.cancelled",
  PLATFORM_NOTICE_ACKED: "platform_notice.acked",
  ADOBE_SIGN_PROVISIONING: "adobe_sign.provisioning",
  RC_LITE_KEY_ISSUED: "rc_lite.key.issued",
  AGENCY_SUSPENDED: "agency.suspended",
  INVITE_CREATED: "invite.created",
  INVITE_REVOKED: "invite.revoked",
  AUTHZ_ACCESS_DENIED: "authz.access_denied",
  NETWORK_POLICY_UPDATED: "network.policy.updated",
  NETWORK_ACCESS_DENIED_IP: "network.access_denied.ip",
  NETWORK_ACCESS_DENIED_TIME: "network.access_denied.time",
  NETWORK_EMERGENCY_OVERRIDE_GRANTED: "network.emergency_override.granted",
  NETWORK_EMERGENCY_OVERRIDE_USED: "network.emergency_override.used",
  NETWORK_EMERGENCY_OVERRIDE_REQUESTED: "network.emergency_override.requested",
  BILLING_PROFILE_UPDATED: "billing.profile.updated",
  BILLING_PLAN_CHANGE_REQUESTED: "billing.plan.change_requested",
  BILLING_SUBSCRIPTION_CANCEL_REQUESTED: "billing.subscription.cancel_requested",
  BILLING_WEBHOOK_PROCESSED: "billing.webhook.processed",
  VIDEO_ASSIST_SESSION_CREATED: "video_assist.session.created",
  VIDEO_ASSIST_SMS_SENT: "video_assist.sms.sent",
  VIDEO_ASSIST_TOKEN_OPENED: "video_assist.token.opened",
  VIDEO_ASSIST_CONSENT: "video_assist.consent.recorded",
  VIDEO_ASSIST_STREAM_STARTED: "video_assist.stream.started",
  VIDEO_ASSIST_STREAM_ENDED: "video_assist.stream.ended",
  VIDEO_ASSIST_SESSION_CANCELED: "video_assist.session.canceled",
  VIDEO_ASSIST_SIGNAL: "video_assist.signal.exchanged",
  /** Dispatcher issued KVS viewer credentials (Connect / venue camera sessions). */
  VIDEO_ASSIST_VIEWER: "video_assist.viewer.access",
  // ── Venue ──────────────────────────────────────────────────────────────────
  VENUE_INTELLIGENCE_VIEWED: "venue.intelligence.viewed",
  VENUE_CAMERA_SESSION_STARTED: "venue.camera.session_started",
  // ── Silent text ────────────────────────────────────────────────────────────
  SILENT_TEXT_SESSION_CREATED: "silent_text.session.created",
  SILENT_TEXT_SMS_SENT: "silent_text.sms.sent",
  SILENT_TEXT_SMS_FAILED: "silent_text.sms.failed",
  SILENT_TEXT_SMS_RESENT: "silent_text.sms.resent",
  SILENT_TEXT_OPENED: "silent_text.session.opened",
  SILENT_TEXT_MESSAGE: "silent_text.message.sent",
  SILENT_TEXT_SESSION_CLOSED: "silent_text.session.closed",
  SILENT_TEXT_SESSION_CANCELED: "silent_text.session.canceled",
  SILENT_TEXT_HIGH_RISK: "silent_text.session.high_risk_marked",
  QA_SESSION_CREATED: "qa.session.created",
  QA_SESSION_UPDATED: "qa.session.updated",
  QA_SESSION_SCORED: "qa.session.scored",
  QA_SESSION_SCORING_FAILED: "qa.session.scoring_failed",
  QA_TEMPLATE_CREATED: "qa.template.created",
  QA_TEMPLATE_UPDATED: "qa.template.updated",
  QA_TEMPLATE_DELETED: "qa.template.deleted",
  INCIDENT_MEDIA_REQUESTED: "incident_media.requested",
  INCIDENT_MEDIA_SMS_SENT: "incident_media.sms.sent",
  INCIDENT_MEDIA_SMS_FAILED: "incident_media.sms.failed",
  INCIDENT_MEDIA_UPLOAD_URL_ISSUED: "incident_media.upload_url.issued",
  INCIDENT_MEDIA_UPLOAD_CONFIRMED: "incident_media.upload.confirmed",
  INCIDENT_MEDIA_CANCELED: "incident_media.canceled",
  LIVE_VIDEO_REQUESTED: "live_video.requested",
  LIVE_VIDEO_SMS_SENT: "live_video.sms.sent",
  LIVE_VIDEO_SMS_FAILED: "live_video.sms.failed",
  LIVE_VIDEO_CALLER_JOINED: "live_video.caller.joined",
  LIVE_VIDEO_DISPATCHER_JOINED: "live_video.dispatcher.joined",
  LIVE_VIDEO_ACTIVATED: "live_video.activated",
  LIVE_VIDEO_ENDED: "live_video.ended",
  LIVE_VIDEO_EXPIRED: "live_video.expired",
  LIVE_VIDEO_STORAGE_CONFIGURED: "live_video.storage_configured",
  LIVE_VIDEO_PLAYBACK_ACCESSED: "live_video.playback_accessed",
  SOP_UPLOAD_URL_ISSUED: "sop.document.upload_url_issued",
  SOP_PROTOCOL_DETECTED: "sop.protocol.detected",
  SOP_PROTOCOL_DISMISSED: "sop.protocol.dismissed",
  SOP_PROTOCOL_OVERRIDE: "sop.protocol.override",
  SOP_PROTOCOL_STEP_TOGGLED: "sop.protocol.step_toggled",
  TRIAGE_RECORDED: "triage.recorded",
  TRIAGE_OVERRIDDEN: "triage.overridden",
  TRIAGE_CLASSIFIED: "triage.classified",
  TRIAGE_QUEUE_UPDATED: "triage.queue_updated",
  TRIAGE_ESCALATED: "triage.escalated",
  FIELD_CONFIDENCE_SCORED: "field_confidence.scored",
  AI_GROUNDING_DOWNGRADE: "ai.grounding_downgrade",
  WELLNESS_TRAUMA_FLAG_CREATED: "wellness.trauma_flag.created",
  WELLNESS_TRAUMA_FLAG_ACK: "wellness.trauma_flag.acknowledged",
  INCIDENT_SHARE_CREATED: "incident.share.created",
  INCIDENT_SHARE_REVOKED: "incident.share.revoked",
  DISPATCHER_COACHING_NOTE_CREATED: "dispatcher.coaching_note.created",
  ADMIN_ANALYTICS_REFRESHED: "admin.analytics.refreshed",
  CALLER_CARD_VIEWED: "caller_card.viewed",
  PREMISE_NOTE_CREATED: "premise_note.created",
  PREMISE_NOTE_UPDATED: "premise_note.updated",
  /** Agency admin / IT admin / RC Admin requested a presigned desktop installer URL. */
  DESKTOP_INSTALLER_DOWNLOAD_URL_ISSUED: "desktop.installer.download_url_issued",
  /** Scheduled retention job removed a CJI-bearing row (see also immutable `DataDeletionAuditTable`). */
  RETENTION_RECORD_PURGED: "retention.record_purged",
  /** Immutable append-only record in `DataDeletionAuditTable` (Lambda `retentionExecutor`). */
  DATA_DELETION_AUDIT: "retention.data_deletion_audit",
  LEGAL_HOLD_SET: "retention.legal_hold.set",
  LEGAL_HOLD_CLEARED: "retention.legal_hold.cleared",
  PERMISSION_ROLE_UPDATED: "permission.role_updated",
  PERMISSION_USER_UPDATED: "permission.user_updated",
  PERMISSION_USER_OVERRIDES_CLEARED: "permission.user_overrides_cleared",
  RCITADMIN_CROSS_TENANT_ACCESS: "rcitadmin.cross_tenant_access",
  RCSUPERADMIN_GRANT_ISSUED: "rcsuperadmin.grant_issued",
  RCSUPERADMIN_GRANT_REVOKED: "rcsuperadmin.grant_revoked",
  RCSUPERADMIN_GRANT_EXPIRED: "rcsuperadmin.grant_expired",
  /** Caller attempted CAD write-back while gated off (audit row includes `blocked`, `reason`). */
  CAD_WRITEBACK_BLOCKED: "cad.writeback.blocked",
  /** Dispatcher saved CAD workspace fields to the incident (no vendor write-back). */
  CAD_DISPATCHER_WORKSPACE_SAVE: "cad.dispatcher_workspace.save",
  /** Internal Cortex SEO Intelligence — page scan persisted for agency (may include target URL metadata only). */
  SEO_INTELLIGENCE_SCAN_RUN: "seo.intelligence.scan_run",
  SEO_INTELLIGENCE_ISSUE_UPDATED: "seo.intelligence.issue_updated",
  CAD_INTEGRATION_CREATED: "cad.integration.created",
  CAD_INTEGRATION_UPDATED: "cad.integration.updated",
  CAD_INTEGRATION_DELETED: "cad.integration.deleted",
  CAD_INTEGRATION_TESTED: "cad.integration.tested",
  CAD_WEBHOOK_RECEIVED: "cad.webhook.received",
  CAD_INCIDENT_INGESTED: "cad.incident.ingested",
  CAD_WRITEBACK_SUBMITTED: "cad.writeback.submitted",
  CAD_WRITEBACK_APPROVED: "cad.writeback.approved",
  CAD_WRITEBACK_REJECTED: "cad.writeback.rejected",
  CAD_WRITEBACK_FAILED: "cad.writeback.failed",
  PINPOINT_LINK_GENERATED: "pinpoint.link_generated",
  PINPOINT_LOCATION_CAPTURED: "pinpoint.location_captured",
  PINPOINT_LINK_REVOKED: "pinpoint.link_revoked",
  SURGE_CLUSTER_DETECTED: "surge.cluster_detected",
  SURGE_CLUSTER_CONFIRMED: "surge.cluster_confirmed",
  SURGE_CLUSTER_SPLIT: "surge.cluster_split",
  SURGE_CLUSTER_DISMISSED: "surge.cluster_dismissed",
  SURGE_CALL_ANALYZED: "surge.call_analyzed",
  HOSPITAL_PREALERT_CREATED: "hospital.prealert.created",
  HOSPITAL_PREALERT_SENT: "hospital.prealert.sent",
  HOSPITAL_PREALERT_ACKNOWLEDGED: "hospital.prealert.acknowledged",
  HOSPITAL_PREALERT_CANCELLED: "hospital.prealert.cancelled",
  HOSPITAL_PROFILE_CREATED: "hospital.profile.created",
  HOSPITAL_PROFILE_UPDATED: "hospital.profile.updated",
  HOSPITAL_CAPACITY_UPDATED: "hospital.capacity.updated",
  HOSPITAL_MCI_PLAN_CREATED: "hospital.mci.plan_created",
  HOSPITAL_MCI_PLAN_ACTIVATED: "hospital.mci.plan_activated",
  HOSPITAL_PORTAL_USER_REGISTERED: "hospital.portal.user_registered",
  CALL_TRANSFER_INITIATED: "call.transfer.initiated",
  CALL_TRANSFER_ACCEPTED: "call.transfer.accepted",
  CALL_TRANSFER_DECLINED: "call.transfer.declined",
  CALL_TAKEOVER_INITIATED: "call.takeover.initiated",

  ...RING_AUDIT_EVENT_TYPES,
} as const;

export type AuditEventTypeName = (typeof AUDIT_EVENT_TYPES)[keyof typeof AUDIT_EVENT_TYPES];
