"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export const REPORT_LANG_STORAGE_KEY = "rc_report_lang";

export const REPORT_LANGUAGES = [
  { code: "EN", label: "English", flag: "🇺🇸", dir: "ltr" as const },
  { code: "ES", label: "Spanish", flag: "🇪🇸", dir: "ltr" as const },
  { code: "FR", label: "French", flag: "🇫🇷", dir: "ltr" as const },
  { code: "PT", label: "Portuguese", flag: "🇵🇹", dir: "ltr" as const },
  { code: "ZH", label: "Chinese (Simplified)", flag: "🇨🇳", dir: "ltr" as const },
  { code: "JA", label: "Japanese", flag: "🇯🇵", dir: "ltr" as const },
  { code: "KO", label: "Korean", flag: "🇰🇷", dir: "ltr" as const },
  { code: "AR", label: "Arabic", flag: "🇸🇦", dir: "rtl" as const },
] as const;

export type ReportLangCode = (typeof REPORT_LANGUAGES)[number]["code"];

type StringTable = Record<string, string>;

/** Shared + vertical UI strings for public NFC/QR intake. */
const DICTIONARIES: Record<ReportLangCode, StringTable> = {
  EN: {
    selectLanguage: "Select language",
    secureReporting: "Secure reporting",
    campusHeader: "Rapid Cortex Campus",
    venueHeader: "Rapid Cortex Venue",
    campusAgencyLabel: "Campus Safety Reporting",
    venueAgencyLabel: "Venue Security",
    campusTitle: "Report a safety concern",
    venueTitle: "Get help now",
    campusDesc:
      "Send a report directly to campus safety. You can call, submit details, share your location, or report discreetly.",
    venueDesc:
      "Report an incident or request security and medical staff. Your report goes directly to the venue operations team.",
    campusCall: "Call Campus Security",
    venueCall: "Contact venue security",
    call911: "Emergency? Call 911",
    lifeThreat: "For life-threatening emergencies, call 911.",
    orSubmit: "Or submit a report",
    submitAReport: "Submit a report",
    category: "Category",
    incidentType: "What type of incident?",
    optional: "(optional)",
    whatHappening: "What is happening?",
    whatHappeningHint: "Describe what you are seeing or experiencing...",
    whatHappeningError: "Please describe what is happening before submitting.",
    locationZone: "Your location / zone",
    yourLocation: "Your location",
    reportAnonymously: "Report anonymously",
    yourName: "Your name",
    yourPhone: "Your phone number",
    optionalPlaceholder: "Optional",
    addPhotoVideo: "Add photo / video",
    shareLocation: "Share location",
    locationShared: "Location shared",
    securityNotice:
      "Reports are sent securely to the appropriate safety team. Anonymous reporting is available — your name and phone are not required.",
    submitReport: "Submit report",
    submitting: "Submitting…",
    campusSuccessTitle: "Report submitted",
    venueSuccessTitle: "Report received",
    campusSuccessDesc: "Campus security has been notified and will respond shortly.",
    venueSuccessDesc: "The venue operations team has been notified and is responding.",
    submitAnother: "Submit another report",
    emergencyFooter: "Emergency? Call 911",
    brandDomain: "app.rapidcortex.us",
    live: "LIVE",
    // Campus categories
    "cat.campus.0": "Medical concern",
    "cat.campus.1": "Suspicious activity",
    "cat.campus.2": "Harassment / threat",
    "cat.campus.3": "Mental health concern",
    "cat.campus.4": "Facility hazard",
    "cat.campus.5": "Other",
    // Venue categories
    "cat.venue.0": "Fight / disturbance",
    "cat.venue.1": "Medical emergency",
    "cat.venue.2": "Lost child",
    "cat.venue.3": "Suspicious item",
    "cat.venue.4": "Spill / hazard",
    "cat.venue.5": "Need staff",
  },
  ES: {
    selectLanguage: "Seleccionar idioma",
    secureReporting: "Informe seguro",
    campusHeader: "Rapid Cortex Campus",
    venueHeader: "Rapid Cortex Venue",
    campusAgencyLabel: "Informes de seguridad del campus",
    venueAgencyLabel: "Seguridad del recinto",
    campusTitle: "Reportar una preocupación de seguridad",
    venueTitle: "Obtener ayuda ahora",
    campusDesc:
      "Envíe un informe directamente a seguridad del campus. Puede llamar, enviar detalles, compartir su ubicación o reportar de forma discreta.",
    venueDesc:
      "Reporte un incidente o solicite personal de seguridad y médico. Su informe llega al equipo de operaciones del recinto.",
    campusCall: "Llamar a seguridad del campus",
    venueCall: "Contactar seguridad del recinto",
    call911: "¿Emergencia? Llame al 911",
    lifeThreat: "En emergencias que amenazan la vida, llame al 911.",
    orSubmit: "O envíe un informe",
    submitAReport: "Enviar un informe",
    category: "Categoría",
    incidentType: "¿Qué tipo de incidente?",
    optional: "(opcional)",
    whatHappening: "¿Qué está pasando?",
    whatHappeningHint: "Describa lo que ve o está experimentando…",
    whatHappeningError: "Describa lo que está pasando antes de enviar.",
    locationZone: "Su ubicación / zona",
    yourLocation: "Su ubicación",
    reportAnonymously: "Reportar de forma anónima",
    yourName: "Su nombre",
    yourPhone: "Su número de teléfono",
    optionalPlaceholder: "Opcional",
    addPhotoVideo: "Agregar foto / video",
    shareLocation: "Compartir ubicación",
    locationShared: "Ubicación compartida",
    securityNotice:
      "Los informes se envían de forma segura al equipo de seguridad correspondiente. El reporte anónimo está disponible: no se requieren nombre ni teléfono.",
    submitReport: "Enviar informe",
    submitting: "Enviando…",
    campusSuccessTitle: "Informe enviado",
    venueSuccessTitle: "Informe recibido",
    campusSuccessDesc: "Seguridad del campus ha sido notificada y responderá pronto.",
    venueSuccessDesc: "El equipo de operaciones del recinto ha sido notificado y está respondiendo.",
    submitAnother: "Enviar otro informe",
    emergencyFooter: "¿Emergencia? Llame al 911",
    brandDomain: "app.rapidcortex.us",
    live: "EN VIVO",
    "cat.campus.0": "Preocupación médica",
    "cat.campus.1": "Actividad sospechosa",
    "cat.campus.2": "Acoso / amenaza",
    "cat.campus.3": "Salud mental",
    "cat.campus.4": "Peligro en instalaciones",
    "cat.campus.5": "Otro",
    "cat.venue.0": "Pelea / disturbio",
    "cat.venue.1": "Emergencia médica",
    "cat.venue.2": "Niño perdido",
    "cat.venue.3": "Objeto sospechoso",
    "cat.venue.4": "Derrame / peligro",
    "cat.venue.5": "Necesito personal",
  },
  FR: {
    selectLanguage: "Choisir la langue",
    secureReporting: "Signalement sécurisé",
    campusHeader: "Rapid Cortex Campus",
    venueHeader: "Rapid Cortex Venue",
    campusAgencyLabel: "Signalement sécurité campus",
    venueAgencyLabel: "Sécurité du site",
    campusTitle: "Signaler un problème de sécurité",
    venueTitle: "Obtenir de l’aide maintenant",
    campusDesc:
      "Envoyez un signalement directement à la sécurité du campus. Vous pouvez appeler, envoyer des détails, partager votre position ou signaler discrètement.",
    venueDesc:
      "Signalez un incident ou demandez le personnel de sécurité et médical. Votre signalement va à l’équipe des opérations.",
    campusCall: "Appeler la sécurité du campus",
    venueCall: "Contacter la sécurité du site",
    call911: "Urgence ? Appelez le 911",
    lifeThreat: "Pour toute urgence vitale, appelez le 911.",
    orSubmit: "Ou envoyer un signalement",
    submitAReport: "Envoyer un signalement",
    category: "Catégorie",
    incidentType: "Quel type d’incident ?",
    optional: "(facultatif)",
    whatHappening: "Que se passe-t-il ?",
    whatHappeningHint: "Décrivez ce que vous voyez ou vivez…",
    whatHappeningError: "Veuillez décrire la situation avant d’envoyer.",
    locationZone: "Votre emplacement / zone",
    yourLocation: "Votre emplacement",
    reportAnonymously: "Signaler anonymement",
    yourName: "Votre nom",
    yourPhone: "Votre numéro de téléphone",
    optionalPlaceholder: "Facultatif",
    addPhotoVideo: "Ajouter photo / vidéo",
    shareLocation: "Partager la position",
    locationShared: "Position partagée",
    securityNotice:
      "Les signalements sont envoyés de façon sécurisée à l’équipe concernée. Le signalement anonyme est disponible — nom et téléphone non requis.",
    submitReport: "Envoyer le signalement",
    submitting: "Envoi…",
    campusSuccessTitle: "Signalement envoyé",
    venueSuccessTitle: "Signalement reçu",
    campusSuccessDesc: "La sécurité du campus a été informée et répondra bientôt.",
    venueSuccessDesc: "L’équipe des opérations a été informée et intervient.",
    submitAnother: "Envoyer un autre signalement",
    emergencyFooter: "Urgence ? Appelez le 911",
    brandDomain: "app.rapidcortex.us",
    live: "EN DIRECT",
    "cat.campus.0": "Problème médical",
    "cat.campus.1": "Activité suspecte",
    "cat.campus.2": "Harcèlement / menace",
    "cat.campus.3": "Santé mentale",
    "cat.campus.4": "Danger dans les locaux",
    "cat.campus.5": "Autre",
    "cat.venue.0": "Bagarre / trouble",
    "cat.venue.1": "Urgence médicale",
    "cat.venue.2": "Enfant perdu",
    "cat.venue.3": "Objet suspect",
    "cat.venue.4": "Déversement / danger",
    "cat.venue.5": "Besoin de personnel",
  },
  PT: {
    selectLanguage: "Selecionar idioma",
    secureReporting: "Relato seguro",
    campusHeader: "Rapid Cortex Campus",
    venueHeader: "Rapid Cortex Venue",
    campusAgencyLabel: "Relato de segurança do campus",
    venueAgencyLabel: "Segurança do local",
    campusTitle: "Relatar uma preocupação de segurança",
    venueTitle: "Obter ajuda agora",
    campusDesc:
      "Envie um relato diretamente à segurança do campus. Você pode ligar, enviar detalhes, compartilhar a localização ou relatar discretamente.",
    venueDesc:
      "Relate um incidente ou solicite segurança e equipe médica. Seu relato vai à equipe de operações do local.",
    campusCall: "Ligar para a segurança do campus",
    venueCall: "Contatar a segurança do local",
    call911: "Emergência? Ligue 911",
    lifeThreat: "Em emergências com risco de vida, ligue 911.",
    orSubmit: "Ou envie um relato",
    submitAReport: "Enviar um relato",
    category: "Categoria",
    incidentType: "Que tipo de incidente?",
    optional: "(opcional)",
    whatHappening: "O que está acontecendo?",
    whatHappeningHint: "Descreva o que você está vendo ou vivenciando…",
    whatHappeningError: "Descreva o que está acontecendo antes de enviar.",
    locationZone: "Sua localização / zona",
    yourLocation: "Sua localização",
    reportAnonymously: "Relatar anonimamente",
    yourName: "Seu nome",
    yourPhone: "Seu telefone",
    optionalPlaceholder: "Opcional",
    addPhotoVideo: "Adicionar foto / vídeo",
    shareLocation: "Compartilhar localização",
    locationShared: "Localização compartilhada",
    securityNotice:
      "Os relatos são enviados com segurança à equipe adequada. O relato anônimo está disponível — nome e telefone não são obrigatórios.",
    submitReport: "Enviar relato",
    submitting: "Enviando…",
    campusSuccessTitle: "Relato enviado",
    venueSuccessTitle: "Relato recebido",
    campusSuccessDesc: "A segurança do campus foi notificada e responderá em breve.",
    venueSuccessDesc: "A equipe de operações foi notificada e está respondendo.",
    submitAnother: "Enviar outro relato",
    emergencyFooter: "Emergência? Ligue 911",
    brandDomain: "app.rapidcortex.us",
    live: "AO VIVO",
    "cat.campus.0": "Preocupação médica",
    "cat.campus.1": "Atividade suspeita",
    "cat.campus.2": "Assédio / ameaça",
    "cat.campus.3": "Saúde mental",
    "cat.campus.4": "Perigo nas instalações",
    "cat.campus.5": "Outro",
    "cat.venue.0": "Briga / distúrbio",
    "cat.venue.1": "Emergência médica",
    "cat.venue.2": "Criança perdida",
    "cat.venue.3": "Item suspeito",
    "cat.venue.4": "Derramamento / perigo",
    "cat.venue.5": "Preciso de equipe",
  },
  ZH: {
    selectLanguage: "选择语言",
    secureReporting: "安全上报",
    campusHeader: "Rapid Cortex Campus",
    venueHeader: "Rapid Cortex Venue",
    campusAgencyLabel: "校园安全上报",
    venueAgencyLabel: "场馆安保",
    campusTitle: "报告安全问题",
    venueTitle: "立即求助",
    campusDesc: "直接向校园安全部门发送报告。您可以拨打电话、提交详情、共享位置或匿名报告。",
    venueDesc: "报告事件或请求安保与医护人员。您的报告将直接发送给场馆运营团队。",
    campusCall: "致电校园安保",
    venueCall: "联系场馆安保",
    call911: "紧急情况？拨打 911",
    lifeThreat: "危及生命的紧急情况请拨打 911。",
    orSubmit: "或提交报告",
    submitAReport: "提交报告",
    category: "类别",
    incidentType: "事件类型？",
    optional: "（可选）",
    whatHappening: "发生了什么？",
    whatHappeningHint: "描述您看到或正在经历的情况…",
    whatHappeningError: "提交前请描述发生的情况。",
    locationZone: "您的位置 / 区域",
    yourLocation: "您的位置",
    reportAnonymously: "匿名报告",
    yourName: "您的姓名",
    yourPhone: "您的电话",
    optionalPlaceholder: "可选",
    addPhotoVideo: "添加照片 / 视频",
    shareLocation: "共享位置",
    locationShared: "已共享位置",
    securityNotice: "报告将安全发送至相应安全团队。可匿名报告——无需姓名和电话。",
    submitReport: "提交报告",
    submitting: "提交中…",
    campusSuccessTitle: "报告已提交",
    venueSuccessTitle: "报告已收到",
    campusSuccessDesc: "校园安保已收到通知，将很快响应。",
    venueSuccessDesc: "场馆运营团队已收到通知，正在响应。",
    submitAnother: "再提交一份报告",
    emergencyFooter: "紧急情况？拨打 911",
    brandDomain: "app.rapidcortex.us",
    live: "直播中",
    "cat.campus.0": "医疗问题",
    "cat.campus.1": "可疑活动",
    "cat.campus.2": "骚扰 / 威胁",
    "cat.campus.3": "心理健康",
    "cat.campus.4": "设施隐患",
    "cat.campus.5": "其他",
    "cat.venue.0": "打架 / 骚乱",
    "cat.venue.1": "医疗紧急情况",
    "cat.venue.2": "走失儿童",
    "cat.venue.3": "可疑物品",
    "cat.venue.4": "泄漏 / 危险",
    "cat.venue.5": "需要工作人员",
  },
  JA: {
    selectLanguage: "言語を選択",
    secureReporting: "安全な通報",
    campusHeader: "Rapid Cortex Campus",
    venueHeader: "Rapid Cortex Venue",
    campusAgencyLabel: "キャンパス安全通報",
    venueAgencyLabel: "会場警備",
    campusTitle: "安全上の懸念を報告",
    venueTitle: "今すぐ助けを求める",
    campusDesc:
      "キャンパス警備に直接報告できます。電話、詳細送信、位置共有、匿名報告が可能です。",
    venueDesc:
      "事案の報告、または警備・医療スタッフを要請できます。報告は会場運営チームに直接届きます。",
    campusCall: "キャンパス警備に電話",
    venueCall: "会場警備に連絡",
    call911: "緊急？911に電話",
    lifeThreat: "生命に関わる緊急時は911に電話してください。",
    orSubmit: "または報告を送信",
    submitAReport: "報告を送信",
    category: "カテゴリ",
    incidentType: "どのような事案ですか？",
    optional: "（任意）",
    whatHappening: "何が起きていますか？",
    whatHappeningHint: "見ていること・状況を説明してください…",
    whatHappeningError: "送信前に状況を説明してください。",
    locationZone: "現在地 / ゾーン",
    yourLocation: "現在地",
    reportAnonymously: "匿名で報告",
    yourName: "お名前",
    yourPhone: "電話番号",
    optionalPlaceholder: "任意",
    addPhotoVideo: "写真 / 動画を追加",
    shareLocation: "位置を共有",
    locationShared: "位置を共有済み",
    securityNotice:
      "報告は適切な安全チームへ安全に送信されます。匿名報告では氏名と電話は不要です。",
    submitReport: "報告を送信",
    submitting: "送信中…",
    campusSuccessTitle: "報告を送信しました",
    venueSuccessTitle: "報告を受信しました",
    campusSuccessDesc: "キャンパス警備に通知され、まもなく対応します。",
    venueSuccessDesc: "会場運営チームに通知され、対応中です。",
    submitAnother: "別の報告を送信",
    emergencyFooter: "緊急？911に電話",
    brandDomain: "app.rapidcortex.us",
    live: "ライブ",
    "cat.campus.0": "医療の懸念",
    "cat.campus.1": "不審な行動",
    "cat.campus.2": "嫌がらせ / 脅迫",
    "cat.campus.3": "メンタルヘルス",
    "cat.campus.4": "施設の危険",
    "cat.campus.5": "その他",
    "cat.venue.0": "喧嘩 / 騒動",
    "cat.venue.1": "医療緊急事態",
    "cat.venue.2": "迷子の子ども",
    "cat.venue.3": "不審物",
    "cat.venue.4": "こぼれた液体 / 危険",
    "cat.venue.5": "スタッフが必要",
  },
  KO: {
    selectLanguage: "언어 선택",
    secureReporting: "안전한 신고",
    campusHeader: "Rapid Cortex Campus",
    venueHeader: "Rapid Cortex Venue",
    campusAgencyLabel: "캠퍼스 안전 신고",
    venueAgencyLabel: "공연장 보안",
    campusTitle: "안전 문제 신고",
    venueTitle: "지금 도움 요청",
    campusDesc:
      "캠퍼스 보안으로 직접 신고하세요. 전화, 세부 제출, 위치 공유 또는 익명 신고가 가능합니다.",
    venueDesc:
      "사건을 신고하거나 보안·의료 직원을 요청하세요. 보고서는 공연장 운영팀에 직접 전달됩니다.",
    campusCall: "캠퍼스 보안에 전화",
    venueCall: "공연장 보안에 연락",
    call911: "응급? 911에 전화",
    lifeThreat: "생명을 위협하는 응급 상황에서는 911에 전화하세요.",
    orSubmit: "또는 보고서 제출",
    submitAReport: "보고서 제출",
    category: "유형",
    incidentType: "어떤 유형의 사건인가요?",
    optional: "(선택)",
    whatHappening: "무슨 일이 일어나고 있나요?",
    whatHappeningHint: "보고 있거나 겪고 있는 상황을 설명하세요…",
    whatHappeningError: "제출 전에 상황을 설명해 주세요.",
    locationZone: "위치 / 구역",
    yourLocation: "위치",
    reportAnonymously: "익명으로 신고",
    yourName: "이름",
    yourPhone: "전화번호",
    optionalPlaceholder: "선택",
    addPhotoVideo: "사진 / 동영상 추가",
    shareLocation: "위치 공유",
    locationShared: "위치 공유됨",
    securityNotice:
      "보고서는 해당 안전 팀에 안전하게 전송됩니다. 익명 신고 시 이름과 전화는 필요하지 않습니다.",
    submitReport: "보고서 제출",
    submitting: "제출 중…",
    campusSuccessTitle: "보고서가 제출되었습니다",
    venueSuccessTitle: "보고서를 수신했습니다",
    campusSuccessDesc: "캠퍼스 보안에 알림이 전달되었으며 곧 대응합니다.",
    venueSuccessDesc: "공연장 운영팀에 알림이 전달되었으며 대응 중입니다.",
    submitAnother: "다른 보고서 제출",
    emergencyFooter: "응급? 911에 전화",
    brandDomain: "app.rapidcortex.us",
    live: "LIVE",
    "cat.campus.0": "의료 문제",
    "cat.campus.1": "수상한 활동",
    "cat.campus.2": "괴롭힘 / 위협",
    "cat.campus.3": "정신 건강",
    "cat.campus.4": "시설 위험",
    "cat.campus.5": "기타",
    "cat.venue.0": "싸움 / 소란",
    "cat.venue.1": "의료 응급",
    "cat.venue.2": "미아",
    "cat.venue.3": "수상한 물체",
    "cat.venue.4": "유출 / 위험",
    "cat.venue.5": "직원 필요",
  },
  AR: {
    selectLanguage: "اختر اللغة",
    secureReporting: "إبلاغ آمن",
    campusHeader: "Rapid Cortex Campus",
    venueHeader: "Rapid Cortex Venue",
    campusAgencyLabel: "إبلاغ سلامة الحرم",
    venueAgencyLabel: "أمن المكان",
    campusTitle: "الإبلاغ عن مخاوف تتعلق بالسلامة",
    venueTitle: "اطلب المساعدة الآن",
    campusDesc:
      "أرسل بلاغًا مباشرة إلى أمن الحرم. يمكنك الاتصال أو إرسال التفاصيل أو مشاركة موقعك أو الإبلاغ بسرية.",
    venueDesc:
      "أبلغ عن حادث أو اطلب الأمن والطاقم الطبي. يصل بلاغك إلى فريق عمليات المكان.",
    campusCall: "اتصل بأمن الحرم",
    venueCall: "اتصل بأمن المكان",
    call911: "حالة طوارئ؟ اتصل بـ 911",
    lifeThreat: "في حالات الطوارئ المهددة للحياة، اتصل بـ 911.",
    orSubmit: "أو أرسل بلاغًا",
    submitAReport: "إرسال بلاغ",
    category: "الفئة",
    incidentType: "ما نوع الحادث؟",
    optional: "(اختياري)",
    whatHappening: "ماذا يحدث؟",
    whatHappeningHint: "صف ما تراه أو ما تمر به…",
    whatHappeningError: "يرجى وصف ما يحدث قبل الإرسال.",
    locationZone: "موقعك / المنطقة",
    yourLocation: "موقعك",
    reportAnonymously: "الإبلاغ دون الكشف عن الهوية",
    yourName: "اسمك",
    yourPhone: "رقم هاتفك",
    optionalPlaceholder: "اختياري",
    addPhotoVideo: "إضافة صورة / فيديو",
    shareLocation: "مشاركة الموقع",
    locationShared: "تمت مشاركة الموقع",
    securityNotice:
      "تُرسل البلاغات بأمان إلى فريق السلامة المناسب. الإبلاغ المجهول متاح — الاسم والهاتف غير مطلوبين.",
    submitReport: "إرسال البلاغ",
    submitting: "جارٍ الإرسال…",
    campusSuccessTitle: "تم إرسال البلاغ",
    venueSuccessTitle: "تم استلام البلاغ",
    campusSuccessDesc: "تم إخطار أمن الحرم وسيستجيب قريبًا.",
    venueSuccessDesc: "تم إخطار فريق العمليات ويستجيب الآن.",
    submitAnother: "إرسال بلاغ آخر",
    emergencyFooter: "حالة طوارئ؟ اتصل بـ 911",
    brandDomain: "app.rapidcortex.us",
    live: "مباشر",
    "cat.campus.0": "قلق طبي",
    "cat.campus.1": "نشاط مشبوه",
    "cat.campus.2": "تحرش / تهديد",
    "cat.campus.3": "صحة نفسية",
    "cat.campus.4": "خطر في المرافق",
    "cat.campus.5": "أخرى",
    "cat.venue.0": "قتال / اضطراب",
    "cat.venue.1": "حالة طبية طارئة",
    "cat.venue.2": "طفل مفقود",
    "cat.venue.3": "غرض مشبوه",
    "cat.venue.4": "انسكاب / خطر",
    "cat.venue.5": "أحتاج موظفين",
  },
};

type ReportLanguageContextValue = {
  code: ReportLangCode;
  setCode: (code: ReportLangCode) => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
};

const ReportLanguageContext = createContext<ReportLanguageContextValue | null>(null);

function isReportLangCode(value: string): value is ReportLangCode {
  return REPORT_LANGUAGES.some((l) => l.code === value);
}

export function ReportLanguageProvider({ children }: { children: ReactNode }) {
  const [code, setCodeState] = useState<ReportLangCode>("EN");

  useEffect(() => {
    const saved = window.localStorage.getItem(REPORT_LANG_STORAGE_KEY);
    if (saved && isReportLangCode(saved)) setCodeState(saved);
  }, []);

  const setCode = useCallback((next: ReportLangCode) => {
    setCodeState(next);
    try {
      window.localStorage.setItem(REPORT_LANG_STORAGE_KEY, next);
    } catch {
      /* ignore */
    }
  }, []);

  const dir = REPORT_LANGUAGES.find((l) => l.code === code)?.dir ?? "ltr";

  const t = useCallback(
    (key: string) => {
      return DICTIONARIES[code][key] ?? DICTIONARIES.EN[key] ?? key;
    },
    [code],
  );

  const value = useMemo(() => ({ code, setCode, dir, t }), [code, setCode, dir, t]);

  return (
    <ReportLanguageContext.Provider value={value}>{children}</ReportLanguageContext.Provider>
  );
}

export function useReportLanguage(): ReportLanguageContextValue {
  const ctx = useContext(ReportLanguageContext);
  if (!ctx) {
    return {
      code: "EN",
      setCode: () => undefined,
      dir: "ltr",
      t: (key: string) => DICTIONARIES.EN[key] ?? key,
    };
  }
  return ctx;
}
