/** Training utterances for campus Lex intents (also declared in stack-lex.yaml). */
export const UTTERANCES_CAMPUS = {
  WellnessCheck: [
    "can someone check on my friend",
    "wellness check",
    "I'm worried about a student",
    "someone is not responding to messages",
    "welfare check",
    "my roommate hasn't come back",
    "please check on someone in the dorm",
    "a student isn't answering their phone",
    "I'm concerned about a classmate",
    "can campus safety do a welfare check",
    "my friend locked themselves in their room",
    "haven't seen my roommate all day and I'm worried",
  ],
  MedicalRequest: [
    "someone is hurt",
    "medical help needed",
    "someone passed out",
    "I need medical assistance",
    "student collapsed in the hallway",
    "someone is having an allergic reaction",
    "person fainted in the library",
    "need EMS on campus",
    "someone cut themselves badly",
    "student is having a seizure",
    "medical help at the rec center",
  ],
  FacilitiesIssue: [
    "something is broken",
    "maintenance issue",
    "the elevator is stuck",
    "there is a leak",
    "facilities problem",
    "the door won't lock",
    "power is out in the building",
    "there's flooding in the restroom",
    "broken window in the dorm",
    "heating isn't working",
    "smoke detector keeps going off but no fire",
    "sidewalk ice is dangerous outside the dorm",
  ],
} as const;
