/**
 * Canonical incident type definitions for Rapid Cortex dispatcher workspace.
 * Each type maps to a CAD nature code, default priority, and inline protocol hints.
 *
 * UI hints only — protocol enforcement and CAD write-back validation are server-side.
 */

export type IncidentPriority = "P1" | "P2" | "P3" | "P4";

export type IncidentDiscipline = "law" | "fire" | "ems" | "other" | "multi";

export interface IncidentTypeDefinition {
  id: string;
  label: string;
  icon: string;
  cadNatureCode: string;
  defaultPriority: IncidentPriority;
  discipline: IncidentDiscipline[];
  protocolHints: string[];
  supervisorAlert: boolean;
}

export const INCIDENT_TYPES: IncidentTypeDefinition[] = [
  {
    id: "assault",
    label: "Assault / Fight",
    icon: "⚡",
    cadNatureCode: "ASSLT",
    defaultPriority: "P2",
    discipline: ["law"],
    protocolHints: [
      "Confirm suspect(s) still on scene",
      "Obtain weapon description",
      "Establish number of victims / injuries",
      "Request EMS if injuries reported",
    ],
    supervisorAlert: true,
  },
  {
    id: "shots_fired",
    label: "Shots Fired",
    icon: "🔴",
    cadNatureCode: "SHOTS",
    defaultPriority: "P1",
    discipline: ["law"],
    protocolHints: [
      "Confirm location — intersection or address",
      "Direction shots were fired",
      "Suspect / vehicle description",
      "Any known injuries — stage EMS if needed",
    ],
    supervisorAlert: true,
  },
  {
    id: "structure_fire",
    label: "Structure Fire",
    icon: "🔥",
    cadNatureCode: "FIRE_STRUCT",
    defaultPriority: "P1",
    discipline: ["fire", "ems"],
    protocolHints: [
      "Is caller inside or outside?",
      "Confirm type of structure",
      "Anyone trapped / not evacuated?",
      "Visible flames vs smoke only",
    ],
    supervisorAlert: true,
  },
  {
    id: "cardiac",
    label: "Cardiac / Chest Pain",
    icon: "❤️",
    cadNatureCode: "CARD",
    defaultPriority: "P1",
    discipline: ["ems"],
    protocolHints: [
      "Patient conscious and breathing?",
      "Age, sex, location in structure",
      "Begin pre-arrival CPR instructions if needed",
      "AED available on scene?",
    ],
    supervisorAlert: false,
  },
  {
    id: "mvc",
    label: "Vehicle Crash",
    icon: "🚗",
    cadNatureCode: "MVC",
    defaultPriority: "P2",
    discipline: ["law", "fire", "ems"],
    protocolHints: [
      "Number of vehicles / injuries",
      "Road / intersection — mile marker if highway",
      "Confirm airbag deployment or entrapment",
      "Hazmat — fuel leak or cargo?",
    ],
    supervisorAlert: false,
  },
  {
    id: "welfare_check",
    label: "Welfare Check",
    icon: "👤",
    cadNatureCode: "WELF",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Last seen / last contact date",
      "Any weapons or mental health history known",
      "Next of kin contact info",
    ],
    supervisorAlert: false,
  },
  {
    id: "burglary",
    label: "Burglary / Break-in",
    icon: "🔓",
    cadNatureCode: "BURG",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "In progress vs just discovered?",
      "Suspect description and last seen direction",
      "Point of entry confirmed?",
      "Is anyone inside?",
    ],
    supervisorAlert: false,
  },
  {
    id: "medical_general",
    label: "Medical Emergency",
    icon: "🚑",
    cadNatureCode: "MED_GEN",
    defaultPriority: "P3",
    discipline: ["ems"],
    protocolHints: [
      "Chief complaint",
      "Patient conscious and breathing?",
      "Address + apartment / floor confirmed",
      "Any access issues (locked gate, elevator)?",
    ],
    supervisorAlert: false,
  },
  {
    id: "domestic",
    label: "Domestic Disturbance",
    icon: "🏠",
    cadNatureCode: "DOM",
    defaultPriority: "P2",
    discipline: ["law"],
    protocolHints: [
      "Physical or verbal only?",
      "Weapons present or threatened?",
      "Children in the residence?",
      "Any prior domestic history at address",
    ],
    supervisorAlert: true,
  },
  {
    id: "overdose",
    label: "Drug Overdose",
    icon: "💊",
    cadNatureCode: "OD",
    defaultPriority: "P2",
    discipline: ["ems", "fire"],
    protocolHints: [
      "Conscious and breathing?",
      "Suspected substance if known",
      "Naloxone available on scene?",
      "Exact address — unit / floor",
    ],
    supervisorAlert: false,
  },
  {
    id: "disturbance",
    label: "Disturbance / Noise",
    icon: "📢",
    cadNatureCode: "DIST",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Type of disturbance",
      "Number of people involved",
      "Any weapons mentioned",
    ],
    supervisorAlert: false,
  },
  {
    id: "other",
    label: "Other / Manual",
    icon: "📋",
    cadNatureCode: "OTHER",
    defaultPriority: "P4",
    discipline: ["law", "fire", "ems", "multi"],
    protocolHints: [
      "Document nature of call clearly",
      "Confirm location and callback number",
    ],
    supervisorAlert: false,
  },
  {
    id: "active-shooter",
    label: "Active Shooter",
    icon: "",
    cadNatureCode: "ACTSHOOT",
    defaultPriority: "P1",
    discipline: ["law"],
    protocolHints: [
      "Exact location and last known direction of travel",
      "Number of shooters and weapon type if known",
      "Injuries / people trapped — stage EMS",
      "Safe staging and ingress for first units",
    ],
    supervisorAlert: true,
  },
  {
    id: "robbery",
    label: "Robbery",
    icon: "",
    cadNatureCode: "ROBB",
    defaultPriority: "P1",
    discipline: ["law"],
    protocolHints: [
      "In progress vs just occurred?",
      "Weapon displayed or implied?",
      "Suspect / vehicle description and last seen",
      "Injuries — request EMS if needed",
    ],
    supervisorAlert: true,
  },
  {
    id: "hit-and-run",
    label: "Hit and Run",
    icon: "",
    cadNatureCode: "HITRUN",
    defaultPriority: "P2",
    discipline: ["law"],
    protocolHints: [
      "Injuries vs property damage only",
      "Suspect vehicle description and direction",
      "License plate if captured",
      "Exact location / lane blockage",
    ],
    supervisorAlert: false,
  },
  {
    id: "suspicious-person",
    label: "Suspicious Person",
    icon: "",
    cadNatureCode: "SUSP",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Description, clothing, and direction of travel",
      "What made the person suspicious",
      "Still on scene?",
    ],
    supervisorAlert: false,
  },
  {
    id: "vehicle-pursuit",
    label: "Vehicle Pursuit",
    icon: "",
    cadNatureCode: "PURSUIT",
    defaultPriority: "P1",
    discipline: ["law"],
    protocolHints: [
      "Last known direction, speed, and roadway",
      "Reason for pursuit / charges if known",
      "Occupants, weapons, stolen vehicle?",
      "Supervisor notification — terminate criteria",
    ],
    supervisorAlert: true,
  },
  {
    id: "missing-person",
    label: "Missing Person",
    icon: "",
    cadNatureCode: "MISSPER",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Age, description, and last seen location / time",
      "At-risk (juvenile, elderly, medical, suicidal)?",
      "Possible destinations and contacts",
    ],
    supervisorAlert: false,
  },
  {
    id: "traffic-stop",
    label: "Traffic Stop",
    icon: "",
    cadNatureCode: "TSTOP",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Exact location and vehicle description",
      "Reason for the stop",
      "Occupant count if known",
    ],
    supervisorAlert: false,
  },
  {
    id: "dui",
    label: "DUI / Impaired",
    icon: "",
    cadNatureCode: "DUI",
    defaultPriority: "P2",
    discipline: ["law"],
    protocolHints: [
      "Vehicle still occupied / moving?",
      "Location and direction of travel",
      "Injuries or crash involved?",
    ],
    supervisorAlert: false,
  },
  {
    id: "warrant",
    label: "Warrant Service",
    icon: "",
    cadNatureCode: "WARRANT",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Confirm warrant type and agency",
      "Address / last known location",
      "Weapons or violence history if known",
    ],
    supervisorAlert: false,
  },
  {
    id: "stalking",
    label: "Stalking / Harassment",
    icon: "",
    cadNatureCode: "STALK",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Is the suspect on scene or nearby?",
      "Protective order in effect?",
      "Immediate threat vs ongoing pattern",
    ],
    supervisorAlert: false,
  },
  {
    id: "theft",
    label: "Theft / Larceny",
    icon: "",
    cadNatureCode: "THEFT",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "In progress vs already occurred?",
      "Property description and value if known",
      "Suspect description and last seen",
    ],
    supervisorAlert: false,
  },
  {
    id: "alarm-residential",
    label: "Residential Alarm",
    icon: "",
    cadNatureCode: "ALMRES",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Zone / alarm type if provided",
      "Premises occupied? Keyholder notified?",
      "Signs of forced entry reported?",
    ],
    supervisorAlert: false,
  },
  {
    id: "alarm-commercial",
    label: "Commercial Alarm",
    icon: "",
    cadNatureCode: "ALMCOM",
    defaultPriority: "P3",
    discipline: ["law"],
    protocolHints: [
      "Business name and alarm zone",
      "Open / closed hours — anyone expected on site?",
      "Keyholder contact",
    ],
    supervisorAlert: false,
  },
  {
    id: "gas-leak",
    label: "Gas Leak",
    icon: "",
    cadNatureCode: "GAS",
    defaultPriority: "P2",
    discipline: ["fire"],
    protocolHints: [
      "Inside structure vs outdoor odor?",
      "Anyone symptomatic — evacuate / stage?",
      "Pilot lights, ignition sources, utility notified?",
    ],
    supervisorAlert: false,
  },
  {
    id: "hazmat",
    label: "Hazmat",
    icon: "",
    cadNatureCode: "HAZMAT",
    defaultPriority: "P2",
    discipline: ["fire"],
    protocolHints: [
      "Container markings / placard if visible",
      "Product, quantity, and leak vs spill",
      "People exposed — upwind staging",
    ],
    supervisorAlert: true,
  },
  {
    id: "water-rescue",
    label: "Water Rescue",
    icon: "",
    cadNatureCode: "WATRES",
    defaultPriority: "P1",
    discipline: ["fire", "ems"],
    protocolHints: [
      "Exact waterway / access point",
      "Number of victims in water vs shore",
      "Swift water vs static — PPE / boat needed",
    ],
    supervisorAlert: true,
  },
  {
    id: "building-collapse",
    label: "Building Collapse",
    icon: "",
    cadNatureCode: "COLLAPSE",
    defaultPriority: "P1",
    discipline: ["fire", "ems"],
    protocolHints: [
      "Partial vs complete collapse",
      "Occupants trapped or unaccounted for?",
      "Utilities, secondary collapse risk",
    ],
    supervisorAlert: true,
  },
  {
    id: "brush-fire",
    label: "Brush / Wildland Fire",
    icon: "",
    cadNatureCode: "BRUSH",
    defaultPriority: "P2",
    discipline: ["fire"],
    protocolHints: [
      "Acres / size and wind direction",
      "Threat to structures?",
      "Access / nearest hydrant or water source",
    ],
    supervisorAlert: false,
  },
  {
    id: "electrical",
    label: "Electrical Hazard",
    icon: "",
    cadNatureCode: "ELEC",
    defaultPriority: "P2",
    discipline: ["fire"],
    protocolHints: [
      "Downed lines vs interior arcing",
      "Anyone in contact — stay back",
      "Utility notified? Road / area blocked?",
    ],
    supervisorAlert: false,
  },
  {
    id: "carbon-monoxide",
    label: "Carbon Monoxide",
    icon: "",
    cadNatureCode: "CO",
    defaultPriority: "P2",
    discipline: ["fire", "ems"],
    protocolHints: [
      "Detector sounding vs symptoms only",
      "Anyone ill — evacuate to fresh air",
      "Source if known (furnace, generator, vehicle)",
    ],
    supervisorAlert: false,
  },
  {
    id: "stroke",
    label: "Stroke / CVA",
    icon: "",
    cadNatureCode: "STROKE",
    defaultPriority: "P1",
    discipline: ["ems"],
    protocolHints: [
      "Last known well time — FAST symptoms",
      "Conscious and breathing?",
      "Exact address + access (gate, floor)",
    ],
    supervisorAlert: false,
  },
  {
    id: "trauma",
    label: "Trauma",
    icon: "",
    cadNatureCode: "TRAUMA",
    defaultPriority: "P2",
    discipline: ["ems"],
    protocolHints: [
      "Mechanism of injury",
      "Bleeding controlled? Consciousness?",
      "Number of patients",
    ],
    supervisorAlert: false,
  },
  {
    id: "seizure",
    label: "Seizure",
    icon: "",
    cadNatureCode: "SEIZ",
    defaultPriority: "P3",
    discipline: ["ems"],
    protocolHints: [
      "Still seizing vs post-ictal",
      "Duration and known history",
      "Airway / injuries from fall",
    ],
    supervisorAlert: false,
  },
  {
    id: "diabetic",
    label: "Diabetic Emergency",
    icon: "",
    cadNatureCode: "DIAB",
    defaultPriority: "P3",
    discipline: ["ems"],
    protocolHints: [
      "Conscious and able to swallow?",
      "High vs low suspected",
      "Insulin / last meal if known",
    ],
    supervisorAlert: false,
  },
  {
    id: "allergic",
    label: "Allergic Reaction",
    icon: "",
    cadNatureCode: "ALLERG",
    defaultPriority: "P2",
    discipline: ["ems"],
    protocolHints: [
      "Breathing difficulty or swelling?",
      "Epinephrine available / given?",
      "Known allergen if identified",
    ],
    supervisorAlert: false,
  },
  {
    id: "obstetric",
    label: "Obstetric Emergency",
    icon: "",
    cadNatureCode: "OB",
    defaultPriority: "P2",
    discipline: ["ems"],
    protocolHints: [
      "Gestation / contractions / crowning?",
      "Bleeding or other complications",
      "Number of patients (mother + infant)",
    ],
    supervisorAlert: false,
  },
  {
    id: "mental-health",
    label: "Mental Health",
    icon: "",
    cadNatureCode: "MH",
    defaultPriority: "P3",
    discipline: ["ems", "law"],
    protocolHints: [
      "Immediate danger to self or others?",
      "Weapons on scene?",
      "Willing to speak with responders?",
    ],
    supervisorAlert: false,
  },
  {
    id: "unconscious",
    label: "Unconscious",
    icon: "",
    cadNatureCode: "UNCON",
    defaultPriority: "P1",
    discipline: ["ems"],
    protocolHints: [
      "Breathing and pulse present?",
      "Begin CPR instructions if needed",
      "Exact location in structure",
    ],
    supervisorAlert: false,
  },
  {
    id: "respiratory",
    label: "Respiratory Distress",
    icon: "",
    cadNatureCode: "RESP",
    defaultPriority: "P2",
    discipline: ["ems"],
    protocolHints: [
      "Able to speak in full sentences?",
      "Asthma / COPD / allergy history",
      "Cyanosis or unresponsive?",
    ],
    supervisorAlert: false,
  },
  {
    id: "fall-injury",
    label: "Fall / Injury",
    icon: "",
    cadNatureCode: "FALL",
    defaultPriority: "P3",
    discipline: ["ems"],
    protocolHints: [
      "From standing vs height",
      "Conscious, bleeding, suspected fracture?",
      "Access / lift-assist needed?",
    ],
    supervisorAlert: false,
  },
  {
    id: "mvc-injury",
    label: "MVC with Injury",
    icon: "",
    cadNatureCode: "MVCINJ",
    defaultPriority: "P2",
    discipline: ["ems", "fire", "law"],
    protocolHints: [
      "Number of patients and vehicles",
      "Entrapment / ejection / rollover?",
      "Highway vs surface street — staging",
    ],
    supervisorAlert: false,
  },
  {
    id: "alarm-unknown",
    label: "Unknown Alarm",
    icon: "",
    cadNatureCode: "ALMUNK",
    defaultPriority: "P3",
    discipline: ["other"],
    protocolHints: [
      "Residential, commercial, or vehicle?",
      "Any additional 911 information",
      "Keyholder if available",
    ],
    supervisorAlert: false,
  },
  {
    id: "animal",
    label: "Animal Complaint",
    icon: "",
    cadNatureCode: "ANIMAL",
    defaultPriority: "P4",
    discipline: ["other"],
    protocolHints: [
      "Aggressive vs contained vs injured",
      "Species and last seen location",
      "Anyone bitten — EMS needed?",
    ],
    supervisorAlert: false,
  },
  {
    id: "lockout",
    label: "Lockout",
    icon: "",
    cadNatureCode: "LOCKOUT",
    defaultPriority: "P4",
    discipline: ["other"],
    protocolHints: [
      "Vehicle vs residence",
      "Child / pet / medical emergency inside?",
      "If emergency, upgrade priority immediately",
    ],
    supervisorAlert: false,
  },
  {
    id: "flooding",
    label: "Flooding",
    icon: "",
    cadNatureCode: "FLOOD",
    defaultPriority: "P3",
    discipline: ["other", "fire"],
    protocolHints: [
      "Structure vs roadway vs swift water",
      "Anyone trapped or needing rescue?",
      "Utilities at risk",
    ],
    supervisorAlert: false,
  },
  {
    id: "public-assist",
    label: "Public Assist",
    icon: "",
    cadNatureCode: "PUBAST",
    defaultPriority: "P4",
    discipline: ["other"],
    protocolHints: [
      "Nature of the request",
      "Medical component — convert to EMS if so",
      "Exact location and callback",
    ],
    supervisorAlert: false,
  },
  {
    id: "civil-standby",
    label: "Civil Standby",
    icon: "",
    cadNatureCode: "CIVIL",
    defaultPriority: "P4",
    discipline: ["other", "law"],
    protocolHints: [
      "Property retrieval vs court order vs other",
      "Weapons / prior violence at address",
      "All parties expected on scene?",
    ],
    supervisorAlert: false,
  },
  {
    id: "transport",
    label: "Transport",
    icon: "",
    cadNatureCode: "TRANSP",
    defaultPriority: "P4",
    discipline: ["other"],
    protocolHints: [
      "Origin, destination, and patient / cargo",
      "Time-critical vs scheduled",
      "Any medical monitoring required",
    ],
    supervisorAlert: false,
  },
  {
    id: "found-person",
    label: "Found Person",
    icon: "",
    cadNatureCode: "FOUND",
    defaultPriority: "P4",
    discipline: ["other", "law"],
    protocolHints: [
      "Description, age, and condition",
      "Matches a missing-person call?",
      "Safe location to wait for units",
    ],
    supervisorAlert: false,
  },
  {
    id: "homeless",
    label: "Homeless / Unsheltered",
    icon: "",
    cadNatureCode: "HOMELESS",
    defaultPriority: "P4",
    discipline: ["other"],
    protocolHints: [
      "Welfare vs trespass vs camp complaint",
      "Medical or weather emergency?",
      "Exact location",
    ],
    supervisorAlert: false,
  },
];

export function getIncidentType(id: string): IncidentTypeDefinition | undefined {
  return INCIDENT_TYPES.find((t) => t.id === id);
}

export const PRIORITY_META: Record<
  IncidentPriority,
  { label: string; color: string; bg: string; border: string; description: string }
> = {
  P1: {
    label: "P1",
    color: "#fca5a5",
    bg: "#450a0a",
    border: "#991b1b",
    description: "Immediate life safety — all resources",
  },
  P2: {
    label: "P2",
    color: "#fcd34d",
    bg: "#451a03",
    border: "#92400e",
    description: "Urgent — expedited response",
  },
  P3: {
    label: "P3",
    color: "#93c5fd",
    bg: "#0c1a2e",
    border: "#1e40af",
    description: "Standard priority",
  },
  P4: {
    label: "P4",
    color: "#a1a1aa",
    bg: "#18181b",
    border: "#3f3f46",
    description: "Non-urgent / informational",
  },
};

/** Canonical PSAP supervisor / admin roles that see override controls in the slide-over. */
export const SUPERVISOR_CREATE_INCIDENT_ROLES = new Set([
  "supervisor",
  "agencyadmin",
  "agencyit",
  "rcsuperadmin",
  "rcadmin",
]);

export function isSupervisorCreateRole(role?: string): boolean {
  return !!role && SUPERVISOR_CREATE_INCIDENT_ROLES.has(role.toLowerCase());
}
