"use client";

import { FileText } from "lucide-react";
import { useSession } from "@/components/auth/session-context";
import { isSupervisorOrStaffRole, SupervisorAccessRestricted } from "../_components/supervisor-access";

const reportTemplates = [
  {
    title: "Operational Summary",
    description: "Shift volume, escalations, and operational highlights.",
  },
  {
    title: "QA Trend Report",
    description: "Quality scores, review completion, and coaching trendline.",
  },
  {
    title: "SLA & Backlog Report",
    description: "SLA adherence and unresolved queue trends by window.",
  },
] as const;

export default function SupervisorReportsPage() {
  const { user } = useSession();

  if (!isSupervisorOrStaffRole(user?.role)) {
    return <SupervisorAccessRestricted />;
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto p-4 pb-10">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-xl font-semibold text-white">Reports</h1>
        <button
          type="button"
          className="rounded-md bg-slate-800 px-3 py-2 text-sm font-medium text-sky-300 ring-1 ring-slate-700 hover:bg-slate-700"
          onClick={() => console.log("TODO: create report")}
        >
          New Report
        </button>
      </div>

      <section className="grid gap-4 md:grid-cols-3">
        {reportTemplates.map((template) => (
          <article key={template.title} className="rounded-lg border border-slate-800 bg-slate-950/40 p-4">
            <h2 className="text-sm font-semibold text-slate-100">{template.title}</h2>
            <p className="mt-2 text-sm text-slate-400">{template.description}</p>
            <button
              type="button"
              className="mt-4 rounded-md bg-slate-800 px-3 py-1.5 text-xs font-medium text-sky-300 ring-1 ring-slate-700 hover:bg-slate-700"
              onClick={() => console.log("TODO: generate report", template.title)}
            >
              Generate
            </button>
          </article>
        ))}
      </section>

      <section className="overflow-hidden rounded-lg border border-slate-800 bg-slate-950/40">
        <div className="grid grid-cols-[1.2fr_1fr_1fr_1fr_auto] gap-3 border-b border-slate-800 px-4 py-2 text-xs uppercase tracking-wide text-slate-500">
          <span>Report Name</span>
          <span>Type</span>
          <span>Generated</span>
          <span>Generated By</span>
          <span>Actions</span>
        </div>
        <div className="flex flex-col items-center justify-center py-14 text-center">
          <FileText className="mb-4 h-10 w-10 text-slate-600" />
          <h2 className="text-lg font-semibold text-slate-300">No reports generated yet.</h2>
        </div>
      </section>
    </div>
  );
}
