import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import {
  DeleteCommand,
  DynamoDBDocumentClient,
  GetCommand,
  PutCommand,
  QueryCommand,
  UpdateCommand,
} from "@aws-sdk/lib-dynamodb";
import {
  AUDIT_EVENT_TYPES,
} from "rapid-cortex-security";
import type {
  CleryAsrCell,
  CleryCategory,
  CleryEntry,
  CleryEntryCreateInput,
  CleryEntrySource,
  CleryEntryUpdateInput,
  CleryGeography,
  CleryImportRow,
  CleryReport,
} from "rapid-cortex-shared";
import {
  CLERY_CATEGORIES,
  CLERY_GEOGRAPHIES,
  CLERY_GEOGRAPHY_LABELS,
  cleryCategorySchema,
} from "rapid-cortex-shared";
import { env } from "../lib/env.js";
import { makeId } from "../lib/ids.js";
import { AuditRepository } from "../repositories/auditRepository.js";
import type { CampusIncident, CampusIncidentType } from "./campus-types.js";
import { CAMPUS_KEYS } from "./campus-types.js";

export {
  CLERY_CATEGORIES,
  CLERY_GEOGRAPHIES,
  CLERY_GEOGRAPHY_LABELS,
  type CleryCategory,
};

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({}));
const auditRepo = new AuditRepository();

const DISCLAIMER =
  "Generated by Rapid Cortex Campus for institutional review. Designated Campus Security Authorities must verify classifications, geography, and ASR inclusion before publication. Rapid Cortex does not make Clery Act determinations or certify compliance.";

function campusIncidentsTable(): string {
  const t = process.env.CAMPUS_INCIDENTS_TABLE?.trim();
  if (!t) throw new Error("CAMPUS_INCIDENTS_TABLE not set");
  return t;
}

const TYPE_TO_CLERY: Partial<Record<CampusIncidentType, CleryCategory>> = {
  property_crime: "Burglary",
  active_threat: "Aggravated Assault",
};

const KEYWORD_CLERY: Array<{ keywords: string[]; category: CleryCategory }> = [
  { keywords: ["arson", "fire", "set fire"], category: "Arson" },
  { keywords: ["robbery", "robbed", "stole from"], category: "Robbery" },
  { keywords: ["assault", "attacked", "hit", "punched"], category: "Aggravated Assault" },
  { keywords: ["car", "vehicle", "auto", "truck", "van"], category: "Motor Vehicle Theft" },
  { keywords: ["weapon", "gun", "knife", "firearm", "explosive"], category: "Arrests - Weapons Violations" },
  { keywords: ["drug", "narcotics", "marijuana", "cocaine", "pills"], category: "Arrests - Drug Abuse Violations" },
  { keywords: ["alcohol", "drunk", "intoxicated", "liquor"], category: "Arrests - Liquor Law Violations" },
  { keywords: ["stalk", "following me", "won't leave me alone"], category: "VAWA - Stalking" },
  { keywords: ["domestic", "partner", "spouse", "boyfriend", "girlfriend"], category: "VAWA - Domestic Violence" },
  { keywords: ["hazing"], category: "Hazing" },
];

/**
 * Keyword-based suggestion only — NEVER automatic classification.
 * Final determination must be made by designated Campus Security Authority.
 */
export function suggestCleryCategory(
  type: CampusIncidentType,
  description: string,
): CleryCategory | null {
  const lower = description.toLowerCase();
  const typeMatch = TYPE_TO_CLERY[type];
  if (typeMatch) return typeMatch;

  const matches = KEYWORD_CLERY.filter(({ keywords }) =>
    keywords.some((k) => lower.includes(k)),
  );
  if (matches.length === 1) return matches[0].category;
  return null;
}

/** Clery academic year typically Aug 1 (start year) through Jul 31 (end year). */
export function academicYearBounds(academicYear: string): { start: string; end: string } {
  const [startYear] = academicYear.split("-").map(Number);
  return {
    start: `${startYear}-08-01T00:00:00.000Z`,
    end: `${startYear + 1}-07-31T23:59:59.999Z`,
  };
}

function assertAgencyMatch(itemAgencyId: string | undefined, agencyId: string): void {
  if (!itemAgencyId || itemAgencyId !== agencyId) {
    throw new Error("TENANT_MISMATCH");
  }
}

function toStoredEntry(item: Record<string, unknown>): CleryEntry {
  return {
    entryId: String(item.entryId),
    agencyId: String(item.agencyId),
    campusCode: String(item.campusCode),
    academicYear: String(item.academicYear),
    category: item.category as CleryCategory,
    geography: item.geography as CleryGeography,
    occurredAt: String(item.occurredAt),
    location: String(item.location ?? ""),
    building: String(item.building ?? ""),
    notes: String(item.notes ?? ""),
    hateCrimeBias: (item.hateCrimeBias as string | null) ?? null,
    unfounded: Boolean(item.unfounded),
    includedInAsr: item.includedInAsr !== false,
    source: item.source as CleryEntrySource,
    externalSourceSystem: (item.externalSourceSystem as string | null) ?? null,
    externalRecordId: (item.externalRecordId as string | null) ?? null,
    platformIncidentId: (item.platformIncidentId as string | null) ?? null,
    reviewedBy: (item.reviewedBy as string | null) ?? null,
    reviewedAt: (item.reviewedAt as string | null) ?? null,
    createdBy: String(item.createdBy ?? ""),
    createdAt: String(item.createdAt),
    updatedAt: String(item.updatedAt),
  };
}

export async function listCleryEntries(opts: {
  agencyId: string;
  campusCode: string;
  academicYear: string;
}): Promise<CleryEntry[]> {
  const result = await ddb.send(
    new QueryCommand({
      TableName: campusIncidentsTable(),
      KeyConditionExpression: "pk = :pk AND begins_with(sk, :sk)",
      ExpressionAttributeValues: {
        ":pk": CAMPUS_KEYS.incidentPk(opts.campusCode),
        ":sk": CAMPUS_KEYS.cleryEntrySkPrefix(opts.academicYear),
        ":agencyId": opts.agencyId,
      },
      FilterExpression: "agencyId = :agencyId",
    }),
  );

  return (result.Items ?? [])
    .map((i) => toStoredEntry(i as Record<string, unknown>))
    .sort((a, b) => a.occurredAt.localeCompare(b.occurredAt));
}

export async function getCleryEntry(
  campusCode: string,
  academicYear: string,
  entryId: string,
  agencyId: string,
): Promise<CleryEntry | null> {
  const result = await ddb.send(
    new GetCommand({
      TableName: campusIncidentsTable(),
      Key: {
        pk: CAMPUS_KEYS.incidentPk(campusCode),
        sk: CAMPUS_KEYS.cleryEntrySk(academicYear, entryId),
      },
    }),
  );
  if (!result.Item) return null;
  assertAgencyMatch(result.Item.agencyId as string | undefined, agencyId);
  return toStoredEntry(result.Item as Record<string, unknown>);
}

async function putCleryEntry(
  entry: CleryEntry,
  actorId: string,
  auditType: string,
  extraDetails?: Record<string, unknown>,
): Promise<CleryEntry> {
  const item = {
    pk: CAMPUS_KEYS.incidentPk(entry.campusCode),
    sk: CAMPUS_KEYS.cleryEntrySk(entry.academicYear, entry.entryId),
    entityType: "CLERY_ENTRY",
    ...entry,
  };

  await ddb.send(
    new PutCommand({
      TableName: campusIncidentsTable(),
      Item: item,
      ConditionExpression: "attribute_not_exists(sk)",
    }),
  );

  await auditRepo.create({
    eventId: makeId("audit"),
    agencyId: entry.agencyId,
    incidentId: entry.platformIncidentId ?? entry.entryId,
    actorId,
    type: auditType,
    details: {
      campusCode: entry.campusCode,
      academicYear: entry.academicYear,
      entryId: entry.entryId,
      category: entry.category,
      source: entry.source,
      ...extraDetails,
    },
    createdAt: entry.createdAt,
    resourceType: "clery_entry",
    resourceId: entry.entryId,
  });

  return entry;
}

export async function createManualCleryEntry(
  input: CleryEntryCreateInput,
  agencyId: string,
  actorId: string,
): Promise<CleryEntry> {
  if (!env.enableCampusClery) throw new Error("FEATURE_DISABLED");
  const now = new Date().toISOString();
  const entryId = makeId("clery");
  const entry: CleryEntry = {
    entryId,
    agencyId,
    campusCode: input.campusCode.toUpperCase(),
    academicYear: input.academicYear,
    category: input.category,
    geography: input.geography,
    occurredAt: new Date(input.occurredAt).toISOString(),
    location: input.location ?? "",
    building: input.building ?? "",
    notes: input.notes ?? "",
    hateCrimeBias: input.hateCrimeBias ?? null,
    unfounded: input.unfounded ?? false,
    includedInAsr: input.includedInAsr ?? true,
    source: input.platformIncidentId
      ? "platform_incident"
      : input.externalSourceSystem
        ? "import"
        : "manual",
    externalSourceSystem: input.externalSourceSystem ?? null,
    externalRecordId: input.externalRecordId ?? null,
    platformIncidentId: input.platformIncidentId ?? null,
    reviewedBy: null,
    reviewedAt: null,
    createdBy: actorId,
    createdAt: now,
    updatedAt: now,
  };

  return putCleryEntry(entry, actorId, AUDIT_EVENT_TYPES.CAMPUS_CLERY_ENTRY_CREATED);
}

export async function updateCleryEntry(
  campusCode: string,
  academicYear: string,
  entryId: string,
  agencyId: string,
  actorId: string,
  update: CleryEntryUpdateInput,
): Promise<CleryEntry> {
  if (!env.enableCampusClery) throw new Error("FEATURE_DISABLED");
  const existing = await getCleryEntry(campusCode, academicYear, entryId, agencyId);
  if (!existing) throw new Error("NOT_FOUND");

  const now = new Date().toISOString();
  const names: string[] = ["#updatedAt"];
  const values: Record<string, unknown> = { ":updatedAt": now };
  const sets: string[] = ["#updatedAt = :updatedAt"];

  const assign = (field: string, value: unknown, attr = field) => {
    names.push(`#${attr}`);
    values[`:${attr}`] = value;
    sets.push(`#${attr} = :${attr}`);
  };

  if (update.category !== undefined) assign("category", update.category);
  if (update.geography !== undefined) assign("geography", update.geography);
  if (update.occurredAt !== undefined) {
    assign("occurredAt", new Date(update.occurredAt).toISOString());
  }
  if (update.location !== undefined) assign("location", update.location);
  if (update.building !== undefined) assign("building", update.building);
  if (update.notes !== undefined) assign("notes", update.notes);
  if (update.hateCrimeBias !== undefined) assign("hateCrimeBias", update.hateCrimeBias);
  if (update.unfounded !== undefined) assign("unfounded", update.unfounded);
  if (update.includedInAsr !== undefined) assign("includedInAsr", update.includedInAsr);
  if (update.reviewed === true) {
    assign("reviewedBy", actorId);
    assign("reviewedAt", now);
  }

  const expressionNames = Object.fromEntries(
    names.map((n) => [n, n.replace("#", "")]),
  );

  await ddb.send(
    new UpdateCommand({
      TableName: campusIncidentsTable(),
      Key: {
        pk: CAMPUS_KEYS.incidentPk(campusCode),
        sk: CAMPUS_KEYS.cleryEntrySk(academicYear, entryId),
      },
      UpdateExpression: `SET ${sets.join(", ")}`,
      ExpressionAttributeNames: expressionNames,
      ExpressionAttributeValues: {
        ...values,
        ":agencyId": agencyId,
      },
      ConditionExpression: "agencyId = :agencyId",
    }),
  );

  const updated = await getCleryEntry(campusCode, academicYear, entryId, agencyId);
  if (!updated) throw new Error("NOT_FOUND");

  await auditRepo.create({
    eventId: makeId("audit"),
    agencyId,
    incidentId: updated.platformIncidentId ?? entryId,
    actorId,
    type: AUDIT_EVENT_TYPES.CAMPUS_CLERY_ENTRY_UPDATED,
    details: { campusCode, academicYear, entryId, fields: Object.keys(update) },
    createdAt: now,
    resourceType: "clery_entry",
    resourceId: entryId,
  });

  return updated;
}

export async function deleteCleryEntry(
  campusCode: string,
  academicYear: string,
  entryId: string,
  agencyId: string,
  actorId: string,
): Promise<void> {
  if (!env.enableCampusClery) throw new Error("FEATURE_DISABLED");
  const existing = await getCleryEntry(campusCode, academicYear, entryId, agencyId);
  if (!existing) throw new Error("NOT_FOUND");

  await ddb.send(
    new DeleteCommand({
      TableName: campusIncidentsTable(),
      Key: {
        pk: CAMPUS_KEYS.incidentPk(campusCode),
        sk: CAMPUS_KEYS.cleryEntrySk(academicYear, entryId),
      },
      ConditionExpression: "agencyId = :agencyId",
      ExpressionAttributeValues: { ":agencyId": agencyId },
    }),
  );

  await auditRepo.create({
    eventId: makeId("audit"),
    agencyId,
    incidentId: existing.platformIncidentId ?? entryId,
    actorId,
    type: AUDIT_EVENT_TYPES.CAMPUS_CLERY_ENTRY_DELETED,
    details: { campusCode, academicYear, entryId, category: existing.category },
    createdAt: new Date().toISOString(),
    resourceType: "clery_entry",
    resourceId: entryId,
  });
}

function buildMatrix(entries: CleryEntry[]): CleryAsrCell[] {
  const map = new Map<string, CleryAsrCell>();
  for (const e of entries) {
    if (!e.includedInAsr) continue;
    const key = `${e.category}||${e.geography}`;
    const cell = map.get(key) ?? {
      category: e.category,
      geography: e.geography,
      count: 0,
      unfounded: 0,
    };
    if (e.unfounded) cell.unfounded += 1;
    else cell.count += 1;
    map.set(key, cell);
  }
  return [...map.values()].sort((a, b) =>
    a.category === b.category
      ? a.geography.localeCompare(b.geography)
      : a.category.localeCompare(b.category),
  );
}

function emptyBySource(): Record<CleryEntrySource, number> {
  return {
    platform_incident: 0,
    manual: 0,
    import: 0,
    external_sync: 0,
  };
}

export async function buildCleryReport(opts: {
  agencyId: string;
  campusCode: string;
  academicYear: string;
  actorId: string;
}): Promise<CleryReport> {
  if (!env.enableCampusClery) throw new Error("FEATURE_DISABLED");
  const entries = await listCleryEntries(opts);
  const period = academicYearBounds(opts.academicYear);
  const bySource = emptyBySource();
  for (const e of entries) bySource[e.source] = (bySource[e.source] ?? 0) + 1;

  const report: CleryReport = {
    campusCode: opts.campusCode.toUpperCase(),
    academicYear: opts.academicYear,
    generatedAt: new Date().toISOString(),
    disclaimer: DISCLAIMER,
    period,
    totals: {
      entries: entries.length,
      includedInAsr: entries.filter((e) => e.includedInAsr && !e.unfounded).length,
      unfounded: entries.filter((e) => e.unfounded).length,
      bySource,
    },
    matrix: buildMatrix(entries),
    entries,
  };

  await auditRepo.create({
    eventId: makeId("audit"),
    agencyId: opts.agencyId,
    incidentId: opts.academicYear,
    actorId: opts.actorId,
    type: AUDIT_EVENT_TYPES.CAMPUS_CLERY_REPORT_GENERATED,
    details: {
      campusCode: opts.campusCode,
      academicYear: opts.academicYear,
      entryCount: entries.length,
    },
    createdAt: report.generatedAt,
    resourceType: "clery_report",
    resourceId: opts.academicYear,
  });

  return report;
}

export function exportCleryReportCsv(report: CleryReport): string {
  const header = [
    `# Academic Year: ${report.academicYear}`,
    `# Generated: ${report.generatedAt}`,
    `# ${report.disclaimer}`,
    "",
    "Entry ID,Occurred At,Category,Geography,Location,Building,Unfounded,Included In ASR,Source,External System,External ID,Platform Incident ID,Notes",
  ];

  const rows = report.entries.map((e) =>
    [
      e.entryId,
      e.occurredAt,
      `"${e.category.replace(/"/g, "'")}"`,
      `"${CLERY_GEOGRAPHY_LABELS[e.geography]}"`,
      `"${e.location.replace(/"/g, "'")}"`,
      `"${e.building.replace(/"/g, "'")}"`,
      e.unfounded ? "yes" : "no",
      e.includedInAsr ? "yes" : "no",
      e.source,
      `"${(e.externalSourceSystem ?? "").replace(/"/g, "'")}"`,
      `"${(e.externalRecordId ?? "").replace(/"/g, "'")}"`,
      `"${(e.platformIncidentId ?? "").replace(/"/g, "'")}"`,
      `"${e.notes.slice(0, 200).replace(/"/g, "'")}"`,
    ].join(","),
  );

  const matrixHeader = ["", "ASR Matrix (category × geography)", "Category,Geography,Count,Unfounded"];
  const matrixRows = report.matrix.map((c) =>
    [
      `"${c.category.replace(/"/g, "'")}"`,
      `"${CLERY_GEOGRAPHY_LABELS[c.geography]}"`,
      c.count,
      c.unfounded,
    ].join(","),
  );

  return [...header, ...rows, ...matrixHeader, ...matrixRows].join("\n");
}

/** @deprecated Prefer buildCleryReport + exportCleryReportCsv — kept for older call sites. */
export function exportCleryReport(incidents: CampusIncident[], academicYear: string): string {
  const classified = incidents.filter((i) => i.cleryCategory);
  const rows = classified.map((i) => {
    const d = new Date(i.createdAt);
    const date = d.toLocaleDateString("en-US");
    const time = d.toLocaleTimeString("en-US", { hour12: false });
    const location = [i.buildingLabel, i.roomCode].filter(Boolean).join(", ");
    return [
      i.id,
      date,
      time,
      `"${i.cleryCategory ?? ""}"`,
      `"${location}"`,
      `"${i.buildingLabel}"`,
      "On Campus",
      `"${i.description.slice(0, 100).replace(/"/g, "'")}"`,
    ].join(",");
  });

  return [
    `# Academic Year: ${academicYear}`,
    "Generated by Rapid Cortex Campus.",
    "Review required by designated Campus Security Authority before publication.",
    "Rapid Cortex does not make Clery Act determinations.",
    "",
    "Incident ID,Date,Time,Category,Location,Building,On Campus,Notes",
    ...rows,
  ].join("\n");
}

export async function importCleryRows(opts: {
  agencyId: string;
  campusCode: string;
  academicYear: string;
  sourceSystem: string;
  rows: CleryImportRow[];
  skipDuplicates: boolean;
  actorId: string;
  source: CleryEntrySource;
  auditType: string;
}): Promise<{ created: number; skipped: number; entries: CleryEntry[] }> {
  if (!env.enableCampusClery) throw new Error("FEATURE_DISABLED");
  const existing = await listCleryEntries({
    agencyId: opts.agencyId,
    campusCode: opts.campusCode,
    academicYear: opts.academicYear,
  });
  const existingExternal = new Set(
    existing
      .filter((e) => e.externalSourceSystem === opts.sourceSystem && e.externalRecordId)
      .map((e) => e.externalRecordId as string),
  );

  let created = 0;
  let skipped = 0;
  const entries: CleryEntry[] = [];

  for (const row of opts.rows) {
    if (
      opts.skipDuplicates &&
      row.externalRecordId &&
      existingExternal.has(row.externalRecordId)
    ) {
      skipped += 1;
      continue;
    }

    const now = new Date().toISOString();
    const entryId = makeId("clery");
    const entry: CleryEntry = {
      entryId,
      agencyId: opts.agencyId,
      campusCode: opts.campusCode.toUpperCase(),
      academicYear: opts.academicYear,
      category: row.category,
      geography: row.geography ?? "on_campus",
      occurredAt: new Date(row.occurredAt).toISOString(),
      location: row.location ?? "",
      building: row.building ?? "",
      notes: row.notes ?? "",
      hateCrimeBias: row.hateCrimeBias ?? null,
      unfounded: row.unfounded ?? false,
      includedInAsr: row.includedInAsr ?? true,
      source: opts.source,
      externalSourceSystem: opts.sourceSystem,
      externalRecordId: row.externalRecordId ?? null,
      platformIncidentId: null,
      reviewedBy: null,
      reviewedAt: null,
      createdBy: opts.actorId,
      createdAt: now,
      updatedAt: now,
    };

    await putCleryEntry(entry, opts.actorId, opts.auditType, {
      sourceSystem: opts.sourceSystem,
    });
    if (row.externalRecordId) existingExternal.add(row.externalRecordId);
    entries.push(entry);
    created += 1;
  }

  return { created, skipped, entries };
}

/** Pull sample/connector rows from another campus system (mock or future live adapters). */
export async function fetchExternalCleryRows(
  sourceSystem: string,
  academicYear: string,
): Promise<CleryImportRow[]> {
  const normalized = sourceSystem.trim().toLowerCase();
  if (normalized === "mock") {
    if (!env.campusCleryExternalMock) {
      throw new Error("EXTERNAL_MOCK_DISABLED");
    }
    const { start } = academicYearBounds(academicYear);
    return [
      {
        occurredAt: start,
        category: "Burglary",
        geography: "on_campus",
        location: "Mock Hall lobby",
        building: "Mock Hall",
        notes: "Sample row from mock external connector — replace with live import.",
        hateCrimeBias: null,
        unfounded: false,
        includedInAsr: true,
        externalRecordId: `mock-${academicYear}-1`,
      },
      {
        occurredAt: start,
        category: "VAWA - Stalking",
        geography: "on_campus_residential",
        location: "Residence Hall A",
        building: "Residence Hall A",
        notes: "Sample VAWA row from mock connector.",
        hateCrimeBias: null,
        unfounded: false,
        includedInAsr: true,
        externalRecordId: `mock-${academicYear}-2`,
      },
    ];
  }

  // Live connectors (Maxient, Report Exec, etc.) require Secrets Manager ARNs — not configured yet.
  throw new Error(`EXTERNAL_CONNECTOR_UNAVAILABLE:${normalized}`);
}

async function listAllPlatformIncidents(campusCode: string): Promise<CampusIncident[]> {
  const items: CampusIncident[] = [];
  let exclusiveStartKey: Record<string, unknown> | undefined;

  do {
    const result = await ddb.send(
      new QueryCommand({
        TableName: campusIncidentsTable(),
        KeyConditionExpression: "pk = :pk AND begins_with(sk, :sk)",
        ExpressionAttributeValues: {
          ":pk": CAMPUS_KEYS.incidentPk(campusCode),
          ":sk": "INCIDENT#",
        },
        ExclusiveStartKey: exclusiveStartKey,
      }),
    );
    for (const item of result.Items ?? []) {
      items.push(item as CampusIncident);
    }
    exclusiveStartKey = result.LastEvaluatedKey as Record<string, unknown> | undefined;
  } while (exclusiveStartKey);

  return items;
}

export async function syncCleryFromPlatform(opts: {
  agencyId: string;
  campusCode: string;
  academicYear: string;
  defaultGeography: CleryGeography;
  actorId: string;
}): Promise<{ created: number; skipped: number; entries: CleryEntry[] }> {
  if (!env.enableCampusClery) throw new Error("FEATURE_DISABLED");
  const { start, end } = academicYearBounds(opts.academicYear);
  const startMs = Date.parse(start);
  const endMs = Date.parse(end);

  const existing = await listCleryEntries(opts);
  const linked = new Set(
    existing.map((e) => e.platformIncidentId).filter(Boolean) as string[],
  );

  const incidents = await listAllPlatformIncidents(opts.campusCode);
  let created = 0;
  let skipped = 0;
  const entries: CleryEntry[] = [];

  for (const incident of incidents) {
    if (!incident.cleryCategory) {
      skipped += 1;
      continue;
    }
    const parsed = cleryCategorySchema.safeParse(incident.cleryCategory);
    if (!parsed.success) {
      skipped += 1;
      continue;
    }
    const occurredMs = Date.parse(incident.createdAt);
    if (Number.isNaN(occurredMs) || occurredMs < startMs || occurredMs > endMs) {
      skipped += 1;
      continue;
    }
    if (linked.has(incident.id)) {
      skipped += 1;
      continue;
    }

    const now = new Date().toISOString();
    const entryId = makeId("clery");
    const entry: CleryEntry = {
      entryId,
      agencyId: opts.agencyId,
      campusCode: opts.campusCode.toUpperCase(),
      academicYear: opts.academicYear,
      category: parsed.data,
      geography: (incident.cleryGeography as CleryGeography | null | undefined) ?? opts.defaultGeography,
      occurredAt: incident.createdAt,
      location: [incident.buildingLabel, incident.roomCode].filter(Boolean).join(", "),
      building: incident.buildingLabel,
      notes: incident.description.slice(0, 4000),
      hateCrimeBias: null,
      unfounded: false,
      includedInAsr: true,
      source: "platform_incident",
      externalSourceSystem: null,
      externalRecordId: null,
      platformIncidentId: incident.id,
      reviewedBy: null,
      reviewedAt: null,
      createdBy: opts.actorId,
      createdAt: now,
      updatedAt: now,
    };

    await putCleryEntry(entry, opts.actorId, AUDIT_EVENT_TYPES.CAMPUS_CLERY_PLATFORM_SYNCED);
    linked.add(incident.id);
    entries.push(entry);
    created += 1;
  }

  return { created, skipped, entries };
}

/** Parse a simple CSV (header row required) into Clery import rows. */
export function parseCleryCsv(csvText: string): CleryImportRow[] {
  const lines = csvText
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
  if (lines.length < 2) return [];

  const headers = splitCsvLine(lines[0]).map((h) => h.trim().toLowerCase());
  const required = ["occurredat", "category"];
  for (const r of required) {
    if (!headers.includes(r)) {
      throw new Error(`CSV_MISSING_COLUMN:${r}`);
    }
  }

  const rows: CleryImportRow[] = [];
  for (const line of lines.slice(1)) {
    const cols = splitCsvLine(line);
    const get = (name: string) => {
      const idx = headers.indexOf(name);
      return idx >= 0 ? (cols[idx] ?? "").trim() : "";
    };

    const categoryParsed = cleryCategorySchema.safeParse(get("category"));
    if (!categoryParsed.success) {
      throw new Error(`CSV_INVALID_CATEGORY:${get("category")}`);
    }

    const geoRaw = get("geography") || "on_campus";
    const geography = (CLERY_GEOGRAPHIES as readonly string[]).includes(geoRaw)
      ? (geoRaw as CleryGeography)
      : geoLabelToCode(geoRaw);

    rows.push({
      occurredAt: get("occurredat"),
      category: categoryParsed.data,
      geography,
      location: get("location"),
      building: get("building"),
      notes: get("notes"),
      hateCrimeBias: get("hatecrimebias") || null,
      unfounded: ["1", "true", "yes", "y"].includes(get("unfounded").toLowerCase()),
      includedInAsr: !["0", "false", "no", "n"].includes(get("includedinasr").toLowerCase()),
      externalRecordId: get("externalrecordid") || null,
    });
  }
  return rows;
}

function geoLabelToCode(label: string): CleryGeography {
  const lower = label.toLowerCase();
  for (const [code, pretty] of Object.entries(CLERY_GEOGRAPHY_LABELS) as Array<
    [CleryGeography, string]
  >) {
    if (pretty.toLowerCase() === lower || code === lower) return code;
  }
  return "on_campus";
}

function splitCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        cur += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }
    if (ch === "," && !inQuotes) {
      out.push(cur);
      cur = "";
      continue;
    }
    cur += ch;
  }
  out.push(cur);
  return out;
}
