import type { CampusIncident, CampusIncidentType } from "./campus-types.js";

export const CLERY_CATEGORIES = [
  "Criminal Homicide - Murder/Non-negligent Manslaughter",
  "Criminal Homicide - Manslaughter by Negligence",
  "Sexual Assault - Rape",
  "Sexual Assault - Fondling",
  "Sexual Assault - Incest",
  "Sexual Assault - Statutory Rape",
  "Robbery",
  "Aggravated Assault",
  "Burglary",
  "Motor Vehicle Theft",
  "Arson",
  "VAWA - Domestic Violence",
  "VAWA - Dating Violence",
  "VAWA - Stalking",
  "Hate Crime",
  "Arrests - Weapons Violations",
  "Arrests - Drug Abuse Violations",
  "Arrests - Liquor Law Violations",
] as const;

export type CleryCategory = (typeof CLERY_CATEGORIES)[number];

const TYPE_TO_CLERY: Partial<Record<CampusIncidentType, CleryCategory>> = {
  property_crime: "Burglary",
  active_threat: "Aggravated Assault",
};

const KEYWORD_CLERY: Array<{ keywords: string[]; category: CleryCategory }> = [
  { keywords: ["arson", "fire", "set fire"], category: "Arson" },
  { keywords: ["robbery", "robbed", "stole from"], category: "Robbery" },
  { keywords: ["assault", "attacked", "hit", "punched"], category: "Aggravated Assault" },
  { keywords: ["car", "vehicle", "auto", "truck", "van"], category: "Motor Vehicle Theft" },
  { keywords: ["weapon", "gun", "knife", "firearm", "explosive"], category: "Arrests - Weapons Violations" },
  { keywords: ["drug", "narcotics", "marijuana", "cocaine", "pills"], category: "Arrests - Drug Abuse Violations" },
  { keywords: ["alcohol", "drunk", "intoxicated", "liquor"], category: "Arrests - Liquor Law Violations" },
  { keywords: ["stalk", "following me", "won't leave me alone"], category: "VAWA - Stalking" },
  { keywords: ["domestic", "partner", "spouse", "boyfriend", "girlfriend"], category: "VAWA - Domestic Violence" },
];

/**
 * Keyword-based suggestion only — NEVER automatic classification.
 * Final determination must be made by designated Campus Security Authority.
 */
export function suggestCleryCategory(type: CampusIncidentType, description: string): CleryCategory | null {
  const lower = description.toLowerCase();
  const typeMatch = TYPE_TO_CLERY[type];
  if (typeMatch) return typeMatch;

  const matches = KEYWORD_CLERY.filter(({ keywords }) => keywords.some((k) => lower.includes(k)));
  if (matches.length === 1) return matches[0].category;
  return null;
}

const CSV_HEADER = [
  "Generated by Rapid Cortex Campus.",
  "Review required by designated Campus Security Authority before publication.",
  "Rapid Cortex does not make Clery Act determinations.",
  "",
  "Incident ID,Date,Time,Category,Location,Building,On Campus,Notes",
].join("\n");

export function exportCleryReport(incidents: CampusIncident[], academicYear: string): string {
  const classified = incidents.filter((i) => i.cleryCategory);
  const rows = classified.map((i) => {
    const d = new Date(i.createdAt);
    const date = d.toLocaleDateString("en-US");
    const time = d.toLocaleTimeString("en-US", { hour12: false });
    const location = [i.buildingLabel, i.roomCode].filter(Boolean).join(", ");
    return [
      i.id,
      date,
      time,
      `"${i.cleryCategory ?? ""}"`,
      `"${location}"`,
      `"${i.buildingLabel}"`,
      "On Campus",
      `"${i.description.slice(0, 100).replace(/"/g, "'")}"`,
    ].join(",");
  });

  return [`# Academic Year: ${academicYear}`, CSV_HEADER, ...rows].join("\n");
}
