/**
 * Call Assist — 311 Non-Emergency Intent Registry
 *
 * 22 primary category intents + FallbackIntent.
 * Each intent uses:
 *   1. SubIssueType slot  — category-specific custom type for disambiguation
 *   2. ServiceAddress     — AMAZON.FreeFormInput (Lex V2 has no AMAZON.Address)
 *   3. IsOngoing          — CA_IsOngoing custom type
 *   4. IssueDescription   — freeform text capture
 *   5. CallerName         — AMAZON.FirstName (optional)
 *   6. CallbackNumber     — AMAZON.PhoneNumber (optional)
 *
 * Dialog Lambda handles:
 *   - Safety escalation keyword detection
 *   - Conditional sub-issue disambiguation
 *   - Address validation prompting
 *   - Department routing override based on sub-issue
 */

import type { IntentDefinition } from './types.js';
import { EXHAUSTIVE_UTTERANCES } from './exhaustive-utterances.js';

function mergeUtterances(base: string[], extra: string[] | undefined): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const u of [...base, ...(extra ?? [])]) {
    const key = u.trim().toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(u.trim());
  }
  return out;
}

// ─── Common slot definitions reused across intents ────────────────────────────

const COMMON_SLOTS = {
  serviceAddress: {
    name: 'ServiceAddress',
    description: 'The address or location where the issue is occurring',
    slotTypeName: 'AMAZON.FreeFormInput',
    isRequired: true,
    elicitationPrompt: 'What is the address or cross streets where the issue is located?',
    clarificationPrompts: [
      'Could you give me the street address or the nearest intersection?',
      'What is the closest address or landmark to the issue?',
    ],
    priority: 2,
  },
  isOngoing: {
    name: 'IsOngoing',
    description: 'Whether the issue is happening right now, is chronic, or already occurred',
    slotTypeName: 'CA_IsOngoing',
    isRequired: true,
    elicitationPrompt: 'Is this happening right now, is it an ongoing issue, or did it already occur?',
    clarificationPrompts: ['Is this a current problem or something that already happened?'],
    priority: 3,
  },
  issueDescription: {
    name: 'IssueDescription',
    description: 'Additional details about the issue in the callers own words',
    slotTypeName: 'AMAZON.FreeFormInput',
    isRequired: false,
    elicitationPrompt: 'Can you describe the issue in a bit more detail?',
    clarificationPrompts: ['Any additional details that would help us respond?'],
    priority: 4,
  },
  callerName: {
    name: 'CallerName',
    description: 'Caller name for service request record',
    slotTypeName: 'AMAZON.FirstName',
    isRequired: false,
    elicitationPrompt: "May I have your name for the service request? You are welcome to remain anonymous.",
    clarificationPrompts: ['Your name, or you can say anonymous if you prefer.'],
    priority: 5,
  },
  callbackNumber: {
    name: 'CallbackNumber',
    description: 'Callback phone number if follow-up is needed',
    slotTypeName: 'AMAZON.PhoneNumber',
    isRequired: false,
    elicitationPrompt: 'Would you like to provide a callback number for updates on your request?',
    clarificationPrompts: ['A phone number where we can reach you if needed.'],
    priority: 6,
  },
};

// ─── Intent Definitions ────────────────────────────────────────────────────────

export const INTENTS: IntentDefinition[] = [

  // ── 1. ROADS & INFRASTRUCTURE ───────────────────────────────────────────────
  {
    name: 'ReportRoadsInfrastructure',
    displayName: 'Roads & Infrastructure',
    description: 'Report road damage, sidewalk issues, manholes, flooding, debris, snow removal, or infrastructure problems',
    category: 'ROADS_INFRASTRUCTURE',
    primaryDepartment: 'PUBLIC_WORKS',
    priorityLevel: 'STANDARD',
    escalationKeywords: ['sinkhole opening', 'road collapsing', 'car fell in hole', 'manhole exploded', 'road is gone'],
    requiresDisambiguation: true,
    sampleUtterances: [
      'There is a pothole on my street',
      'The road is damaged',
      'There is a hole in the road',
      'My sidewalk is broken',
      'There is a missing manhole cover',
      'The road is flooded',
      'There is debris blocking the road',
      'My street was not plowed',
      'There is a dead animal in the road',
      'The alley needs to be repaired',
      'There is a sinkhole',
      'The road is crumbling',
      'I need the road fixed',
      'There is ice on the street and it was not salted',
      'A fallen tree is blocking a travel lane',
      'Someone is digging in the street without a permit',
      'The bridge is damaged',
      'My curb ramp is broken',
    ],
    slots: [
      {
        name: 'RoadsSubIssue',
        description: 'Specific type of road or infrastructure issue',
        slotTypeName: 'CA_Roads_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What type of road or infrastructure issue are you reporting? For example, a pothole, damaged sidewalk, missing manhole cover, street flooding, or debris?',
        clarificationPrompts: [
          'Is this a pothole, sidewalk damage, flooding, debris, manhole issue, or something else?',
          'Can you describe what the road problem looks like?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your {RoadsSubIssue} report at {ServiceAddress}. Shall I submit this service request to Public Works?',
    fulfillmentMessage: 'Your road and infrastructure report has been submitted to Public Works. You will receive a service request number. You can track it by calling 311 again or visiting the city portal.',
  },

  // ── 2. STREET LIGHTING ───────────────────────────────────────────────────────
  {
    name: 'ReportStreetLighting',
    displayName: 'Street Lighting & Signals',
    description: 'Report streetlight outages, flickering lights, pole damage, traffic signal malfunctions, or pedestrian signal issues',
    category: 'STREET_LIGHTING',
    primaryDepartment: 'PUBLIC_WORKS_ELECTRICAL',
    priorityLevel: 'STANDARD',
    escalationKeywords: ['exposed live wire', 'wire sparking', 'electrocution', 'wire on fire', 'pole fell on car'],
    requiresDisambiguation: false,
    sampleUtterances: [
      'The streetlight is out',
      'A street lamp is not working',
      'The traffic light is not working',
      'The traffic signal is completely dark',
      'The traffic light is out at the intersection',
      'The streetlight is on during the day',
      'The light pole is damaged',
      'The light is flickering',
      'The pedestrian signal is broken',
      'The crosswalk button does not work',
      'The whole block is dark',
      'There are wires hanging from the light pole',
      'The signal is stuck on red',
      'The traffic light timing seems off',
      'My street has no lights working',
    ],
    slots: [
      {
        name: 'LightingSubIssue',
        description: 'Specific type of lighting or signal issue',
        slotTypeName: 'CA_Lighting_SubIssue',
        isRequired: true,
        elicitationPrompt: 'Is this about a streetlight, a traffic signal, a light pole, or a pedestrian crosswalk signal?',
        clarificationPrompts: [
          'Is the light completely out, flickering, or is this about the traffic signal?',
          'Is this a pedestrian signal, a streetlight, or a traffic signal for vehicles?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your lighting report for {LightingSubIssue} at {ServiceAddress}. Shall I submit this to Public Works Electrical?',
    fulfillmentMessage: 'Your lighting report has been submitted. A service request has been sent to the Electrical Division. Typical response time is 24 to 72 hours.',
  },

  // ── 3. TRAFFIC SIGNS & MARKINGS ──────────────────────────────────────────────
  {
    name: 'ReportTrafficSignsMarkings',
    displayName: 'Traffic Signs & Markings',
    description: 'Report missing, damaged, faded, or incorrect traffic signs and road markings',
    category: 'TRAFFIC_SIGNS_MARKINGS',
    primaryDepartment: 'PUBLIC_WORKS',
    priorityLevel: 'STANDARD',
    escalationKeywords: ['stop sign is missing and cars are running through', 'accident because sign is missing'],
    requiresDisambiguation: false,
    sampleUtterances: [
      'A stop sign is missing',
      'There is no street sign at this corner',
      'The sign is damaged',
      'The yield sign is gone',
      'The crosswalk markings are faded',
      'I cannot see the lane markings',
      'The speed limit sign is missing',
      'There is a wrong sign at this location',
      'The bike lane is not marked',
      'The school zone markings are faded',
      'A sign is blocking another sign',
      'Tree branches are covering the stop sign',
    ],
    slots: [
      {
        name: 'SignsSubIssue',
        description: 'Specific type of sign or road marking issue',
        slotTypeName: 'CA_Signs_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What type of sign or road marking issue are you reporting? For example, a missing stop sign, faded crosswalk, incorrect sign, or lane markings?',
        clarificationPrompts: [
          'Is this a missing sign, a damaged sign, or a faded road marking?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your sign issue report for {SignsSubIssue} at {ServiceAddress}. Shall I submit this service request?',
    fulfillmentMessage: 'Your traffic sign and markings report has been submitted. A service request has been sent to Public Works.',
  },

  // ── 4. SANITATION & WASTE ────────────────────────────────────────────────────
  {
    name: 'ReportSanitationWaste',
    displayName: 'Sanitation & Waste',
    description: 'Report missed pickups, illegal dumping, overflowing trash cans, request bin replacement, dead animal pickup, or get disposal information',
    category: 'SANITATION_WASTE',
    primaryDepartment: 'SANITATION',
    priorityLevel: 'STANDARD',
    requiresDisambiguation: true,
    sampleUtterances: [
      'My garbage was not picked up',
      'They missed my trash',
      'Someone dumped trash on my street',
      'There is illegal dumping',
      'The public trash can is overflowing',
      'My recycling was not picked up',
      'I need a new trash bin',
      'My trash can is broken',
      'There is a dead animal in my yard',
      'I need a bulk pickup',
      'Where do I drop off old electronics',
      'How do I dispose of medication',
      'Someone dumped a mattress',
      'There is a lot of litter on the street',
      'The dumpster is overflowing',
      'My bin was stolen',
      'Where do I drop off paint',
    ],
    slots: [
      {
        name: 'SanitationSubIssue',
        description: 'Specific type of sanitation or waste issue',
        slotTypeName: 'CA_Sanitation_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the sanitation issue? For example, missed pickup, illegal dumping, overflowing trash can, dead animal pickup, or a disposal question?',
        clarificationPrompts: [
          'Is this a missed collection, an illegal dumping report, or do you need a bin replaced?',
          'Are you reporting a problem, or do you need information about disposal services?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your sanitation report for {SanitationSubIssue} at {ServiceAddress}. Shall I submit this to the Sanitation Department?',
    fulfillmentMessage: 'Your sanitation request has been submitted. A service request has been sent to the Sanitation Department.',
  },

  // ── 5. WATER, SEWER & DRAINAGE ───────────────────────────────────────────────
  {
    name: 'ReportWaterSewerDrainage',
    displayName: 'Water, Sewer & Drainage',
    description: 'Report water main breaks, fire hydrant issues, low pressure, water quality problems, sewer backups, blocked drains, or billing disputes',
    category: 'WATER_SEWER_DRAINAGE',
    primaryDepartment: 'WATER_SEWER_AUTHORITY',
    priorityLevel: 'ELEVATED',
    escalationKeywords: [
      'water geyser shooting into air',
      'massive water break flooding street',
      'sewer backing up into my house',
      'sewage in my basement',
      'water smells like gas',
    ],
    requiresDisambiguation: true,
    sampleUtterances: [
      'There is a water main break',
      'A water main is spraying into the street',
      'The fire hydrant is leaking',
      'I have no water',
      'My water pressure is very low',
      'My water looks brown',
      'The water smells strange',
      'There is a sewer backup on the street',
      'It smells like sewage outside',
      'The storm drain is blocked',
      'There is water coming from the ground',
      'The catch basin is clogged',
      'My water bill is wrong',
      'There is an irrigation leak in the median',
      'There is an open sewer cap',
      'Water is pooling under the bridge',
      'Someone is dumping into the storm drain',
    ],
    slots: [
      {
        name: 'WaterSubIssue',
        description: 'Specific type of water, sewer, or drainage issue',
        slotTypeName: 'CA_Water_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the water or sewer issue? Is it a water main break, fire hydrant problem, low pressure, water quality concern, sewer issue, or blocked drain?',
        clarificationPrompts: [
          'Is water actively coming from the ground, or is this a quality or pressure issue?',
          'Is this a sewer smell, a drain backup, or a water service issue?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your water and sewer report for {WaterSubIssue} at {ServiceAddress}. Shall I submit this to the Water Authority?',
    fulfillmentMessage: 'Your water and sewer report has been submitted. A service request has been sent to the Water and Sewer Authority. For active main breaks, a crew will be dispatched.',
    conditionalDepartmentRouting: {
      WATER_METER_DISPUTE: 'WATER_SEWER_AUTHORITY',
      WATER_BILL_DISPUTE: 'THREE11_OPERATIONS',
    },
  },

  // ── 6. NOISE COMPLAINT ───────────────────────────────────────────────────────
  {
    name: 'ReportNoiseComplaint',
    displayName: 'Noise Complaint',
    description: 'Report noise disturbances including loud music, parties, construction, vehicles, animals, or fireworks',
    category: 'NOISE_COMPLAINT',
    primaryDepartment: 'CODE_ENFORCEMENT',
    conditionalDepartmentRouting: {
      DOG_BARKING: 'ANIMAL_CONTROL',
      PERMITTED_EVENT_NOISE: 'THREE11_OPERATIONS',
    },
    priorityLevel: 'STANDARD',
    requiresDisambiguation: true,
    sampleUtterances: [
      'My neighbor is playing loud music',
      'There is a loud party next door',
      'Construction is happening too early',
      'There is a loud car alarm going off',
      'My neighbors dog will not stop barking',
      'A bar nearby is too loud',
      'There are fireworks going off',
      'A motorcycle has a very loud exhaust',
      'There is loud construction noise outside permitted hours',
      'My neighbors are having a very loud party at 2 AM',
      'The leaf blower is running before 7 AM',
      'There is amplified music on the street',
      'The event nearby is too loud',
    ],
    slots: [
      {
        name: 'NoiseSubIssue',
        description: 'Specific type of noise complaint',
        slotTypeName: 'CA_Noise_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What type of noise is the problem? For example, loud music, a party, construction, a car alarm, a barking dog, or fireworks?',
        clarificationPrompts: [
          'Is this coming from a residence, a business, or a vehicle?',
          'Is this construction noise, music, an alarm, or an animal?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your noise complaint for {NoiseSubIssue} at {ServiceAddress}. Is this happening right now?',
    fulfillmentMessage: 'Your noise complaint has been submitted. A service request has been sent to Code Enforcement.',
  },

  // ── 7. ABANDONED & ILLEGALLY PARKED VEHICLES ─────────────────────────────────
  {
    name: 'ReportVehicleIssue',
    displayName: 'Abandoned & Illegal Vehicles',
    description: 'Report abandoned vehicles, illegal parking, vehicles blocking hydrants, driveways, sidewalks, or bike lanes',
    category: 'ABANDONED_ILLEGAL_VEHICLES',
    primaryDepartment: 'PARKING_ENFORCEMENT',
    priorityLevel: 'STANDARD',
    escalationKeywords: ['car blocking ambulance', 'blocking fire truck', 'blocking emergency vehicle'],
    requiresDisambiguation: false,
    sampleUtterances: [
      'There is an abandoned car on my street',
      'A car has been parked here for weeks',
      'There is a car blocking my driveway',
      'A car is parked in front of the fire hydrant',
      'A car is blocking the sidewalk',
      'There is a car parked in the bike lane',
      'Someone is double parked',
      'There is an RV that has been parked here too long',
      'A commercial truck is parked in our neighborhood overnight',
      'A car is parked on the lawn',
      'The car has no license plates',
      'A car has expired tags',
      'Someone is parked in a handicap space without a placard',
      'A car is parked in a tow away zone',
      'There is an inoperable vehicle on the street',
    ],
    slots: [
      {
        name: 'VehicleSubIssue',
        description: 'Specific type of vehicle parking or abandonment issue',
        slotTypeName: 'CA_Vehicles_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the vehicle issue? Is it abandoned, blocking a driveway or hydrant, parked illegally, or something else?',
        clarificationPrompts: [
          'Is the vehicle abandoned, or is it parked illegally right now?',
          'Is the vehicle blocking something like a driveway, hydrant, sidewalk, or bike lane?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      {
        name: 'VehicleDetails',
        description: 'Color, make, model, and license plate of the vehicle if known',
        slotTypeName: 'AMAZON.FreeFormInput',
        isRequired: false,
        elicitationPrompt: 'Can you describe the vehicle? Color, make, model, and license plate if visible?',
        clarificationPrompts: ['What does the vehicle look like?'],
        priority: 3,
      },
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your vehicle report for {VehicleSubIssue} at {ServiceAddress}. Shall I submit this to Parking Enforcement?',
    fulfillmentMessage: 'Your vehicle complaint has been submitted. A service request has been sent to Parking Enforcement.',
  },

  // ── 8. GRAFFITI & VANDALISM ──────────────────────────────────────────────────
  {
    name: 'ReportGraffitiVandalism',
    displayName: 'Graffiti & Vandalism',
    description: 'Report graffiti on public or private property, vandalized street furniture, bus shelters, park equipment, or public art',
    category: 'GRAFFITI_VANDALISM',
    primaryDepartment: 'PUBLIC_WORKS',
    priorityLevel: 'STANDARD',
    requiresDisambiguation: false,
    sampleUtterances: [
      'There is graffiti on a building',
      'Someone spray painted the wall',
      'There is graffiti in the park',
      'A bus shelter was vandalized',
      'The park bench is broken',
      'There is graffiti on the bridge',
      'A utility box was tagged',
      'The parking meter was vandalized',
      'The public art was defaced',
      'There is graffiti on my building',
      'Gang graffiti appeared overnight',
      'The playground was vandalized',
      'Public property has been spray painted',
    ],
    slots: [
      {
        name: 'GraffitiSubIssue',
        description: 'Specific type of graffiti or vandalism',
        slotTypeName: 'CA_Graffiti_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the graffiti or vandalism on? For example, a public building, bridge, bus shelter, utility box, park equipment, or private property?',
        clarificationPrompts: [
          'Is this on public property or private property?',
          'What was vandalized — a building, park equipment, a sign, or something else?',
        ],
        priority: 1,
      },
      {
        name: 'PropertyOwnership',
        description: 'Whether the graffiti is on public or private property',
        slotTypeName: 'CA_PropertyOwnership',
        isRequired: true,
        elicitationPrompt: 'Is this on public property or private property?',
        clarificationPrompts: ['Is it on a city-owned surface or a private building?'],
        priority: 2,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your graffiti report for {GraffitiSubIssue} at {ServiceAddress}. Shall I submit this?',
    fulfillmentMessage: 'Your graffiti report has been submitted. A service request has been created. Public property graffiti is typically removed within 5 business days.',
  },

  // ── 9. ANIMALS & PESTS ──────────────────────────────────────────────────────
  {
    name: 'ReportAnimalsPests',
    displayName: 'Animals & Pests',
    description: 'Report stray animals, animal neglect or cruelty, wildlife complaints, rodent infestations, bees, mosquitoes, or dead animal pickup',
    category: 'ANIMALS_PESTS',
    primaryDepartment: 'ANIMAL_CONTROL',
    conditionalDepartmentRouting: {
      RODENT_INFESTATION: 'SANITATION',
      RODENT_BAITING_REQUEST: 'SANITATION',
      MOSQUITO_STANDING_WATER: 'ENVIRONMENTAL_QUALITY',
      MOSQUITO_CONTROL_REQUEST: 'ENVIRONMENTAL_QUALITY',
      STAGNANT_WATER_MOSQUITO: 'ENVIRONMENTAL_QUALITY',
    },
    priorityLevel: 'STANDARD',
    escalationKeywords: ['dog is attacking me right now', 'animal is attacking', 'dog bit my child', 'being chased by animal'],
    requiresDisambiguation: true,
    sampleUtterances: [
      'There is a stray dog running loose',
      'My neighbors dog keeps barking',
      'I was bitten by a dog',
      'There are raccoons getting into my trash',
      'I see a coyote in the neighborhood',
      'There is an injured bird in my yard',
      'There are rats on my street',
      'There is a bee swarm on public property',
      'My neighbor is neglecting their dog',
      'An animal is being abused',
      'There are feral cats everywhere',
      'There is a snake in my yard',
      'There are mosquitoes breeding in standing water',
      'I need a dead animal picked up',
      'There are pigeons making a mess',
      'I need rodent baiting service',
      'There is a wasp nest in the park',
    ],
    slots: [
      {
        name: 'AnimalSubIssue',
        description: 'Specific type of animal or pest issue',
        slotTypeName: 'CA_Animals_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What type of animal or pest issue are you reporting? A stray dog, wildlife, rodents, insects, or something else?',
        clarificationPrompts: [
          'Is this about a stray or aggressive animal, a wildlife complaint, a pest infestation, or a dead animal pickup?',
          'What type of animal are you reporting?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      {
        name: 'AnimalDescription',
        description: 'Description of the animal including type, color, size, and behavior',
        slotTypeName: 'AMAZON.FreeFormInput',
        isRequired: false,
        elicitationPrompt: 'Can you describe the animal — what type, what it looks like, and what it is doing?',
        clarificationPrompts: ['What does the animal look like and how is it behaving?'],
        priority: 3,
      },
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your animal report for {AnimalSubIssue} at {ServiceAddress}. Shall I submit this?',
    fulfillmentMessage: 'Your animal and pest report has been submitted. A service request has been sent to Animal Control.',
  },

  // ── 10. TREES & VEGETATION ───────────────────────────────────────────────────
  {
    name: 'ReportTreesVegetation',
    displayName: 'Trees & Vegetation',
    description: 'Report fallen trees, dead street trees, trees blocking signs or roads, overgrown vegetation, or request trimming and new tree planting',
    category: 'TREES_VEGETATION',
    primaryDepartment: 'URBAN_FORESTRY',
    priorityLevel: 'STANDARD',
    escalationKeywords: ['tree fell on a car', 'tree hit a house', 'tree hit power line and sparking', 'tree blocking emergency access'],
    requiresDisambiguation: false,
    sampleUtterances: [
      'A tree fell and is blocking the street',
      'A large branch came down',
      'There is a dead tree on my street',
      'The tree roots are breaking my sidewalk',
      'A tree is overhanging the road',
      'Bushes are blocking the stop sign',
      'I want to request a tree trimming',
      'The street tree is dying',
      'Vegetation is blocking the sidewalk',
      'There is an overgrown vacant lot',
      'I would like a new tree planted on my street',
      'There is an invasive plant taking over the park',
      'A tree stump needs to be ground down',
      'The storm damaged a tree',
    ],
    slots: [
      {
        name: 'TreeSubIssue',
        description: 'Specific type of tree or vegetation issue',
        slotTypeName: 'CA_Trees_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the tree or vegetation issue? A fallen tree, dead tree, overgrown vegetation blocking something, or a trimming request?',
        clarificationPrompts: [
          'Is the tree fallen or a hazard, or is this a maintenance request like trimming?',
          'Is vegetation blocking a sign, sidewalk, or road?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your tree and vegetation report for {TreeSubIssue} at {ServiceAddress}. Shall I submit this to Urban Forestry?',
    fulfillmentMessage: 'Your tree and vegetation report has been submitted. A service request has been sent to Urban Forestry.',
  },

  // ── 11. PARKS & PUBLIC SPACES ────────────────────────────────────────────────
  {
    name: 'ReportParksPublicSpaces',
    displayName: 'Parks & Public Spaces',
    description: 'Report broken playground equipment, park lighting, restroom issues, vandalism, overgrown areas, unsafe courts, or unauthorized use in parks',
    category: 'PARKS_PUBLIC_SPACES',
    primaryDepartment: 'PARKS_RECREATION',
    priorityLevel: 'STANDARD',
    requiresDisambiguation: false,
    sampleUtterances: [
      'The playground equipment is broken',
      'A park light is out',
      'The park restroom is locked',
      'The park bathroom is disgusting',
      'The park fountain is not working',
      'There is someone camping in the park',
      'The basketball court is damaged',
      'The park grass is overgrown',
      'Someone vandalized the park equipment',
      'The splash pad is not working',
      'There is an unauthorized event in the park',
      'The trail is damaged',
      'There is a dog in the park where dogs are not allowed',
      'The outdoor fitness equipment is broken',
      'The skate park needs repair',
      'The park gate is locked when it should be open',
    ],
    slots: [
      {
        name: 'ParkSubIssue',
        description: 'Specific type of park or public space issue',
        slotTypeName: 'CA_Parks_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the park issue? Broken equipment, lighting, restroom, overgrown area, or unauthorized activity?',
        clarificationPrompts: [
          'Is this about damaged equipment, a safety concern, or the condition of the park?',
        ],
        priority: 1,
      },
      {
        name: 'ParkName',
        description: 'Name of the park where the issue is occurring',
        slotTypeName: 'AMAZON.FreeFormInput',
        isRequired: false,
        elicitationPrompt: 'What is the name of the park?',
        clarificationPrompts: ['Which park is this happening in?'],
        priority: 2,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your parks report for {ParkSubIssue} at {ServiceAddress}. Shall I submit this to Parks and Recreation?',
    fulfillmentMessage: 'Your parks report has been submitted. A service request has been sent to the Parks and Recreation Department.',
  },

  // ── 12. BUILDINGS & HOUSING CODE ─────────────────────────────────────────────
  {
    name: 'ReportBuildingsHousing',
    displayName: 'Buildings & Housing',
    description: 'Report building code violations, abandoned properties, unpermitted construction, tenant issues like no heat or mold, or unsafe structures',
    category: 'BUILDINGS_HOUSING',
    primaryDepartment: 'CODE_ENFORCEMENT',
    conditionalDepartmentRouting: {
      NO_HEAT_TENANT: 'HOUSING_COMMUNITY_DEV',
      NO_HOT_WATER_TENANT: 'HOUSING_COMMUNITY_DEV',
      PEST_INFESTATION_TENANT: 'HOUSING_COMMUNITY_DEV',
      MOLD_COMPLAINT: 'HOUSING_COMMUNITY_DEV',
      LEAD_PAINT_CONCERN: 'ENVIRONMENTAL_QUALITY',
    },
    priorityLevel: 'STANDARD',
    escalationKeywords: ['building is collapsing', 'wall falling down', 'structure about to fall', 'building on fire', 'gas smell in building'],
    requiresDisambiguation: true,
    sampleUtterances: [
      'There is an abandoned building on my block',
      'Someone is building without a permit',
      'My landlord will not fix the heat',
      'There is mold in my apartment',
      'My building has no heat',
      'There are roaches and my landlord will not help',
      'There is lead paint peeling in my apartment',
      'The building has broken windows',
      'There is an illegal apartment conversion',
      'The fence is about to fall over',
      'My neighbor is hoarding junk outside',
      'There is illegal construction happening',
      'The elevator in my building is out',
      'The fire escape is blocked',
      'There is a scaffolding problem',
      'An unsafe retaining wall is about to fall',
    ],
    slots: [
      {
        name: 'BuildingSubIssue',
        description: 'Specific type of building or housing code issue',
        slotTypeName: 'CA_Buildings_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the building or housing issue? A code violation, tenant concern like no heat, unpermitted construction, or structural problem?',
        clarificationPrompts: [
          'Is this a tenant complaint, a building code violation, or an unsafe structure?',
          'Is this about your own unit, or a property you are reporting as a neighbor?',
        ],
        priority: 1,
      },
      {
        name: 'PropertyOwnership',
        description: 'Relationship to the property being reported',
        slotTypeName: 'CA_PropertyOwnership',
        isRequired: true,
        elicitationPrompt: 'Is this your property, a rental you live in, or a neighboring property you are reporting?',
        clarificationPrompts: ['Are you a tenant, a property owner, or a neighbor reporting this?'],
        priority: 2,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your building and housing report for {BuildingSubIssue} at {ServiceAddress}. Shall I submit this?',
    fulfillmentMessage: 'Your building and housing report has been submitted. A service request has been sent to Code Enforcement.',
  },

  // ── 13. HOMELESS & SOCIAL SERVICES ───────────────────────────────────────────
  {
    name: 'ReportHomelessSocialServices',
    displayName: 'Homeless & Social Services',
    description: 'Report homeless encampments, request welfare checks, outreach team response, needles debris, or request social service referrals',
    category: 'HOMELESS_SOCIAL_SERVICES',
    primaryDepartment: 'SOCIAL_SERVICES',
    priorityLevel: 'STANDARD',
    escalationKeywords: ['person is unconscious', 'person is not breathing', 'person is in medical distress', 'person has a weapon'],
    requiresDisambiguation: false,
    sampleUtterances: [
      'There is a homeless encampment on the sidewalk',
      'There are tents under the bridge',
      'Someone is sleeping in a doorway',
      'There is a person who looks like they need help',
      'Can you do a welfare check on someone outside',
      'There are needles on the ground in the park',
      'I want to connect someone with services',
      'There is a large encampment in the park',
      'Someone looks sick and is outside',
      'There are syringes in the alley',
      'There is an encampment near the school',
      'I need information about homeless services',
    ],
    slots: [
      {
        name: 'HomelessSubIssue',
        description: 'Specific type of homeless or social services request',
        slotTypeName: 'CA_Homeless_SubIssue',
        isRequired: true,
        elicitationPrompt: 'Are you reporting an encampment, requesting a welfare check, reporting needles or debris, or looking for a service referral?',
        clarificationPrompts: [
          'Is this a report of an encampment, a concern about an individuals wellbeing, or sharps on the ground?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your report for {HomelessSubIssue} at {ServiceAddress}. Shall I submit this?',
    fulfillmentMessage: 'Your request has been submitted. A service request has been routed to the appropriate social services team.',
  },

  // ── 14. ENVIRONMENTAL & HEALTH ────────────────────────────────────────────────
  {
    name: 'ReportEnvironmentalHealth',
    displayName: 'Environmental & Health',
    description: 'Report air quality complaints, illegal burning, hazardous spills, oil in storm drains, septic overflows, restaurant sanitation, or waterway pollution',
    category: 'ENVIRONMENTAL_HEALTH',
    primaryDepartment: 'ENVIRONMENTAL_QUALITY',
    conditionalDepartmentRouting: {
      RESTAURANT_SANITATION: 'CODE_ENFORCEMENT',
      UNLICENSED_FOOD_VENDOR: 'CODE_ENFORCEMENT',
    },
    priorityLevel: 'STANDARD',
    escalationKeywords: ['gas leak', 'chemical explosion', 'toxic fumes making people sick', 'hazmat', 'people passing out from fumes'],
    requiresDisambiguation: false,
    sampleUtterances: [
      'There is a terrible smell coming from a factory',
      'Someone is burning trash illegally',
      'There was a chemical spill on the road',
      'Oil is going into the storm drain',
      'There is sewage on the sidewalk',
      'There is standing water with mosquitoes breeding in it',
      'I want to report a restaurant for sanitation issues',
      'There is an unlicensed food cart',
      'Pollution is going into the creek',
      'There is a garbage smell from a nearby business',
      'Someone is dumping chemicals',
      'There is mold in a public building',
      'There is excessive smoke in our area',
    ],
    slots: [
      {
        name: 'EnvironmentalSubIssue',
        description: 'Specific type of environmental or health complaint',
        slotTypeName: 'CA_Environmental_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the environmental or health concern? A smell, illegal burning, spill, drain contamination, food safety issue, or something else?',
        clarificationPrompts: [
          'Is this an odor complaint, a spill, illegal burning, a food safety issue, or environmental contamination?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your environmental report for {EnvironmentalSubIssue} at {ServiceAddress}. Shall I submit this?',
    fulfillmentMessage: 'Your environmental and health report has been submitted. A service request has been sent to Environmental Quality.',
  },

  // ── 15. LAW ENFORCEMENT NON-EMERGENCY ────────────────────────────────────────
  {
    name: 'ReportLawEnforcementNonEmergency',
    displayName: 'Police Non-Emergency',
    description: 'Report chronic issues like drug activity, speeding, illegal vehicles, theft (after the fact), property disputes, or request extra patrol. NOT for active emergencies.',
    category: 'LAW_ENFORCEMENT_NON_EMERGENCY',
    primaryDepartment: 'POLICE_NON_EMERGENCY',
    priorityLevel: 'STANDARD',
    escalationKeywords: [
      'crime in progress',
      'happening right now',
      'someone is being hurt',
      'active fight',
      'gun',
      'shooting',
      'stabbing',
      'robbery happening now',
    ],
    requiresDisambiguation: true,
    sampleUtterances: [
      'There is chronic drug dealing on my corner',
      'Cars are always speeding down my street',
      'My package was stolen',
      'My mail was stolen',
      'My catalytic converter was stolen',
      'I want to report a property dispute with my neighbor',
      'I need more police patrols in my neighborhood',
      'People are always loitering at this location',
      'There are ATVs and dirt bikes on the street',
      'I want to follow up on a police report I filed',
      'Can you check on the status of my case',
      'There is a car with a very loud exhaust',
      'There are kids racing cars at night',
      'There is chronic trespassing at this property',
    ],
    slots: [
      {
        name: 'LawEnforcementSubIssue',
        description: 'Specific type of non-emergency law enforcement request',
        slotTypeName: 'CA_LawEnforcement_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the non-emergency police concern? For example, chronic drug activity, speeding, a theft that already occurred, a property dispute, or a patrol request?',
        clarificationPrompts: [
          'Is this an ongoing problem in the area, or something that already happened?',
          'Is this a chronic community issue or a report about something that has already occurred?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your non-emergency police report for {LawEnforcementSubIssue} at {ServiceAddress}. Shall I submit this?',
    fulfillmentMessage: 'Your non-emergency police request has been submitted. A service request has been sent to the Police Department non-emergency unit.',
  },

  // ── 16. FIRE & EMS NON-EMERGENCY ─────────────────────────────────────────────
  {
    name: 'ReportFireEMSNonEmergency',
    displayName: 'Fire & EMS Non-Emergency',
    description: 'Report fire hazards, blocked fire hydrants, open burning without permit, or request smoke detector installation and fire safety information',
    category: 'FIRE_EMS_NON_EMERGENCY',
    primaryDepartment: 'FIRE_MARSHAL_NON_EMERGENCY',
    priorityLevel: 'ELEVATED',
    escalationKeywords: ['fire right now', 'building on fire', 'house is burning', 'smoke coming from building', 'fire spreading'],
    requiresDisambiguation: false,
    sampleUtterances: [
      'There is a fire hazard at a property',
      'The fire hydrant is blocked by vegetation',
      'Someone is burning trash in their yard without a permit',
      'The fire lane is always blocked',
      'I would like to request a smoke detector',
      'I have a question about fire extinguishers',
      'I would like fire safety information',
      'How do I get a free smoke alarm',
      'The fire escape at my building is blocked',
      'There are illegal fireworks stored at a property',
      'What is the phone number for the fire station',
      'There are materials stacked near a building that are a fire hazard',
    ],
    slots: [
      {
        name: 'FireEMSSubIssue',
        description: 'Specific type of fire or EMS non-emergency request',
        slotTypeName: 'CA_FireEMS_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the fire safety concern? A fire hazard, a blocked hydrant or fire lane, illegal burning, or a request for information or equipment?',
        clarificationPrompts: [
          'Is this a fire hazard report, or are you looking for safety information or resources?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your fire safety report for {FireEMSSubIssue} at {ServiceAddress}. Shall I submit this?',
    fulfillmentMessage: 'Your fire safety report has been submitted. A service request has been sent to the Fire Marshal.',
  },

  // ── 17. TRANSIT & TRANSPORTATION ─────────────────────────────────────────────
  {
    name: 'ReportTransitIssue',
    displayName: 'Transit & Transportation',
    description: 'Report bus stop damage, broken bike share stations, scooters on sidewalks, parking meter issues, inquire about towing or parking permits',
    category: 'TRANSIT_TRANSPORTATION',
    primaryDepartment: 'TRANSIT_AUTHORITY',
    conditionalDepartmentRouting: {
      PARKING_METER_BROKEN: 'PARKING_ENFORCEMENT',
      PARKING_PERMIT_INQUIRY: 'PARKING_ENFORCEMENT',
      TOW_INQUIRY: 'PARKING_ENFORCEMENT',
      NO_PARKING_SIGN_DISPUTE: 'PARKING_ENFORCEMENT',
    },
    priorityLevel: 'STANDARD',
    requiresDisambiguation: false,
    sampleUtterances: [
      'The bus stop bench is broken',
      'The bus shelter is damaged',
      'The bus stop sign is missing',
      'The bus is always late on this route',
      'The bike share station is broken',
      'An electric scooter is blocking the sidewalk',
      'The parking meter is not working',
      'I need to know about parking permits',
      'My car was towed and I need to find it',
      'The real time arrival sign at the bus stop is not working',
      'The bus shelter glass is shattered',
      'There is an e-bike abandoned on the sidewalk',
      'Uber and Lyft drivers are parking in the bus stop',
      'I have a paratransit scheduling problem',
      'The pedestrian bridge needs repair',
    ],
    slots: [
      {
        name: 'TransitSubIssue',
        description: 'Specific type of transit or transportation issue',
        slotTypeName: 'CA_Transit_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is the transit or transportation issue? A bus stop problem, bike lane issue, parking meter, scooter on the sidewalk, or a tow inquiry?',
        clarificationPrompts: [
          'Is this about a bus stop, bike share, parking, or transit service?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.isOngoing,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your transit report for {TransitSubIssue} at {ServiceAddress}. Shall I submit this?',
    fulfillmentMessage: 'Your transit and transportation report has been submitted. A service request has been sent to the appropriate department.',
  },

  // ── 18. GOVERNMENT INFORMATION & SERVICES ────────────────────────────────────
  {
    name: 'RequestGovernmentInformation',
    displayName: 'Government Information',
    description: 'Inquire about city services, permits, licenses, inspections, vital records, public records, voter registration, senior services, social services, or other city programs',
    category: 'GOVERNMENT_INFORMATION',
    primaryDepartment: 'THREE11_OPERATIONS',
    priorityLevel: 'INFO_ONLY',
    requiresDisambiguation: false,
    sampleUtterances: [
      'What are the hours for city hall',
      'How do I apply for a business license',
      'How do I renew my business license',
      'What is the zoning for this property',
      'How do I get a building permit',
      'What is the status of my permit',
      'How do I schedule an inspection',
      'How do I get a birth certificate',
      'How do I register to vote',
      'Where do I go to vote',
      'I need information about senior services',
      'I need help paying my rent',
      'I need food assistance',
      'I need a language interpreter for a city appointment',
      'How do I make a public records request',
      'I need information about mental health services',
      'Where can I get help with my utility bill',
      'I need information about domestic violence resources',
      'How do I get a certificate of occupancy',
      'I need information about disability services',
    ],
    slots: [
      {
        name: 'GovInfoSubIssue',
        description: 'Specific type of government information or service needed',
        slotTypeName: 'CA_GovInfo_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What city service or information are you looking for? Permits, licenses, vital records, social services, senior programs, or something else?',
        clarificationPrompts: [
          'Are you looking for information about permits, social services, records, or a city department?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I can help you with information about {GovInfoSubIssue}. Let me connect you with the right resource.',
    fulfillmentMessage: 'I am connecting you with information about {GovInfoSubIssue}. You can also visit the city website or call the relevant department directly.',
  },

  // ── 19. SPECIAL EVENTS & PERMITS ─────────────────────────────────────────────
  {
    name: 'ReportSpecialEventIssue',
    displayName: 'Special Events & Permits',
    description: 'Report noise from permitted events, ask about street closures, or get information about event permits, film permits, parades, and special event applications',
    category: 'SPECIAL_EVENTS_PERMITS',
    primaryDepartment: 'THREE11_OPERATIONS',
    priorityLevel: 'INFO_ONLY',
    requiresDisambiguation: false,
    sampleUtterances: [
      'Why is my street closed',
      'There is an event nearby that is too loud',
      'How do I get a permit for a block party',
      'How do I apply for a special event permit',
      'There is a film crew outside my building',
      'When is the parade route',
      'How do I get a vendor permit for an event',
      'Can I get a fireworks permit',
      'The game day traffic is a problem',
      'I need a tent permit for my event',
    ],
    slots: [
      {
        name: 'SpecialEventSubIssue',
        description: 'Specific type of special event inquiry or complaint',
        slotTypeName: 'CA_SpecialEvents_SubIssue',
        isRequired: true,
        elicitationPrompt: 'What is your special event question or concern? A street closure, event noise complaint, permit application, or something else?',
        clarificationPrompts: [
          'Are you asking about a permit, reporting noise from an event, or asking about a street closure?',
        ],
        priority: 1,
      },
      COMMON_SLOTS.serviceAddress,
      COMMON_SLOTS.issueDescription,
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'I have your special event inquiry for {SpecialEventSubIssue}. Shall I route this appropriately?',
    fulfillmentMessage: 'Your special event inquiry has been submitted. A service request has been sent to the appropriate department.',
  },

  // ── 20. SERVICE REQUEST STATUS ────────────────────────────────────────────────
  {
    name: 'CheckServiceRequestStatus',
    displayName: 'Service Request Status',
    description: 'Check the status of a previously submitted service request, reopen a closed request, escalate an unresolved issue, or get a confirmation number',
    category: 'SERVICE_REQUEST_STATUS',
    primaryDepartment: 'THREE11_OPERATIONS',
    priorityLevel: 'INFO_ONLY',
    requiresDisambiguation: false,
    sampleUtterances: [
      'I want to check on my service request',
      'What is the status of my complaint',
      'I called about this before and it is not fixed',
      'My request was closed but the problem is still there',
      'I need my service request number',
      'I need to reopen my request',
      'I need to escalate my complaint',
      'I reported this last week and nothing happened',
      'Can I get an update on my case',
      'The issue I reported is still not resolved',
      'I want to follow up on a request',
      'I already reported this and need a status',
    ],
    slots: [
      {
        name: 'ServiceStatusSubIssue',
        description: 'What the caller wants to do with their service request',
        slotTypeName: 'CA_ServiceStatus_SubIssue',
        isRequired: true,
        elicitationPrompt: 'Are you checking the status of a request, trying to reopen a closed request, or looking to escalate an unresolved issue?',
        clarificationPrompts: [
          'Do you have a service request number I can look up?',
        ],
        priority: 1,
      },
      {
        name: 'ServiceRequestNumber',
        description: 'The SR number the caller wants to look up',
        slotTypeName: 'AMAZON.AlphaNumeric',
        isRequired: false,
        elicitationPrompt: 'Do you have your service request number? It starts with SR followed by the date and a six-digit number.',
        clarificationPrompts: ['What is your service request or confirmation number?'],
        priority: 2,
      },
      COMMON_SLOTS.callerName,
      COMMON_SLOTS.callbackNumber,
    ],
    confirmationPrompt: 'Let me look up service request {ServiceRequestNumber} for you.',
    fulfillmentMessage: 'I am looking up your service request. One moment please.',
  },

  // ── 21. TRANSFER TO LIVE AGENT ────────────────────────────────────────────────
  {
    name: 'TransferToLiveAgent',
    displayName: 'Transfer to Live Agent',
    description: 'Caller explicitly requests a human operator or the bot cannot handle the request',
    category: 'SERVICE_REQUEST_STATUS',
    primaryDepartment: 'THREE11_OPERATIONS',
    priorityLevel: 'STANDARD',
    requiresDisambiguation: false,
    sampleUtterances: [
      'I want to speak to a person',
      'Transfer me to an agent',
      'Let me speak to a human',
      'I need a real person',
      'Connect me to someone',
      'Give me a live operator',
      'I do not want to talk to a robot',
      'Agent please',
      'Operator',
      'I want to talk to a person',
    ],
    slots: [],
    confirmationPrompt: '',
    fulfillmentMessage: 'Transferring you to a 311 operator now. Please hold.',
  },

  // ── 22. EMERGENCY REDIRECT ────────────────────────────────────────────────────
  {
    name: 'RedirectToEmergencyServices',
    displayName: 'Redirect to 911',
    description: 'Caller describes an active emergency — redirect immediately to 911',
    category: 'SERVICE_REQUEST_STATUS',
    primaryDepartment: 'ESCALATE_911',
    priorityLevel: 'ESCALATE_911',
    requiresDisambiguation: false,
    escalationKeywords: ['fire', 'shooting', 'stabbing', 'someone is dying', 'help me', 'heart attack', 'emergency', 'accident', 'crash'],
    sampleUtterances: [
      'This is an emergency',
      'I need 911',
      'There is a fire',
      'Someone was shot',
      'There is a car accident',
      'Someone is not breathing',
      'There is a fight and someone has a knife',
      'Call 911',
      'I need police right now',
      'Help me',
      'There is a medical emergency',
    ],
    slots: [],
    confirmationPrompt: '',
    fulfillmentMessage: 'This sounds like an emergency. Please hang up and dial 9-1-1 immediately. If you cannot call, stay on the line and we will transfer you now.',
  },

].map((intent): IntentDefinition => ({
  ...intent,
  sampleUtterances: mergeUtterances(intent.sampleUtterances, EXHAUSTIVE_UTTERANCES[intent.name]),
}));

export const INTENT_MAP: Record<string, IntentDefinition> =
  Object.fromEntries(INTENTS.map(i => [i.name, i]));
