/** Generated from connect/lex-bot-complete-spec.md — both locales live in infra/lex/bot-spec.json. */

export const UTTERANCES_911 = {
  "EmergencyEscalation": [
    "someone is shooting",
    "there's a shooter",
    "shots fired",
    "active shooter",
    "he has a gun",
    "she has a gun",
    "they have a gun",
    "there's a gun",
    "he's pointing a gun at me",
    "help me",
    "I need help right now",
    "there's a stabbing",
    "he stabbed someone",
    "she's not breathing",
    "he's not breathing",
    "someone is unconscious",
    "there's a fire",
    "call 911",
    "this is an emergency",
    "send police right now",
    "there's a dead body",
    "someone is being attacked",
    "they're trying to kill me",
    "I'm being robbed right now",
    "he's going to hurt me",
    "domestic violence happening right now",
    "he's hitting her",
    "someone is drowning",
    "there's been an explosion",
    "I can smell gas",
    "gas leak",
    "she just collapsed",
    "he just collapsed",
    "they're breaking in right now",
    "someone is breaking into my house",
    "home invasion",
    "car crash with injuries",
    "the car is on fire",
    "I need an ambulance right now",
    "medical emergency",
    "heart attack",
    "someone is having a seizure",
    "I think he has a weapon",
    "she threatened to kill me",
    "he threatened to shoot",
    "they have a knife"
  ],
  "RequestHuman": [
    "let me talk to someone",
    "I want to speak to an officer",
    "can I talk to a real person",
    "transfer me to a dispatcher",
    "I need a dispatcher",
    "give me a human",
    "I don't want to talk to a machine",
    "I need to talk to someone",
    "can you transfer me",
    "connect me to dispatch",
    "operator",
    "talk to someone real",
    "I'd rather talk to a person"
  ],
  "NoiseComplaint": [
    "my neighbor is being too loud",
    "there's too much noise",
    "noise complaint",
    "it's really loud outside",
    "there's a loud party",
    "my neighbor won't turn down the music",
    "someone is playing loud music",
    "there's a party going on",
    "people are being loud",
    "there's a loud gathering",
    "someone is making a lot of noise",
    "neighbors are loud",
    "the music is too loud",
    "the bass is shaking my walls",
    "people are yelling outside",
    "there's screaming outside",
    "they've been loud for hours",
    "this has been going on all night",
    "fireworks in the neighborhood",
    "someone is setting off fireworks",
    "loud engine running outside",
    "car alarm going off",
    "dog won't stop barking",
    "there's a dog barking constantly",
    "there's noise outside my apartment",
    "loud motorcycle"
  ],
  "SuspiciousPerson": [
    "there's a suspicious person",
    "someone looks suspicious",
    "there's a guy acting weird",
    "there's a strange person",
    "someone is lurking",
    "suspicious male",
    "suspicious female",
    "there's someone walking around looking in cars",
    "a person is peering into windows",
    "someone is casing houses",
    "there's a man watching kids",
    "suspicious activity",
    "someone doesn't belong here",
    "there's a person who looks out of place",
    "someone is hanging around",
    "someone is just sitting there watching",
    "there's a sketchy person",
    "person acting strangely",
    "someone is following me",
    "I think someone is following my car",
    "there's a person I don't recognize acting oddly",
    "someone is trying to break into a car",
    "person looks like they're on drugs",
    "someone is wandering around confused",
    "there's a man yelling at people",
    "a person is making people uncomfortable"
  ],
  "AbandonedVehicle": [
    "there's an abandoned car",
    "abandoned vehicle",
    "a car has been sitting here for days",
    "this car hasn't moved in a week",
    "there's a car that's been parked here forever",
    "I want to report an abandoned vehicle",
    "there's a car with no plates",
    "a car has flat tires and looks abandoned",
    "someone left their car here",
    "there's a car that's been here for over 24 hours",
    "abandoned truck",
    "abandoned motorcycle",
    "this vehicle looks like nobody owns it",
    "car has been here for three days",
    "junk car sitting on the street",
    "can you tow this abandoned car"
  ],
  "VehicleBurglary": [
    "someone broke into my car",
    "my car was broken into",
    "car break-in",
    "my window was smashed",
    "someone smashed my car window",
    "stuff was stolen from my car",
    "my car was burglarized",
    "items were taken from my vehicle",
    "someone went through my car",
    "my car got broken into last night",
    "car burglary",
    "theft from vehicle",
    "they broke my car window",
    "my car was vandalized and stuff was taken",
    "someone stole things from my car",
    "my radio was stolen",
    "my laptop was stolen from my car",
    "my car was ransacked"
  ],
  "TheftReport": [
    "I want to report a theft",
    "someone stole from me",
    "I was robbed",
    "my property was stolen",
    "someone stole my package",
    "package was stolen from my porch",
    "porch pirate",
    "someone took my bike",
    "my bicycle was stolen",
    "shoplifting",
    "someone shoplifted from my store",
    "employee theft",
    "theft at a business",
    "my purse was snatched",
    "my wallet was stolen",
    "something was taken from me",
    "I'd like to file a theft report",
    "can I report stolen property",
    "someone took my phone",
    "my phone was stolen",
    "theft of services"
  ],
  "ParkingComplaint": [
    "there's a parking violation",
    "someone is illegally parked",
    "car parked in a handicap spot without a placard",
    "blocking my driveway",
    "someone is blocking the fire hydrant",
    "car is double parked",
    "someone parked in a no parking zone",
    "parking complaint",
    "illegally parked vehicle",
    "car blocking the alley",
    "someone parked in a fire lane",
    "car parked on the sidewalk",
    "they parked on my lawn",
    "someone keeps parking in my spot",
    "car blocking my mailbox",
    "wrong way parking",
    "expired tags parked on street"
  ],
  "WelfareCheck": [
    "I need a welfare check",
    "can you check on someone",
    "I'm worried about my neighbor",
    "I haven't seen my neighbor in days",
    "I'm concerned about someone",
    "can you send someone to check on a person",
    "welfare check on my elderly neighbor",
    "I think someone might be in trouble",
    "I can't get in touch with my family member",
    "my friend isn't answering the door",
    "can someone go check on my roommate",
    "I'm worried something happened to someone",
    "my elderly parent isn't answering",
    "haven't heard from my friend",
    "someone isn't responding",
    "I need someone checked on",
    "can you do a wellness check",
    "check on elderly person",
    "check on my mom",
    "check on my dad"
  ],
  "AnimalComplaint": [
    "there's an animal complaint",
    "stray dog",
    "loose dog",
    "aggressive dog",
    "dog attacked me",
    "dog bit someone",
    "vicious dog",
    "dog running loose",
    "dog off leash",
    "there's a dog in the road",
    "animal cruelty",
    "someone is hurting an animal",
    "neglected animal",
    "dog left in a hot car",
    "stray cat",
    "injured animal",
    "there's a raccoon in my house",
    "animal in my yard",
    "coyote sighting",
    "stray animal"
  ],
  "TowComplaint": [
    "I need a tow complaint",
    "my car was towed illegally",
    "my car was towed without notice",
    "they towed my car",
    "I want to report an illegal tow",
    "my vehicle was towed and I don't know why",
    "my car was towed from private property",
    "tow truck scam",
    "I think my car was towed wrongfully",
    "towing complaint",
    "predatory towing",
    "my car was booted",
    "someone put a boot on my car"
  ],
  "VandalismDamage": [
    "vandalism",
    "someone vandalized my property",
    "graffiti",
    "someone tagged my building",
    "my fence was damaged",
    "someone keyed my car",
    "my car was keyed",
    "someone broke my window",
    "property damage",
    "someone spray painted my wall",
    "they broke my mailbox",
    "someone smashed my sign",
    "damage to my property",
    "eggs on my car",
    "someone threw rocks through my window",
    "my fence was knocked over"
  ],
  "CodeEnforcementComplaint": [
    "code enforcement complaint",
    "property violation",
    "there's trash piled up at a house",
    "overgrown grass",
    "high grass",
    "tall weeds",
    "junk cars in the yard",
    "abandoned property",
    "condemned building",
    "illegal business operating",
    "someone is running a business out of their house",
    "illegal construction",
    "building without a permit",
    "health hazard",
    "property is a mess",
    "nuisance property"
  ],
  "PublicWorksIssue": [
    "public works issue",
    "water main break",
    "water is flooding the street",
    "the street is flooded",
    "pothole",
    "there's a big pothole",
    "streetlight is out",
    "the stoplight is broken",
    "the traffic light isn't working",
    "water leak in the street",
    "sewer backup",
    "manhole cover is missing",
    "road is damaged",
    "sign is knocked down",
    "tree fell in the road",
    "there's a sinkhole",
    "a pipe burst",
    "water coming up from the street",
    "water is gushing from the ground",
    "the street caved in"
  ],
  "TrafficAccidentReportOnly": [
    "I was in an accident",
    "fender bender",
    "minor car accident",
    "I need to file an accident report",
    "hit and run",
    "someone hit my car and drove off",
    "my parked car was hit",
    "someone backed into my car",
    "car accident to report",
    "accident with no injuries",
    "car crash no one was hurt",
    "accident report",
    "I need a report number for insurance",
    "vehicle accident report"
  ],
  "OnlineReportEligibility": [
    "can I file a report online",
    "where can I file a report",
    "how do I report something online",
    "can I do this on the website",
    "I want to file a report online",
    "can I fill out a report myself",
    "do I need to talk to someone or can I do it online",
    "where do I report vandalism online",
    "can this be done online",
    "I'd rather file this online",
    "how do I make a report without calling"
  ],
  "RepeatCallCheck": [
    "I already called about this",
    "I called earlier",
    "I reported this already",
    "I've been calling for hours",
    "no one came",
    "I called last night",
    "I made a report but nothing happened",
    "I called and no one showed up",
    "I was told someone would come",
    "following up on my earlier call",
    "I have a reference number",
    "checking on my report"
  ],
  "InformationRequest": [
    "I have a question",
    "I need information",
    "where is the police station",
    "what are the police station hours",
    "how do I get a police report copy",
    "how do I get a copy of an incident report",
    "how do I contest a parking ticket",
    "how do I get a restraining order",
    "how do I file a complaint against an officer",
    "what's the non-emergency number",
    "can I get a fingerprint done",
    "sex offender registry",
    "how do I register my alarm",
    "are there sex offenders in my area",
    "who do I call for noise complaints",
    "how do I get a gun permit"
  ],
  "Welcome": [
    "hello",
    "hi",
    "yes",
    "i need help",
    "i need to report something",
    "i have a question",
    "i want to report",
    "can i get some help",
    "i have a non-emergency",
    "i need to make a report",
    "i want to file a report"
  ]
} as const;

export const UTTERANCES_911_ES = {
  "EmergencyEscalation": [
    "hay un tiroteo",
    "alguien está disparando",
    "disparos",
    "hay una pistola",
    "él tiene un arma",
    "me está atacando",
    "ayuda",
    "necesito ayuda ahora",
    "hay un incendio",
    "alguien está inconsciente",
    "no está respirando",
    "llamen al novecientos once",
    "es una emergencia",
    "hay un cuerpo",
    "me están robando",
    "violencia doméstica",
    "me está golpeando",
    "se está ahogando",
    "huele a gas",
    "accidente con heridos",
    "infarto",
    "está convulsionando",
    "me amenazó con matarme",
    "tiene un cuchillo"
  ],
  "RequestHuman": [
    "quiero hablar con alguien",
    "pásame con una persona",
    "quiero hablar con un oficial",
    "necesito un despachador",
    "transfiérame",
    "con una persona real",
    "no quiero hablar con una máquina"
  ],
  "NoiseComplaint": [
    "mis vecinos hacen mucho ruido",
    "hay una fiesta muy ruidosa",
    "queja de ruido",
    "la música está muy alta",
    "están haciendo mucho escándalo",
    "hay gritos afuera",
    "la fiesta sigue y no para",
    "los vecinos tienen el estéreo muy alto",
    "el perro no deja de ladrar",
    "hay cohetes en el vecindario",
    "alguien tiene el carro con la música muy fuerte"
  ],
  "SuspiciousPerson": [
    "hay una persona sospechosa",
    "alguien actúa de manera extraña",
    "hay un hombre mirando por las ventanas",
    "una persona sospechosa merodeando",
    "alguien que no pertenece aquí",
    "hay alguien muy raro afuera",
    "me están siguiendo",
    "un hombre está siguiendo a los niños",
    "alguien está viendo los carros",
    "comportamiento sospechoso",
    "hay alguien acechando"
  ],
  "AbandonedVehicle": [
    "hay un carro abandonado",
    "quiero reportar un vehículo abandonado",
    "un carro lleva días aquí",
    "este carro no se ha movido",
    "hay un carro sin placas",
    "alguien dejó su carro aquí",
    "un carro abandonado en la calle"
  ],
  "VehicleBurglary": [
    "rompieron el vidrio de mi carro",
    "me entraron al carro",
    "me robaron cosas del carro",
    "mi carro fue robado",
    "alguien abrió mi carro",
    "me rompieron la ventana del carro",
    "me robaron del carro",
    "entraron a mi vehículo"
  ],
  "TheftReport": [
    "quiero reportar un robo",
    "me robaron",
    "alguien me robó",
    "me robaron el paquete",
    "me robaron la bicicleta",
    "robo en una tienda",
    "alguien me robó la bolsa",
    "me robaron el teléfono",
    "me robaron la cartera",
    "quiero hacer un reporte de robo"
  ],
  "ParkingComplaint": [
    "un carro estacionado ilegalmente",
    "están bloqueando mi entrada",
    "un carro en zona de no estacionamiento",
    "queja de estacionamiento",
    "carro bloqueando la salida de incendio",
    "están estacionados en el pavimento",
    "alguien se estacionó en mi espacio",
    "carro bloqueando el hidrante",
    "estacionado en zona de discapacitados sin placa"
  ],
  "WelfareCheck": [
    "quiero un chequeo de bienestar",
    "estoy preocupado por mi vecino",
    "no he visto a mi vecino en días",
    "no contesta la puerta",
    "quiero que vayan a ver a alguien",
    "estoy preocupado por un familiar",
    "chequeo de bienestar para persona mayor",
    "mi mamá no contesta",
    "no he sabido nada de mi amigo"
  ],
  "AnimalComplaint": [
    "hay un perro suelto",
    "perro agresivo",
    "el perro me mordió",
    "alguien lastima a un animal",
    "animal callejero",
    "crueldad animal",
    "animal en la calle",
    "coyote suelto",
    "un animal abandonado",
    "gato callejero",
    "perro en el carro caliente"
  ],
  "TowComplaint": [
    "me grúaron el carro",
    "se llevaron mi carro sin aviso",
    "queja de grúa",
    "me grúaron ilegalmente",
    "pusieron una bota en mi carro"
  ],
  "VandalismDamage": [
    "vandalismo",
    "pintaron grafiti en mi propiedad",
    "dañaron mi propiedad",
    "le rayaron mi carro",
    "rompieron mi ventana",
    "tiraron huevos a mi carro",
    "me rompieron el buzón",
    "pintaron mi barda",
    "daños a la propiedad"
  ],
  "CodeEnforcementComplaint": [
    "queja de código de construcción",
    "hay basura acumulada en una casa",
    "pasto muy alto",
    "carros en el patio",
    "propiedad abandonada",
    "negocio ilegal en casa",
    "construcción sin permiso"
  ],
  "PublicWorksIssue": [
    "problema de obras públicas",
    "se rompió una tubería",
    "hay agua en la calle",
    "el semáforo no funciona",
    "la luz de la calle está apagada",
    "hay un hoyo en el camino",
    "drenaje bloqueado",
    "se cayó un árbol en la calle",
    "la coladera no tiene tapa",
    "está saliendo agua del suelo"
  ],
  "TrafficAccidentReportOnly": [
    "estuve en un accidente",
    "choque menor",
    "me golpearon el carro y se fueron",
    "necesito un reporte de accidente",
    "choque y fuga",
    "alguien me golpeó el carro estacionado",
    "accidente sin heridos",
    "necesito el número de reporte para el seguro"
  ],
  "OnlineReportEligibility": [
    "¿puedo hacer un reporte en línea?",
    "¿dónde puedo reportar esto?",
    "¿puedo hacerlo en el sitio web?",
    "quiero hacer un reporte por internet",
    "¿cómo hago un reporte sin llamar?"
  ],
  "RepeatCallCheck": [
    "ya llamé antes sobre esto",
    "llamé más temprano",
    "ya reporté esto",
    "nadie llegó",
    "llamé anoche",
    "tengo un número de referencia",
    "quiero saber qué pasó con mi reporte",
    "nadie vino"
  ],
  "InformationRequest": [
    "tengo una pregunta",
    "necesito información",
    "¿dónde está la estación de policía?",
    "¿cuáles son las horas de la estación?",
    "¿cómo obtengo una copia del reporte?",
    "¿cómo contesto una multa de estacionamiento?",
    "¿cómo solicito una orden de restricción?",
    "número de teléfono no emergencias",
    "¿cómo registro mi alarma?",
    "¿cómo obtengo un permiso de arma?"
  ],
  "Welcome": [
    "hola",
    "sí",
    "necesito ayuda",
    "necesito reportar algo",
    "quiero reportar",
    "puedo recibir ayuda",
    "tengo una llamada que no es de emergencia",
    "necesito hacer un reporte",
    "quiero presentar un reporte"
  ]
} as const;
