/** Training utterances for venue Lex intents (also declared in stack-lex.yaml). */
export const UTTERANCES_VENUE = {
  MedicalAssistance: [
    "someone needs medical help",
    "person collapsed",
    "medical emergency at section",
    "unresponsive person",
    "guest passed out in the concourse",
    "someone is having chest pain",
    "person fainted in the stands",
    "need a medic at my section",
    "guest is bleeding",
    "someone can't breathe near gate",
    "heat exhaustion in the crowd",
  ],
  SecurityIncident: [
    "fight in section",
    "someone is being aggressive",
    "security needed",
    "threatening behavior",
    "two people are fighting in the aisle",
    "guest is harassing others",
    "someone flashed a weapon",
    "crowd is getting out of control",
    "person won't leave after being asked",
    "threatening language toward staff",
    "security to section please",
  ],
  LostPerson: [
    "I lost my child",
    "missing person",
    "can't find my kid",
    "lost child in section",
    "my child wandered off",
    "I can't find my daughter",
    "lost my son near the restrooms",
    "separated from my family",
    "missing child wearing a blue shirt",
    "my kid got lost in the crowd",
    "help finding a lost adult with dementia",
  ],
} as const;
