/** Rapid IQ jurisdiction registry — RC-global (no agencyId). Seed source for DynamoDB. */

import { UNIVERSITY_JURISDICTIONS } from "./university-registry.js";

export type ScanTier = 0 | 1 | 2 | 3;

export type JurisdictionType =
  | "county"
  | "city"
  | "university"
  | "university_system"
  | "state_agency";

export interface Jurisdiction {
  jurisdictionId: string;
  type: JurisdictionType;
  name: string;
  stateCode: string;
  stateName: string;
  population: number;
  tier: ScanTier;
  tierWeight: number;
  intervalHours: number;
  agendaBaseUrl: string;
  agendaPathHints: string[];
  lastScannedAt: string;
  lastSignalAt: string | null;
  totalSignalsFound: number;
  isActive: boolean;
  priorityBoost: number;
  notes: string | null;
}

export interface StateCoverage {
  stateCode: string;
  stateName: string;
  lastScannedAt: string | null;
  lastSignalAt: string | null;
  totalSignals: number;
  jurisdictionCount: number;
}

export type JurisdictionSeed = Omit<
  Jurisdiction,
  "lastScannedAt" | "lastSignalAt" | "totalSignalsFound" | "priorityBoost"
>;

export const ALL_JURISDICTIONS: JurisdictionSeed[] = [
  {
    jurisdictionId: "county#CA#los-angeles",
    type: "county",
    name: "Los Angeles County",
    stateCode: "CA",
    stateName: "California",
    population: 10014009,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.bos.lacounty.gov",
    agendaPathHints: ["/board/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#TX#harris",
    type: "county",
    name: "Harris County",
    stateCode: "TX",
    stateName: "Texas",
    population: 4731145,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.harriscountytx.gov",
    agendaPathHints: ["/commissioners-court", "/agendas"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#IL#cook",
    type: "county",
    name: "Cook County",
    stateCode: "IL",
    stateName: "Illinois",
    population: 5275541,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.cookcountyil.gov",
    agendaPathHints: ["/government/board", "/agendas"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#AZ#maricopa",
    type: "county",
    name: "Maricopa County",
    stateCode: "AZ",
    stateName: "Arizona",
    population: 4490868,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.maricopa.gov",
    agendaPathHints: ["/board/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#NY#new-york-city",
    type: "city",
    name: "New York City",
    stateCode: "NY",
    stateName: "New York",
    population: 8336817,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.nyc.gov",
    agendaPathHints: ["/meetings", "/agendas"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#FL#miami-dade",
    type: "county",
    name: "Miami-Dade County",
    stateCode: "FL",
    stateName: "Florida",
    population: 2701140,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.miamidade.gov",
    agendaPathHints: ["/meetings", "/agendas"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#GA#fulton",
    type: "county",
    name: "Fulton County",
    stateCode: "GA",
    stateName: "Georgia",
    population: 1066710,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.fultoncountyga.gov",
    agendaPathHints: ["/commissioners/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#WA#king",
    type: "county",
    name: "King County",
    stateCode: "WA",
    stateName: "Washington",
    population: 2269675,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://kingcounty.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#PA#philadelphia",
    type: "city",
    name: "Philadelphia",
    stateCode: "PA",
    stateName: "Pennsylvania",
    population: 1603797,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.phila.gov",
    agendaPathHints: ["/council", "/agendas"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#TX#dallas",
    type: "county",
    name: "Dallas County",
    stateCode: "TX",
    stateName: "Texas",
    population: 2613539,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.dallascounty.org",
    agendaPathHints: ["/commissioners-court", "/agendas"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#AL#montgomery",
    type: "county",
    name: "Montgomery County",
    stateCode: "AL",
    stateName: "Alabama",
    population: 228954,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.montgomeryal.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#AL#montgomery",
    type: "city",
    name: "Montgomery",
    stateCode: "AL",
    stateName: "Alabama",
    population: 76318,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.montgomeryal.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#AK#juneau",
    type: "county",
    name: "City and Borough of Juneau",
    stateCode: "AK",
    stateName: "Alaska",
    population: 32255,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.juneau.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#AK#juneau",
    type: "city",
    name: "Juneau",
    stateCode: "AK",
    stateName: "Alaska",
    population: 10751,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.juneau.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#AZ#phoenix",
    type: "city",
    name: "Phoenix",
    stateCode: "AZ",
    stateName: "Arizona",
    population: 1496956,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.maricopa.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#AR#pulaski",
    type: "county",
    name: "Pulaski County",
    stateCode: "AR",
    stateName: "Arkansas",
    population: 399125,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.pulaskicounty.net",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#AR#little-rock",
    type: "city",
    name: "Little Rock",
    stateCode: "AR",
    stateName: "Arkansas",
    population: 133041,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.pulaskicounty.net",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#CA#sacramento",
    type: "county",
    name: "Sacramento County",
    stateCode: "CA",
    stateName: "California",
    population: 1588921,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.saccounty.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#CA#sacramento",
    type: "city",
    name: "Sacramento",
    stateCode: "CA",
    stateName: "California",
    population: 529640,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.saccounty.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#CO#denver",
    type: "county",
    name: "City and County of Denver",
    stateCode: "CO",
    stateName: "Colorado",
    population: 715522,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.denvergov.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#CO#denver",
    type: "city",
    name: "Denver",
    stateCode: "CO",
    stateName: "Colorado",
    population: 238507,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.denvergov.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#CT#hartford",
    type: "county",
    name: "Hartford County",
    stateCode: "CT",
    stateName: "Connecticut",
    population: 899498,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.hartford.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#CT#hartford",
    type: "city",
    name: "Hartford",
    stateCode: "CT",
    stateName: "Connecticut",
    population: 299832,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.hartford.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#DE#kent",
    type: "county",
    name: "Kent County",
    stateCode: "DE",
    stateName: "Delaware",
    population: 186383,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.co.kent.de.us",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#DE#dover",
    type: "city",
    name: "Dover",
    stateCode: "DE",
    stateName: "Delaware",
    population: 62127,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.co.kent.de.us",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#FL#leon",
    type: "county",
    name: "Leon County",
    stateCode: "FL",
    stateName: "Florida",
    population: 293582,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.leoncountyfl.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#FL#tallahassee",
    type: "city",
    name: "Tallahassee",
    stateCode: "FL",
    stateName: "Florida",
    population: 97860,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.leoncountyfl.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#GA#atlanta",
    type: "city",
    name: "Atlanta",
    stateCode: "GA",
    stateName: "Georgia",
    population: 355570,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.fultoncountyga.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#HI#honolulu",
    type: "county",
    name: "City and County of Honolulu",
    stateCode: "HI",
    stateName: "Hawaii",
    population: 1016508,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.honolulu.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#HI#honolulu",
    type: "city",
    name: "Honolulu",
    stateCode: "HI",
    stateName: "Hawaii",
    population: 338836,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.honolulu.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#ID#ada",
    type: "county",
    name: "Ada County",
    stateCode: "ID",
    stateName: "Idaho",
    population: 511931,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://adacounty.id.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#ID#boise",
    type: "city",
    name: "Boise",
    stateCode: "ID",
    stateName: "Idaho",
    population: 170643,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://adacounty.id.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#IL#sangamon",
    type: "county",
    name: "Sangamon County",
    stateCode: "IL",
    stateName: "Illinois",
    population: 196343,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.sangamonil.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#IL#springfield",
    type: "city",
    name: "Springfield",
    stateCode: "IL",
    stateName: "Illinois",
    population: 65447,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.sangamonil.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#IN#marion",
    type: "county",
    name: "Marion County",
    stateCode: "IN",
    stateName: "Indiana",
    population: 971102,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.indy.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#IN#indianapolis",
    type: "city",
    name: "Indianapolis",
    stateCode: "IN",
    stateName: "Indiana",
    population: 323700,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.indy.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#IA#polk",
    type: "county",
    name: "Polk County",
    stateCode: "IA",
    stateName: "Iowa",
    population: 492401,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.polkcountyiowa.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#IA#des-moines",
    type: "city",
    name: "Des Moines",
    stateCode: "IA",
    stateName: "Iowa",
    population: 164133,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.polkcountyiowa.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#KS#shawnee",
    type: "county",
    name: "Shawnee County",
    stateCode: "KS",
    stateName: "Kansas",
    population: 178909,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.snco.us",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#KS#topeka",
    type: "city",
    name: "Topeka",
    stateCode: "KS",
    stateName: "Kansas",
    population: 59636,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.snco.us",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#KY#franklin",
    type: "county",
    name: "Franklin County",
    stateCode: "KY",
    stateName: "Kentucky",
    population: 51544,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.frankfort.ky.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#KY#frankfort",
    type: "city",
    name: "Frankfort",
    stateCode: "KY",
    stateName: "Kentucky",
    population: 17181,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.frankfort.ky.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#LA#east-baton-rouge",
    type: "county",
    name: "East Baton Rouge Parish",
    stateCode: "LA",
    stateName: "Louisiana",
    population: 456781,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.brla.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#LA#baton-rouge",
    type: "city",
    name: "Baton Rouge",
    stateCode: "LA",
    stateName: "Louisiana",
    population: 152260,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.brla.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#ME#kennebec",
    type: "county",
    name: "Kennebec County",
    stateCode: "ME",
    stateName: "Maine",
    population: 123642,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.kennebecounty.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#ME#augusta",
    type: "city",
    name: "Augusta",
    stateCode: "ME",
    stateName: "Maine",
    population: 41214,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.kennebecounty.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#MD#anne-arundel",
    type: "county",
    name: "Anne Arundel County",
    stateCode: "MD",
    stateName: "Maryland",
    population: 590336,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.aacounty.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#MD#annapolis",
    type: "city",
    name: "Annapolis",
    stateCode: "MD",
    stateName: "Maryland",
    population: 196778,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.aacounty.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#MA#suffolk",
    type: "county",
    name: "Suffolk County",
    stateCode: "MA",
    stateName: "Massachusetts",
    population: 797936,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.boston.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#MA#boston",
    type: "city",
    name: "Boston",
    stateCode: "MA",
    stateName: "Massachusetts",
    population: 265978,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.boston.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#MI#ingham",
    type: "county",
    name: "Ingham County",
    stateCode: "MI",
    stateName: "Michigan",
    population: 284898,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.ingham.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#MI#lansing",
    type: "city",
    name: "Lansing",
    stateCode: "MI",
    stateName: "Michigan",
    population: 94966,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.ingham.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#MN#ramsey",
    type: "county",
    name: "Ramsey County",
    stateCode: "MN",
    stateName: "Minnesota",
    population: 552352,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.ramseycounty.us",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#MN#saint-paul",
    type: "city",
    name: "Saint Paul",
    stateCode: "MN",
    stateName: "Minnesota",
    population: 184117,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.ramseycounty.us",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#MS#hinds",
    type: "county",
    name: "Hinds County",
    stateCode: "MS",
    stateName: "Mississippi",
    population: 227742,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.hindscountyms.com",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#MS#jackson",
    type: "city",
    name: "Jackson",
    stateCode: "MS",
    stateName: "Mississippi",
    population: 75914,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.hindscountyms.com",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#MO#cole",
    type: "county",
    name: "Cole County",
    stateCode: "MO",
    stateName: "Missouri",
    population: 77358,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.colecounty.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#MO#jefferson-city",
    type: "city",
    name: "Jefferson City",
    stateCode: "MO",
    stateName: "Missouri",
    population: 25786,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.colecounty.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#MT#lewis-and-clark",
    type: "county",
    name: "Lewis and Clark County",
    stateCode: "MT",
    stateName: "Montana",
    population: 73495,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.lccountymt.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#MT#helena",
    type: "city",
    name: "Helena",
    stateCode: "MT",
    stateName: "Montana",
    population: 24498,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.lccountymt.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#NE#lancaster",
    type: "county",
    name: "Lancaster County",
    stateCode: "NE",
    stateName: "Nebraska",
    population: 322608,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.lancaster.ne.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#NE#lincoln",
    type: "city",
    name: "Lincoln",
    stateCode: "NE",
    stateName: "Nebraska",
    population: 107536,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.lancaster.ne.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#NV#carson-city",
    type: "county",
    name: "Carson City",
    stateCode: "NV",
    stateName: "Nevada",
    population: 58639,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.carson.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#NV#carson-city",
    type: "city",
    name: "Carson City",
    stateCode: "NV",
    stateName: "Nevada",
    population: 19546,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.carson.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#NH#merrimack",
    type: "county",
    name: "Merrimack County",
    stateCode: "NH",
    stateName: "New Hampshire",
    population: 156078,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.merrimackcounty.net",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#NH#concord",
    type: "city",
    name: "Concord",
    stateCode: "NH",
    stateName: "New Hampshire",
    population: 52026,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.merrimackcounty.net",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#NJ#mercer",
    type: "county",
    name: "Mercer County",
    stateCode: "NJ",
    stateName: "New Jersey",
    population: 387340,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.mercercounty.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#NJ#trenton",
    type: "city",
    name: "Trenton",
    stateCode: "NJ",
    stateName: "New Jersey",
    population: 129113,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.mercercounty.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#NM#santa-fe",
    type: "county",
    name: "Santa Fe County",
    stateCode: "NM",
    stateName: "New Mexico",
    population: 154823,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.santafecountynm.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#NM#santa-fe",
    type: "city",
    name: "Santa Fe",
    stateCode: "NM",
    stateName: "New Mexico",
    population: 51607,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.santafecountynm.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#NY#albany",
    type: "county",
    name: "Albany County",
    stateCode: "NY",
    stateName: "New York",
    population: 314848,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.albanycounty.com",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#NY#albany",
    type: "city",
    name: "Albany",
    stateCode: "NY",
    stateName: "New York",
    population: 104949,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.albanycounty.com",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#NC#wake",
    type: "county",
    name: "Wake County",
    stateCode: "NC",
    stateName: "North Carolina",
    population: 1175111,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.wakegov.com",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#NC#raleigh",
    type: "city",
    name: "Raleigh",
    stateCode: "NC",
    stateName: "North Carolina",
    population: 391703,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.wakegov.com",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#ND#burleigh",
    type: "county",
    name: "Burleigh County",
    stateCode: "ND",
    stateName: "North Dakota",
    population: 98598,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.burleighco.com",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#ND#bismarck",
    type: "city",
    name: "Bismarck",
    stateCode: "ND",
    stateName: "North Dakota",
    population: 32866,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.burleighco.com",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#OH#franklin",
    type: "county",
    name: "Franklin County",
    stateCode: "OH",
    stateName: "Ohio",
    population: 1323807,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.franklincountyohio.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#OH#columbus",
    type: "city",
    name: "Columbus",
    stateCode: "OH",
    stateName: "Ohio",
    population: 441269,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.franklincountyohio.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#OK#oklahoma",
    type: "county",
    name: "Oklahoma County",
    stateCode: "OK",
    stateName: "Oklahoma",
    population: 796292,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.oklahomacounty.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#OK#oklahoma-city",
    type: "city",
    name: "Oklahoma City",
    stateCode: "OK",
    stateName: "Oklahoma",
    population: 265430,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.oklahomacounty.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#OR#marion",
    type: "county",
    name: "Marion County",
    stateCode: "OR",
    stateName: "Oregon",
    population: 345920,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.co.marion.or.us",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#OR#salem",
    type: "city",
    name: "Salem",
    stateCode: "OR",
    stateName: "Oregon",
    population: 115306,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.co.marion.or.us",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#PA#dauphin",
    type: "county",
    name: "Dauphin County",
    stateCode: "PA",
    stateName: "Pennsylvania",
    population: 288590,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.dauphincounty.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#PA#harrisburg",
    type: "city",
    name: "Harrisburg",
    stateCode: "PA",
    stateName: "Pennsylvania",
    population: 96196,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.dauphincounty.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#RI#providence",
    type: "county",
    name: "Providence County",
    stateCode: "RI",
    stateName: "Rhode Island",
    population: 660741,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.providenceri.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#RI#providence",
    type: "city",
    name: "Providence",
    stateCode: "RI",
    stateName: "Rhode Island",
    population: 220247,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.providenceri.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#SC#richland",
    type: "county",
    name: "Richland County",
    stateCode: "SC",
    stateName: "South Carolina",
    population: 416147,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.richlandcountysc.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#SC#columbia",
    type: "city",
    name: "Columbia",
    stateCode: "SC",
    stateName: "South Carolina",
    population: 138715,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.richlandcountysc.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#SD#hughes",
    type: "county",
    name: "Hughes County",
    stateCode: "SD",
    stateName: "South Dakota",
    population: 17765,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.hughescounty.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#SD#pierre",
    type: "city",
    name: "Pierre",
    stateCode: "SD",
    stateName: "South Dakota",
    population: 10000,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.hughescounty.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#TN#davidson",
    type: "county",
    name: "Davidson County",
    stateCode: "TN",
    stateName: "Tennessee",
    population: 715884,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.nashville.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#TN#nashville",
    type: "city",
    name: "Nashville",
    stateCode: "TN",
    stateName: "Tennessee",
    population: 238628,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.nashville.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#TX#travis",
    type: "county",
    name: "Travis County",
    stateCode: "TX",
    stateName: "Texas",
    population: 1290188,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.traviscountytx.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#TX#austin",
    type: "city",
    name: "Austin",
    stateCode: "TX",
    stateName: "Texas",
    population: 430062,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.traviscountytx.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#UT#salt-lake",
    type: "county",
    name: "Salt Lake County",
    stateCode: "UT",
    stateName: "Utah",
    population: 1186441,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://slco.org",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#UT#salt-lake-city",
    type: "city",
    name: "Salt Lake City",
    stateCode: "UT",
    stateName: "Utah",
    population: 395480,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://slco.org",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#VT#washington",
    type: "county",
    name: "Washington County",
    stateCode: "VT",
    stateName: "Vermont",
    population: 59807,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.washingtoncountyvt.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#VT#montpelier",
    type: "city",
    name: "Montpelier",
    stateCode: "VT",
    stateName: "Vermont",
    population: 19935,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.washingtoncountyvt.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#VA#richmond-city",
    type: "county",
    name: "City of Richmond",
    stateCode: "VA",
    stateName: "Virginia",
    population: 226610,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.rva.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#VA#richmond",
    type: "city",
    name: "Richmond",
    stateCode: "VA",
    stateName: "Virginia",
    population: 75536,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.rva.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#WA#thurston",
    type: "county",
    name: "Thurston County",
    stateCode: "WA",
    stateName: "Washington",
    population: 298758,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.thurstoncountywa.gov",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#WA#olympia",
    type: "city",
    name: "Olympia",
    stateCode: "WA",
    stateName: "Washington",
    population: 99586,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.thurstoncountywa.gov",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#WV#kanawha",
    type: "county",
    name: "Kanawha County",
    stateCode: "WV",
    stateName: "West Virginia",
    population: 180745,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.kanawha.us",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#WV#charleston",
    type: "city",
    name: "Charleston",
    stateCode: "WV",
    stateName: "West Virginia",
    population: 60248,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.kanawha.us",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#WI#dane",
    type: "county",
    name: "Dane County",
    stateCode: "WI",
    stateName: "Wisconsin",
    population: 561504,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.countyofdane.com",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#WI#madison",
    type: "city",
    name: "Madison",
    stateCode: "WI",
    stateName: "Wisconsin",
    population: 187168,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.countyofdane.com",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#WY#laramie",
    type: "county",
    name: "Laramie County",
    stateCode: "WY",
    stateName: "Wyoming",
    population: 100512,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.laramiecounty.com",
    agendaPathHints: ["/government/agendas", "/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "city#WY#cheyenne",
    type: "city",
    name: "Cheyenne",
    stateCode: "WY",
    stateName: "Wyoming",
    population: 33504,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://www.laramiecounty.com",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#GA#muscogee",
    type: "county",
    name: "Muscogee County",
    stateCode: "GA",
    stateName: "Georgia",
    population: 206922,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.columbusga.gov",
    agendaPathHints: ["/government/council/agendas", "/meetings"],
    isActive: true,
    notes: "Columbus GA \u2014 RC HQ market",
  },
  {
    jurisdictionId: "county#FL#desoto",
    type: "county",
    name: "DeSoto County",
    stateCode: "FL",
    stateName: "Florida",
    population: 36744,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.desotocountyfl.gov",
    agendaPathHints: ["/government/bcc/agendas", "/meetings"],
    isActive: true,
    notes: "Active E911 PSAP procurement signal \u2014 priority watch",
  },
  {
    jurisdictionId: "county#WV#upshur",
    type: "county",
    name: "Upshur County",
    stateCode: "WV",
    stateName: "West Virginia",
    population: 24623,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    agendaBaseUrl: "https://upshurwv.org",
    agendaPathHints: ["/commission/agendas", "/meetings"],
    isActive: true,
    notes: "Active NG911 evaluation signal",
  },
  {
    jurisdictionId: "county#GA#chatham",
    type: "county",
    name: "Chatham County",
    stateCode: "GA",
    stateName: "Georgia",
    population: 295291,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.chathamcountyga.gov",
    agendaPathHints: ["/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#GA#dekalb",
    type: "county",
    name: "DeKalb County",
    stateCode: "GA",
    stateName: "Georgia",
    population: 764382,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.dekalbcountyga.gov",
    agendaPathHints: ["/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#GA#cobb",
    type: "county",
    name: "Cobb County",
    stateCode: "GA",
    stateName: "Georgia",
    population: 766149,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.cobbcounty.org",
    agendaPathHints: ["/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#AL#jefferson",
    type: "county",
    name: "Jefferson County",
    stateCode: "AL",
    stateName: "Alabama",
    population: 674721,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.jccal.org",
    agendaPathHints: ["/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#AL#madison",
    type: "county",
    name: "Madison County",
    stateCode: "AL",
    stateName: "Alabama",
    population: 388153,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    agendaBaseUrl: "https://www.madisoncountyal.gov",
    agendaPathHints: ["/commission/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#FL#hillsborough",
    type: "county",
    name: "Hillsborough County",
    stateCode: "FL",
    stateName: "Florida",
    population: 1459762,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.hillsboroughcounty.org",
    agendaPathHints: ["/bocc/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#FL#orange",
    type: "county",
    name: "Orange County",
    stateCode: "FL",
    stateName: "Florida",
    population: 1429908,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    agendaBaseUrl: "https://www.orangecountyfl.net",
    agendaPathHints: ["/board/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  {
    jurisdictionId: "county#FL#duval",
    type: "county",
    name: "Duval County",
    stateCode: "FL",
    stateName: "Florida",
    population: 995098,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    agendaBaseUrl: "https://www.coj.net",
    agendaPathHints: ["/council/agendas", "/meetings"],
    isActive: true,
    notes: null,
  },
  ...UNIVERSITY_JURISDICTIONS,
];

export function hydrateJurisdiction(seed: JurisdictionSeed, overrides?: Partial<Jurisdiction>): Jurisdiction {
  return {
    ...seed,
    lastScannedAt: overrides?.lastScannedAt ?? "",
    lastSignalAt: overrides?.lastSignalAt ?? null,
    totalSignalsFound: overrides?.totalSignalsFound ?? 0,
    priorityBoost: overrides?.priorityBoost ?? 0,
    ...overrides,
  };
}
