import type { JurisdictionSeed, ScanTier } from "./jurisdiction-registry.js";

/**
 * Large road races + national OCR corporates used as Rapid IQ venue seeds.
 * National brands use stateCode "US" so they stay out of state-coverage tracking.
 */
export const VENUE_JURISDICTIONS: JurisdictionSeed[] = [
  {
    jurisdictionId: "venue_event#GA#peachtree",
    type: "venue_event",
    name: "AJC Peachtree Road Race",
    stateCode: "GA",
    stateName: "Georgia",
    population: 60000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "July 4 — ~60,000 participants. Atlanta's largest single-day sporting event.",
    agendaBaseUrl: "https://www.atlantatrackclub.org/peachtree",
    agendaPathHints: ["/news", "/race-info"],
  },
  {
    jurisdictionId: "venue_event#GA#georgia-marathon",
    type: "venue_event",
    name: "Georgia Marathon",
    stateCode: "GA",
    stateName: "Georgia",
    population: 12000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "March — Atlanta marathon / half with city-wide course operations.",
    agendaBaseUrl: "https://www.georgiamarathon.com",
    agendaPathHints: ["/news", "/race-info"],
  },
  {
    jurisdictionId: "venue_event#FL#disney-marathon",
    type: "venue_event",
    name: "Walt Disney World Marathon Weekend",
    stateCode: "FL",
    stateName: "Florida",
    population: 50000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "January — multi-day Disney World race weekend.",
    agendaBaseUrl: "https://www.rundisney.com",
    agendaPathHints: ["/events", "/news"],
  },
  {
    jurisdictionId: "venue_event#TX#houston-marathon",
    type: "venue_event",
    name: "Chevron Houston Marathon",
    stateCode: "TX",
    stateName: "Texas",
    population: 25000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "January — Houston's flagship road race.",
    agendaBaseUrl: "https://www.chevronhoustonmarathon.com",
    agendaPathHints: ["/news", "/race-info"],
  },
  {
    jurisdictionId: "venue_corporate#US#spartan",
    type: "venue_corporate",
    name: "Spartan Race",
    stateCode: "US",
    stateName: "United States",
    population: 100000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "National OCR — 100+ events/year. Corporate account covers all US races.",
    agendaBaseUrl: "https://www.spartan.com",
    agendaPathHints: ["/race/find-race", "/news"],
  },
  {
    jurisdictionId: "venue_corporate#US#tough-mudder",
    type: "venue_corporate",
    name: "Tough Mudder",
    stateCode: "US",
    stateName: "United States",
    population: 80000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "National OCR — year-round obstacle events.",
    agendaBaseUrl: "https://toughmudder.com",
    agendaPathHints: ["/events", "/news"],
  },
];
