/**
 * RMS HTTP API (CRUD, NIBRS classify, push, pre-call context).
 *
 * GET    /api/rms/reports
 * GET    /api/rms/reports/{reportId}
 * PATCH  /api/rms/reports/{reportId}
 * POST   /api/rms/reports/{reportId}/finalize
 * GET    /api/rms/reports/{reportId}/export
 * POST   /api/rms/reports/{reportId}/push
 * POST   /api/rms/nibrs/classify
 * GET    /api/rms/context
 */

import type { APIGatewayProxyEventV2, APIGatewayProxyResultV2 } from "aws-lambda";
import {
  FinalizeIncidentReportSchema,
  NibrsClassifyRequestSchema,
  PatchIncidentReportSchema,
  isRcsuperadmin,
  type IncidentReport,
  type NibrsClassification,
  type RmsContext,
} from "rapid-cortex-shared";
import { AuthorizationService } from "rapid-cortex-security";
import { ACCOUNT_INACTIVE_MESSAGE, getUserContext, isUserAccountActive } from "../../lib/auth.js";
import { withCorrelationHeaders } from "../../lib/correlation.js";
import { env } from "../../lib/env.js";
import { getRmsAdapter, resolveAgencyRmsConfig } from "../../lib/rms/adapters.js";
import { auditRmsMutation, AUDIT_EVENT_TYPES } from "../../lib/rms/audit.js";
import {
  buildNibrsPrompt,
  completeClaudeJson,
  parseJsonObject,
} from "../../lib/rms/claude-report.js";
import {
  finalizeReport,
  getReport,
  getRmsContextCache,
  listReports,
  setRmsContextCache,
  updateReport,
} from "../../lib/rms/reports-db.js";
import {
  badRequest,
  forbidden,
  notFound,
  ok,
  serverError,
  unauthorized,
} from "../../lib/response.js";

const authz = new AuthorizationService();

function parseBody(event: APIGatewayProxyEventV2): unknown {
  if (!event.body) return {};
  try {
    const raw = event.isBase64Encoded
      ? Buffer.from(event.body, "base64").toString("utf8")
      : event.body;
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function formatReportAsText(report: IncidentReport): string {
  const lines: string[] = [
    "INCIDENT REPORT",
    "═".repeat(60),
    `Incident Number: ${report.cadIncidentNumber ?? report.incidentId}`,
    `Date: ${report.incidentDate}  Time: ${report.incidentTime}`,
    `Incident Type: ${report.incidentType}`,
    `Location: ${report.incidentAddress}${report.incidentCity ? `, ${report.incidentCity}` : ""}${report.incidentState ? `, ${report.incidentState}` : ""}`,
    `Reporting Officer: ${report.reportingOfficer ?? ""}`,
    "",
    "NARRATIVE",
    "─".repeat(60),
    report.narrative.officerNarrative,
    "",
  ];

  if (report.narrative.suspectDescription) {
    lines.push("SUSPECT DESCRIPTION", "─".repeat(60), report.narrative.suspectDescription, "");
  }
  if (report.narrative.victimInformation) {
    lines.push("VICTIM INFORMATION", "─".repeat(60), report.narrative.victimInformation, "");
  }
  if (report.narrative.vehicleInformation) {
    lines.push("VEHICLE INFORMATION", "─".repeat(60), report.narrative.vehicleInformation, "");
  }
  if (report.narrative.evidenceSummary) {
    lines.push("EVIDENCE", "─".repeat(60), report.narrative.evidenceSummary, "");
  }
  if (report.nibrsClassification && report.nibrsConfirmed) {
    lines.push(
      "NIBRS CLASSIFICATION",
      "─".repeat(60),
      `Offense Code: ${report.nibrsClassification.offenseCode} — ${report.nibrsClassification.offenseDescription}`,
      `Location Type: ${report.nibrsClassification.locationTypeCode} — ${report.nibrsClassification.locationTypeDescription}`,
      `Attempted/Completed: ${report.nibrsClassification.attemptedCompleted === "C" ? "Completed" : "Attempted"}`,
      "",
    );
  }

  lines.push(
    "─".repeat(60),
    "Report generated by Rapid Cortex AI Report Writer",
    `Status: ${report.status.toUpperCase()}`,
    report.finalizedAt ? `Finalized: ${report.finalizedAt} by ${report.finalizedBy}` : "",
    "Record retained per RC MSA Section 10.7 (7 years)",
  );

  return lines.filter((l) => l !== undefined && l !== null).join("\n");
}

async function queryTylerContext(
  address: string | undefined,
  phone: string | undefined,
  config: Record<string, string>,
): Promise<Omit<RmsContext, "dataSource" | "retrievedAt" | "cached">> {
  const apiUrl = config.apiUrl;
  const apiKey = config.apiKey;
  if (!apiUrl || !apiKey) throw new Error("Tyler RMS not configured");

  const results: Omit<RmsContext, "dataSource" | "retrievedAt" | "cached"> = {};

  if (address) {
    const res = await fetch(
      `${apiUrl.replace(/\/$/, "")}/incidents/history?address=${encodeURIComponent(address)}&limit=5`,
      { headers: { "X-API-Key": apiKey }, signal: AbortSignal.timeout(3_000) },
    );
    if (res.ok) {
      const data = (await res.json()) as Record<string, unknown>;
      results.addressHistory = {
        address,
        priorIncidentCount: Number(data.totalCount ?? 0),
        lastIncidentDate: data.lastIncidentDate as string | undefined,
        lastIncidentType: data.lastIncidentType as string | undefined,
        hasActiveProtectiveOrder: Boolean(data.hasProtectiveOrder),
        hasHazardFlag: Boolean(data.hasHazardFlag),
        hazardDescription: data.hazardDescription as string | undefined,
        recentIncidents: ((data.incidents as Array<Record<string, string>>) ?? []).map((i) => ({
          date: i.date ?? "",
          type: i.type ?? "",
          caseNumber: i.caseNumber,
          disposition: i.disposition,
        })),
      };
    }
  }

  if (phone) {
    results.callerHistory = {
      phone,
      priorCallCount: 0,
      isKnownOffender: false,
      hasActiveWarrant: false,
    };
  }

  return results;
}

export async function handler(event: APIGatewayProxyEventV2): Promise<APIGatewayProxyResultV2> {
  try {
    if (!env.enableRms) {
      return withCorrelationHeaders(event, badRequest("RMS capabilities are not enabled"));
    }

    const method = (event.requestContext.http?.method ?? "GET").toUpperCase();
    const path = event.rawPath ?? event.requestContext.http?.path ?? "";

    const user = await getUserContext(event);
    if (!user) return withCorrelationHeaders(event, unauthorized());
    if (!isUserAccountActive(user)) {
      return withCorrelationHeaders(event, unauthorized(ACCOUNT_INACTIVE_MESSAGE));
    }

    const agencyId = user.agencyId;
    if (!agencyId && !isRcsuperadmin(user)) {
      return withCorrelationHeaders(event, forbidden());
    }
    const actor = user.email ?? user.userId ?? "unknown";
    const reportId = event.pathParameters?.reportId
      ? decodeURIComponent(event.pathParameters.reportId)
      : undefined;

    // GET /api/rms/context
    if (method === "GET" && /\/rms\/context\/?$/.test(path)) {
      try {
        authz.assertCanPerform(user, "rms.view_context");
      } catch {
        return withCorrelationHeaders(event, forbidden());
      }

      const address = event.queryStringParameters?.address ?? "";
      const phone = event.queryStringParameters?.phone ?? "";
      if (!address && !phone) {
        return withCorrelationHeaders(event, badRequest("address or phone required"));
      }

      const scopedAgency = agencyId || "";
      const cacheKey = `${scopedAgency}:${address}:${phone}`;
      const cached = await getRmsContextCache(cacheKey);
      if (cached) {
        return withCorrelationHeaders(event, ok({ context: { ...cached, cached: true } }));
      }

      const { target, config } = await resolveAgencyRmsConfig(scopedAgency);
      if (!target) {
        return withCorrelationHeaders(
          event,
          ok({ context: null, message: "No RMS configured for this agency." }),
        );
      }

      try {
        let contextData: Omit<RmsContext, "dataSource" | "retrievedAt" | "cached"> = {};
        if (target === "tyler-new-world") {
          contextData = await queryTylerContext(address || undefined, phone || undefined, config);
        }
        const context: RmsContext = {
          ...contextData,
          dataSource: target,
          retrievedAt: new Date().toISOString(),
          cached: false,
        };
        await setRmsContextCache(cacheKey, context);
        return withCorrelationHeaders(event, ok({ context }));
      } catch (err) {
        console.warn("RMS context query failed:", err);
        return withCorrelationHeaders(
          event,
          ok({ context: null, error: err instanceof Error ? err.message : String(err) }),
        );
      }
    }

    // POST /api/rms/nibrs/classify
    if (method === "POST" && /\/rms\/nibrs\/classify\/?$/.test(path)) {
      try {
        authz.assertCanPerform(user, "rms.view_nibrs");
      } catch {
        return withCorrelationHeaders(event, forbidden());
      }
      const body = parseBody(event);
      if (body === null) return withCorrelationHeaders(event, badRequest("Invalid JSON"));
      const parsed = NibrsClassifyRequestSchema.safeParse(body);
      if (!parsed.success) {
        return withCorrelationHeaders(event, badRequest(parsed.error.message));
      }
      const text = await completeClaudeJson(
        buildNibrsPrompt(parsed.data.incidentType, parsed.data.description, parsed.data.state ?? ""),
        500,
      );
      const classification = parseJsonObject(text) as unknown as NibrsClassification;
      return withCorrelationHeaders(event, ok({ classification }));
    }

    // GET /api/rms/reports
    if (method === "GET" && /\/rms\/reports\/?$/.test(path)) {
      try {
        authz.assertCanPerform(user, "rms.view_report");
      } catch {
        return withCorrelationHeaders(event, forbidden());
      }
      if (!agencyId) return withCorrelationHeaders(event, badRequest("agencyId required"));
      const status = event.queryStringParameters?.status;
      const reports = await listReports(agencyId, status);
      return withCorrelationHeaders(event, ok({ reports }));
    }

    if (!reportId) {
      return withCorrelationHeaders(event, badRequest("reportId required"));
    }
    if (!agencyId) return withCorrelationHeaders(event, badRequest("agencyId required"));

    // GET export
    if (method === "GET" && path.endsWith("/export")) {
      try {
        authz.assertCanPerform(user, "rms.export_report");
      } catch {
        return withCorrelationHeaders(event, forbidden());
      }
      const report = await getReport(agencyId, reportId);
      if (!report) return withCorrelationHeaders(event, notFound("Report not found"));
      const text = formatReportAsText(report);
      return withCorrelationHeaders(event, {
        statusCode: 200,
        headers: {
          "Content-Type": "text/plain; charset=utf-8",
          "Content-Disposition": `attachment; filename="incident-report-${report.incidentId}-${report.incidentDate}.txt"`,
        },
        body: text,
      });
    }

    // POST finalize — supervisors only; body must confirm NIBRS.
    if (method === "POST" && path.endsWith("/finalize")) {
      try {
        authz.assertCanPerform(user, "rms.finalize_report");
      } catch {
        return withCorrelationHeaders(event, forbidden());
      }
      const body = parseBody(event);
      if (body === null) return withCorrelationHeaders(event, badRequest("Invalid JSON"));
      const parsed = FinalizeIncidentReportSchema.safeParse(body);
      if (!parsed.success) {
        return withCorrelationHeaders(event, badRequest("nibrsConfirmed must be true to finalize"));
      }
      const existing = await getReport(agencyId, reportId);
      if (!existing) return withCorrelationHeaders(event, notFound("Report not found"));
      if (!existing.nibrsClassification) {
        return withCorrelationHeaders(
          event,
          badRequest("NIBRS classification is required before finalize"),
        );
      }
      const report = await finalizeReport(agencyId, reportId, actor);
      await auditRmsMutation({
        type: AUDIT_EVENT_TYPES.RMS_REPORT_FINALIZED,
        user,
        agencyId,
        incidentId: report.incidentId,
        reportId,
        metadata: { nibrsConfirmed: true },
      });
      return withCorrelationHeaders(event, ok({ report }));
    }

    // POST push
    if (method === "POST" && path.endsWith("/push")) {
      try {
        authz.assertCanPerform(user, "rms.push_to_rms");
      } catch {
        return withCorrelationHeaders(event, forbidden());
      }
      const report = await getReport(agencyId, reportId);
      if (!report) return withCorrelationHeaders(event, notFound("Report not found"));
      if (report.status !== "finalized") {
        return withCorrelationHeaders(
          event,
          ok({ error: "Report must be finalized before pushing to RMS." }, 422),
        );
      }

      const { target, config } = await resolveAgencyRmsConfig(agencyId);
      const resolvedTarget = target ?? "tyler-new-world";

      try {
        const adapter = getRmsAdapter(resolvedTarget, config);
        const result = await adapter.push(report);
        if (result.status === "pending_vendor") {
          const updated = await updateReport(
            agencyId,
            reportId,
            {
              rmsPushStatus: "pending_vendor",
              rmsPushTarget: resolvedTarget,
              rmsExternalId: result.externalId,
            },
            actor,
          );
          await auditRmsMutation({
            type: AUDIT_EVENT_TYPES.RMS_REPORT_PUSHED,
            user,
            agencyId,
            incidentId: report.incidentId,
            reportId,
            metadata: { status: "pending_vendor", target: resolvedTarget },
          });
          return withCorrelationHeaders(
            event,
            ok({
              success: true,
              status: "pending_vendor",
              externalId: result.externalId,
              target: resolvedTarget,
              report: updated,
            }),
          );
        }
        const updated = await updateReport(
          agencyId,
          reportId,
          {
            rmsPushStatus: "pushed",
            rmsPushTarget: resolvedTarget,
            rmsPushedAt: new Date().toISOString(),
            rmsExternalId: result.externalId,
            status: "pushed_to_rms",
          },
          actor,
        );
        await auditRmsMutation({
          type: AUDIT_EVENT_TYPES.RMS_REPORT_PUSHED,
          user,
          agencyId,
          incidentId: report.incidentId,
          reportId,
          metadata: { status: "pushed", target: resolvedTarget, externalId: result.externalId },
        });
        return withCorrelationHeaders(
          event,
          ok({
            success: true,
            status: "pushed",
            externalId: result.externalId,
            target: resolvedTarget,
            report: updated,
          }),
        );
      } catch (err) {
        await updateReport(agencyId, reportId, { rmsPushStatus: "failed" }, actor).catch(() => null);
        return withCorrelationHeaders(
          event,
          serverError(err instanceof Error ? err.message : "RMS push failed"),
        );
      }
    }

    // GET single
    if (method === "GET") {
      try {
        authz.assertCanPerform(user, "rms.view_report");
      } catch {
        return withCorrelationHeaders(event, forbidden());
      }
      const report = await getReport(agencyId, reportId);
      if (!report) return withCorrelationHeaders(event, notFound("Report not found"));
      return withCorrelationHeaders(event, ok({ report }));
    }

    // PATCH
    if (method === "PATCH") {
      try {
        authz.assertCanPerform(user, "rms.edit_report");
      } catch {
        return withCorrelationHeaders(event, forbidden());
      }
      const body = parseBody(event);
      if (body === null) return withCorrelationHeaders(event, badRequest("Invalid JSON"));
      const parsed = PatchIncidentReportSchema.safeParse(body);
      if (!parsed.success) {
        return withCorrelationHeaders(event, badRequest(parsed.error.message));
      }

      const existing = await getReport(agencyId, reportId);
      if (!existing) return withCorrelationHeaders(event, notFound("Report not found"));

      const patch = parsed.data;
      const updates: Partial<IncidentReport> = {};
      if (patch.narrative) {
        updates.narrative = { ...existing.narrative, ...patch.narrative };
      }
      if (patch.nibrsClassification) updates.nibrsClassification = patch.nibrsClassification;
      if (patch.nibrsConfirmed !== undefined) updates.nibrsConfirmed = patch.nibrsConfirmed;
      if (patch.suspects) updates.suspects = patch.suspects;
      if (patch.victims) updates.victims = patch.victims;
      if (patch.witnesses) updates.witnesses = patch.witnesses;
      if (patch.vehicles) updates.vehicles = patch.vehicles;
      if (patch.reportingOfficer !== undefined) updates.reportingOfficer = patch.reportingOfficer;
      if (patch.caseNumber !== undefined) updates.caseNumber = patch.caseNumber;
      if (patch.status) updates.status = patch.status;

      const report = await updateReport(agencyId, reportId, updates, actor);
      await auditRmsMutation({
        type: AUDIT_EVENT_TYPES.RMS_REPORT_EDITED,
        user,
        agencyId,
        incidentId: report.incidentId,
        reportId,
        metadata: { fields: Object.keys(updates) },
      });
      return withCorrelationHeaders(event, ok({ report }));
    }

    return withCorrelationHeaders(event, badRequest("Method not allowed"));
  } catch (err) {
    console.error(
      JSON.stringify({
        msg: "rms_http_error",
        error: err instanceof Error ? err.message : String(err),
      }),
    );
    if (err instanceof Error && err.message === "Finalized reports cannot be edited") {
      return withCorrelationHeaders(event, badRequest(err.message));
    }
    if (err instanceof Error && err.message === "Report not found") {
      return withCorrelationHeaders(event, notFound(err.message));
    }
    return withCorrelationHeaders(event, serverError());
  }
}
