export const Strings = {
  app: {
    name: 'Rapid Cortex',
    tagline: 'Real-Time AI Intelligence for Emergency Response',
  },

  enterSplash: {
    eyebrow: 'Rapid Cortex',
    titleLine1: 'Enter the',
    titleLine2: 'Cortex',
    tagline: 'Intelligence at the speed of response',
    initialize: 'Initialize',
    accessing: 'Accessing...',
    statusNeural: 'NEURAL LINK ESTABLISHED',
    statusOnline: 'CORTEX ONLINE',
    statusRouting: 'ROUTING...',
  },

  common: {
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    save: 'Save',
    retry: 'Try Again',
    close: 'Close',
    edit: 'Edit',
    share: 'Share',
    copy: 'Copy',
    copied: 'Copied',
    loading: 'Loading…',
    offline: 'You are offline. Some features may be unavailable.',
    offlineLastUpdated: (minutes: number) => `Last updated ${minutes} min ago`,
    willSyncWhenConnected: 'Will sync when connected',
    somethingWentWrong: 'Something went wrong. Try again.',
    notFound: 'Not found',
    noPermission: "You don't have permission to do this.",
    checkConnection: 'Unable to connect. Check your internet connection and try again.',
    switchProduct: 'Switch product',
    signOut: 'Sign Out',
    clearAll: 'Clear All',
    skip: 'Skip',
    learnMore: 'Learn More',
    useDeviceLanguage: 'Use Device Language',
    rtlRestartNotice: 'Restart the app for full right-to-left layout support.',
  },

  productSelection: {
    safeSoundTitle: 'RC Safe & Sound',
    safeSoundSubtitle: 'Protect your family, pets, and valuables',
    venueTitle: 'RC Venue',
    venueSubtitle: 'Zone signs, QR codes, and NFC tag programming',
    campusTitle: 'RC Campus',
    campusSubtitle: 'Campus safety reporting codes and NFC deployment',
    /** @deprecated Prefer venueTitle / campusTitle */
    venueCampusTitle: 'RC Venue / Campus',
    venueCampusSubtitle: 'Sign management and field deployment tools',
  },

  auth: {
    signIn: 'Sign In',
    createAccount: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    forgotPassword: 'Forgot password?',
    showPassword: 'Show',
    hidePassword: 'Hide',
    backToProducts: '← Products',
    verificationCode: 'Verification Code',
    venueTools: 'Venue Tools',
    campusTools: 'Campus Tools',
    venueCampusTools: 'Venue & Campus Tools',
    noAccountContactAdmin: "Don't have an account? Contact your Rapid Cortex administrator.",
    faceIdPrompt: 'Allow Rapid Cortex to use Face ID for secure login.',
    biometricReason: 'Authenticate to access Rapid Cortex',
    usePasscode: 'Use Passcode',

    errors: {
      userNotConfirmed: "Please verify your email first. We'll resend the code.",
      notAuthorized: 'Incorrect email or password.',
      usernameExists: 'An account with this email already exists.',
      invalidPassword: 'Password does not meet requirements.',
      networkTimeout: 'Unable to connect. Check your internet connection and try again.',
      venueAccessDenied:
        'Your account does not have access to venue tools. Contact your administrator.',
      campusAccessDenied:
        'Your account does not have access to campus tools. Contact your administrator.',
    },
  },

  safeSound: {
    myDevices: 'My Devices',
    addDevice: 'Add Device',
    noDevicesTitle: 'No devices yet',
    noDevicesAction: 'Add Your First Device',
    deviceTypes: {
      home: 'Home',
      guardian: 'Guardian',
    },
    mountTypes: {
      keychain: 'Keychain',
      backpack: 'Backpack',
      collar: 'Pet Collar',
      luggage: 'Luggage Tag',
      wristband: 'Wristband',
      other: 'Other',
    },
    status: {
      inRange: 'In range',
      recentlySeen: 'Recently seen',
      warning: 'Last seen 10–60 min ago',
      offline: 'Offline',
      lostMode: 'Lost Mode',
    },
    lastSeen: (label: string) => `Last seen ${label}`,
    battery: 'Battery',
    lostMode: 'Lost Mode',
    locationHistory: 'Location History',
    geofences: 'Geofences',
    emergencyContacts: 'Emergency Contacts',
    rcCoreConsentTitle:
      'Allow authorized 911 centers to request this device\'s location during an emergency',
    rcCoreConsentSubtitle:
      'Your data is never shared without your authorization. All access is logged.',
    deleteDeviceTitle: 'Delete Device',
    deleteDeviceMessage: 'This will permanently remove the device from your account.',
    addDeviceHome: {
      title: 'Safe & Sound Home',
      price: '$9.99',
      description: 'Pairs via Bluetooth',
      batteryLife: '6–12 month battery',
    },
    addDeviceGuardian: {
      title: 'Safe & Sound Guardian',
      price: '$19.99 + $3.99/mo',
      description: 'Independent tracking',
    },
    pairing: {
      wakeDevice: 'Press the button on your Home device once.',
      deviceAwake: 'My device is awake',
      scanning: 'Scanning…',
      scanningTimeout: 'No device found. Try again.',
      nameDevice: 'Name your device',
      defaultDeviceName: 'My Device',
      pairing: 'Pairing…',
      success: (name: string) => `Your ${name} is set up!`,
      blePermissionDenied: 'Bluetooth permission is required to pair devices.',
      bleOpenSettings: 'Open Settings',
    },
    guardianPairing: {
      scanQr: 'Scan the QR code on your Guardian quick start card.',
      subscriptionTitle: 'Guardian subscription required',
      subscriptionPrice: '$3.99/month',
      activating: 'Activating eSIM…',
      connecting: 'Connecting to network…',
      gettingLocation: 'Getting first location…',
      ready: 'Ready',
      rcCoreConsentExplain:
        'During an emergency, authorized 911 centers may request your Guardian device location if you opt in.',
    },
    map: {
      zoomToFit: 'Show all devices',
      locateMe: 'Locate me',
    },
    alerts: {
      title: 'Alerts',
      geofenceEnter: 'Entered geofence',
      geofenceExit: 'Left geofence',
      sos: 'SOS activated',
      fallDetected: 'Possible fall detected',
      lowBattery: 'Low battery',
      deviceOffline: 'Device offline',
      deviceOnline: 'Device back online',
      lostModeActivated: 'Lost Mode activated',
      lostModeDeactivated: 'Lost Mode deactivated',
      contactsNotified: 'Emergency contacts notified',
      escalation: 'Guardian escalation',
    },
    account: {
      devices: 'Devices',
      subscriptions: 'Subscriptions',
      manageSubscription: 'Manage',
      notifications: 'Notifications',
      biometricLogin: 'Biometric login',
      language: 'Language',
      myLanguage: 'My Language',
      languageSubtitle:
        'Intelligent translations powered by Rapid Cortex · 150+ languages',
      languagePreferenceHelp:
        'Your language preference helps emergency responders communicate with you. Rapid Cortex intelligent translation supports 150+ languages.',
      emergencyContactsShortcut: 'Emergency contacts',
    },
  },

  venue: {
    codes: 'QR & NFC Codes',
    create: 'Create',
    account: 'Account',
    agencyCodes: 'QR & NFC Codes',
    searchPlaceholder: 'Search by name or zone',
    filters: {
      all: 'All',
      active: 'Active',
      inactive: 'Inactive',
      nfcWritten: 'NFC Written',
      notWritten: 'Not Written',
    },
    nfcWritten: 'NFC Written',
    notProgrammed: 'Not Programmed',
    lastActivity: 'Last activity',
    createCode: {
      codeName: 'Code Name',
      codeNamePlaceholder: 'e.g. Gate B Concourse',
      zone: 'Zone / Location',
      zonePlaceholder: 'e.g. Section 112, Row A',
      reportType: 'Report Type',
      reportTypes: {
        anonymous: 'Anonymous',
        identified: 'Identified',
        both: 'Both',
      },
      smsNumber: 'SMS Phone Number',
      smsPlaceholder: '(555) 000-0000',
      smsHelper:
        'The phone number visitors text to report an incident. Appears on the physical sign.',
      createButton: 'Create Code',
      successToast: 'Code created — ready to program',
    },
    signPackage: {
      signIdentity: 'Sign Identity',
      qrCode: 'QR Code',
      saveToPhotos: 'Save to Photos',
      shareQr: 'Share',
      copyUrl: 'Copy URL',
      printMinSize: 'Print at minimum 2 inches for wall signs',
      nfcTag: 'NFC Tag',
      programNfc: 'Program NFC Tag',
      nfcHoldPrompt: 'Hold an NTAG213 tag to the back of your phone',
      nfcSuccess: 'Tag programmed ✓',
      nfcWriteLog: 'NFC Write Log',
      nfcWriteLogEmpty: 'No tags programmed yet.',
      smsNumber: 'SMS Number',
      smsHelper:
        'Visitors text this number to report an incident. Include this on the printed sign.',
      signReference: 'Complete Sign Reference',
      shareSignPackage: 'Share Sign Package',
      engagementMetrics: 'Engagement Metrics',
      nfcTaps: 'NFC Taps',
      qrScans: 'QR Scans',
      totalActivity: 'Total activity',
      dangerZone: 'Danger Zone',
      deactivateCode: 'Deactivate Code',
      deleteCode: 'Delete Code',
      deleteCodeConfirm:
        'This will permanently delete this code and all associated data. Signs using this code will stop working.',
    },
    nfcWrite: {
      ready: 'Hold an NTAG213 tag to the back of your phone',
      detected: 'Tag detected…',
      writing: 'Writing…',
      success: 'Tag programmed successfully',
      writeAnother: 'Write Another',
      errors: {
        unsupported: 'This device does not support NFC.',
        permissionDenied: 'NFC permission was denied.',
        timeout: 'No tag detected in time.',
        tagIncompatible: 'Tag is not compatible. Use an NTAG213 tag.',
        writeFailed: 'Failed to write to tag.',
        cancelled: 'NFC write cancelled.',
      },
    },
    tradeShowNfc: {
      title: 'Trade show signs',
      cta: 'Trade show signs',
      program: 'Program NFC tag',
      blurb:
        'Print the QR and program an NTAG213 so a booth tap or scan opens the Rapid Cortex site — not a location report form. Each tap is counted.',
      homeLabel: 'Home',
      demoLabel: 'Demo',
      ready: 'Hold an NTAG213 tag to the back of your phone',
      writing: 'Writing marketing URL…',
      success: 'Tag opens the Rapid Cortex website',
    },
    accountDetails: {
      role: 'Role',
      agency: 'Agency',
      biometricLogin: 'Biometric login',
      notifications: 'Notifications',
    },
    vertical: {
      venue: 'VENUE',
      campus: 'CAMPUS',
    },
  },

  campus: {
    codes: 'QR & NFC Codes',
    create: 'Create',
    account: 'Account',
  },

  emergency: {
    fallDetected: 'Possible Fall Detected',
    sosActivated: 'SOS Activated',
    noMovement: 'No Movement Detected',
    unusualHeartRate: 'Unusual Heart Rate',
    cancelButton: "I'M OKAY — TAP TO CANCEL",
    cancelled: 'Alert Cancelled',
    contactsNotified: 'Emergency contacts notified',
    incidentCreated: 'Incident created',
    escalationInitiated: 'Escalation initiated',
    helpOnTheWay: 'Help is on the way',
    falseAlarm: 'Cancel — False Alarm',
    cancelHint: 'Tap once to cancel the emergency alert',
    countdownAccessibility: (seconds: number) => `${seconds} seconds remaining`,
  },

  geofence: {
    create: 'Create Geofence',
    save: 'Save Geofence',
    name: 'Geofence name',
    alertOnEnter: 'Alert on enter',
    alertOnExit: 'Alert on exit',
    circle: 'Circle',
    polygon: 'Polygon',
    addressSearch: 'Search address',
  },

  emergencyContacts: {
    title: 'Emergency Contacts',
    name: 'Name',
    phone: 'Phone number',
    relationship: 'Relationship',
    notifyVia: 'Notify via',
    push: 'Push notification',
    sms: 'SMS',
    phoneCall: 'Phone call',
    canCancelAlerts: 'Can cancel alerts',
    preferredLanguage: 'Notification language',
    preferredLanguageHelp:
      "Emergency alerts will be sent to this contact in their language using Rapid Cortex's 150+ language translation service.",
    relationships: {
      parent: 'Parent',
      spouse: 'Spouse',
      child: 'Child',
      sibling: 'Sibling',
      friend: 'Friend',
      caregiver: 'Caregiver',
      other: 'Other',
    },
    maxContacts: 'You can add up to 5 emergency contacts.',
  },

  language: {
    pickerTitle: 'Select Language',
    searchPlaceholder: 'Search languages',
    noResults: (query: string) => `No languages matching '${query}'`,
    rtlBadge: 'RTL',
    poweredBy: 'Intelligent translations powered by Rapid Cortex',
    unavailable: 'Language list unavailable. Check your connection.',
    detected: 'Detected',
  },

  location: {
    permissionDenied: 'Location permission is required for this feature.',
    backgroundDenied:
      'Background location permission is required for Guardian emergency detection.',
    openSettings: 'Open Settings',
    sources: {
      gps: 'GPS',
      cellular: 'Cellular',
      bluetooth: 'Bluetooth',
      community: 'Community',
      phoneGps: 'Phone GPS',
    },
  },

  nfc: {
    unsupported: 'NFC is not available on this device.',
    disabled: 'NFC is disabled. Enable it in Settings.',
  },

  ble: {
    deviceNotFound: 'Device not found',
    pairingFailed: 'Pairing failed',
    outOfRange: 'Device is out of range',
  },

  validation: {
    emailRequired: 'Email is required.',
    emailInvalid: 'Enter a valid email address.',
    passwordRequired: 'Password is required.',
    passwordMinLength: 'Password must be at least 12 characters.',
    passwordUppercase: 'Password must include an uppercase letter.',
    passwordLowercase: 'Password must include a lowercase letter.',
    passwordNumber: 'Password must include a number.',
    passwordSymbol: 'Password must include a symbol.',
    passwordMismatch: 'Passwords do not match.',
    phoneRequired: 'Phone number is required.',
    phoneInvalid: 'Enter a valid phone number in E.164 format.',
    fieldRequired: 'This field is required.',
  },

  guardian: {
    batteryOptimizationTitle: 'Keep Guardian running',
    batteryOptimizationBody:
      'Allow background activity so Guardian can detect emergencies even when your phone is locked.',
  },

  compliance: {
    not911Replacement: 'NOT A 911 EMERGENCY DISPATCH SYSTEM',
    fallDetection: 'detects possible falls',
    cardiac: 'detects unusual heart rate patterns',
    connectHelp: 'helps connect you with help',
  },
} as const;

export type StringsType = typeof Strings;
