/**
 * Secure venue incident report PDF + distribution (RFP 2396IP).
 */
import PDFDocument from "pdfkit";
import { PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { GetObjectCommand } from "@aws-sdk/client-s3";
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand, PutCommand, QueryCommand } from "@aws-sdk/lib-dynamodb";
import type { VenueSecureShareBody } from "rapid-cortex-shared";
import { makeId } from "../lib/ids.js";
import { listVenueEvidence } from "./venue-evidence-service.js";
import { listVenueRfpAudit, writeVenueRfpAudit } from "./venue-rfp-audit.js";
import { VENUE_KEYS, type VenueIncidentRecord } from "./venue-types.js";

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({}));
const s3 = new S3Client({});

function venueConfigTable(): string {
  const t = process.env.VENUE_CONFIG_TABLE?.trim();
  if (!t) throw new Error("VENUE_CONFIG_TABLE not set");
  return t;
}

function assetsBucket(): string {
  const b = process.env.ASSETS_BUCKET?.trim() || process.env.VENUE_EVIDENCE_BUCKET?.trim() || "";
  if (!b) throw new Error("ASSETS_BUCKET not set");
  return b;
}

async function renderIncidentPdf(params: {
  incident: VenueIncidentRecord;
  evidenceCount: number;
  auditCount: number;
  generatedBy: string;
}): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 50, size: "LETTER" });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  doc.fontSize(18).text("NexCort iQ — Venue Incident Report", { underline: true });
  doc.moveDown();
  doc.fontSize(11);
  doc.text(`Incident: ${params.incident.incidentId}`);
  doc.text(`Venue: ${params.incident.venueCode}`);
  doc.text(`Status: ${params.incident.status}`);
  doc.text(`Type: ${params.incident.type}`);
  doc.text(`Zone: ${params.incident.zoneLabel || params.incident.zoneCode || "—"}`);
  doc.text(`Assigned: ${params.incident.assignedTo ?? "—"}`);
  doc.text(`Escalation: ${params.incident.escalationLevel ?? 0}`);
  doc.text(`Approval: ${params.incident.approvalStatus ?? "—"}`);
  doc.text(`Created: ${params.incident.createdAt}`);
  doc.text(`Updated: ${params.incident.updatedAt}`);
  doc.moveDown();
  doc.text("Description");
  doc.text(params.incident.description || "—", { width: 500 });
  doc.moveDown();
  if (params.incident.disposition) {
    doc.text("Disposition");
    doc.text(params.incident.disposition, { width: 500 });
    doc.moveDown();
  }
  doc.text(`Evidence items: ${params.evidenceCount}`);
  doc.text(`Audit events: ${params.auditCount}`);
  doc.moveDown();
  doc.fontSize(9).fillColor("#666").text(`Generated by ${params.generatedBy} at ${new Date().toISOString()}`);
  doc.text("This document is controlled. Redistribution requires authorized secure link.");
  doc.end();
  return done;
}

export async function generateVenueIncidentReport(params: {
  venueCode: string;
  agencyId: string;
  incidentId: string;
  actorId: string;
  actorRole: string;
  actorEmail?: string;
  ttlHours?: number;
}): Promise<{ reportId: string; reportKey: string; reportUrl: string; expiresAt: string }> {
  const venueCode = params.venueCode.toUpperCase();
  const incident = (
    await ddb.send(
      new GetCommand({
        TableName: venueConfigTable(),
        Key: { pk: VENUE_KEYS.incidentPk(venueCode), sk: VENUE_KEYS.incidentSk(params.incidentId) },
      }),
    )
  ).Item as VenueIncidentRecord | undefined;
  if (!incident) throw Object.assign(new Error("NOT_FOUND"), { statusCode: 404 });

  const evidence = await listVenueEvidence(venueCode, params.incidentId, params.agencyId);
  const audit = await listVenueRfpAudit({ venueCode, incidentId: params.incidentId, limit: 50 });
  const pdf = await renderIncidentPdf({
    incident,
    evidenceCount: evidence.length,
    auditCount: audit.length,
    generatedBy: params.actorEmail || params.actorId,
  });

  const reportId = makeId("rpt");
  const reportKey = `reports/${venueCode}/${params.incidentId}/${reportId}.pdf`;
  const bucket = assetsBucket();
  await s3.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: reportKey,
      Body: pdf,
      ContentType: "application/pdf",
      ServerSideEncryption: "AES256",
      Metadata: {
        "incident-id": params.incidentId,
        "venue-code": venueCode,
        "generated-by": params.actorId,
      },
    }),
  );

  const ttlHours = Math.min(Math.max(params.ttlHours ?? 24, 1), 168);
  const expiresIn = ttlHours * 3600;
  const reportUrl = await getSignedUrl(
    s3,
    new GetObjectCommand({ Bucket: bucket, Key: reportKey }),
    { expiresIn },
  );
  const expiresAt = new Date(Date.now() + expiresIn * 1000).toISOString();
  const now = new Date().toISOString();

  await ddb.send(
    new PutCommand({
      TableName: venueConfigTable(),
      Item: {
        pk: VENUE_KEYS.incidentPk(venueCode),
        sk: VENUE_KEYS.reportSk(params.incidentId, reportId),
        reportId,
        incidentId: params.incidentId,
        venueCode,
        agencyId: params.agencyId,
        s3Bucket: bucket,
        s3Key: reportKey,
        createdAt: now,
        createdBy: params.actorId,
        expiresAt,
      },
      ConditionExpression: "attribute_not_exists(sk)",
    }),
  );

  await writeVenueRfpAudit({
    venueCode,
    agencyId: params.agencyId,
    eventType: "REPORT_GENERATED",
    actorId: params.actorId,
    actorRole: params.actorRole,
    actorEmail: params.actorEmail,
    resourceType: "report",
    resourceId: reportId,
    incidentId: params.incidentId,
    metadata: { reportKey, expiresAt },
  });

  return { reportId, reportKey, reportUrl, expiresAt };
}

export async function distributeVenueReport(params: {
  venueCode: string;
  agencyId: string;
  incidentId: string;
  reportId: string;
  actorId: string;
  actorRole: string;
  body: VenueSecureShareBody;
}): Promise<{ distributionId: string; reportUrl: string; expiresAt: string }> {
  const venueCode = params.venueCode.toUpperCase();
  const report = (
    await ddb.send(
      new GetCommand({
        TableName: venueConfigTable(),
        Key: {
          pk: VENUE_KEYS.incidentPk(venueCode),
          sk: VENUE_KEYS.reportSk(params.incidentId, params.reportId),
        },
      }),
    )
  ).Item as
    | {
        s3Bucket: string;
        s3Key: string;
        reportId: string;
      }
    | undefined;
  if (!report) throw Object.assign(new Error("NOT_FOUND"), { statusCode: 404 });

  const expiresIn = Math.min(Math.max(params.body.ttlHours ?? 72, 1), 168) * 3600;
  const reportUrl = await getSignedUrl(
    s3,
    new GetObjectCommand({ Bucket: report.s3Bucket, Key: report.s3Key }),
    { expiresIn },
  );
  const expiresAt = new Date(Date.now() + expiresIn * 1000).toISOString();
  const distributionId = makeId("dist");
  const now = new Date().toISOString();

  await ddb.send(
    new PutCommand({
      TableName: venueConfigTable(),
      Item: {
        pk: VENUE_KEYS.incidentPk(venueCode),
        sk: `INCIDENT#${params.incidentId}#DIST#${distributionId}`,
        distributionId,
        reportId: params.reportId,
        incidentId: params.incidentId,
        venueCode,
        agencyId: params.agencyId,
        recipientEmail: params.body.recipientEmail ?? null,
        recipientLabel: params.body.recipientLabel ?? null,
        note: params.body.note ?? null,
        includeAttachments: params.body.includeAttachments,
        createdAt: now,
        createdBy: params.actorId,
        expiresAt,
        reportUrlRedacted: true,
      },
      ConditionExpression: "attribute_not_exists(sk)",
    }),
  );

  await writeVenueRfpAudit({
    venueCode,
    agencyId: params.agencyId,
    eventType: "REPORT_DISTRIBUTED",
    actorId: params.actorId,
    actorRole: params.actorRole,
    resourceType: "report",
    resourceId: params.reportId,
    incidentId: params.incidentId,
    metadata: {
      distributionId,
      recipientEmail: params.body.recipientEmail,
      expiresAt,
    },
  });

  // SES send is optional — return link for UI to copy; email path uses existing SES when configured.
  return { distributionId, reportUrl, expiresAt };
}

export async function listVenueReports(venueCode: string, incidentId: string, agencyId: string) {
  const code = venueCode.toUpperCase();
  const r = await ddb.send(
    new QueryCommand({
      TableName: venueConfigTable(),
      KeyConditionExpression: "pk = :pk AND begins_with(sk, :prefix)",
      ExpressionAttributeValues: {
        ":pk": VENUE_KEYS.incidentPk(code),
        ":prefix": VENUE_KEYS.reportPrefix(incidentId),
      },
      Limit: 50,
    }),
  );
  return (r.Items ?? []).filter((row) => row.agencyId === agencyId || agencyId.startsWith("rc"));
}
