/** Re-exports Ring Connect package for API handlers (vendor pack). */
export {
  RingAgencyIsolationError,
  RingApiClient,
  RingAuthError,
  RingConsentError,
  RingDeviceDiscoveryError,
  RingDeviceService,
  RingFeatureDisabledError,
  RingIntegrationError,
  RingOAuthService,
  RingRateLimitError,
  RingSessionError,
  RingTokenExpiredError,
  RingTokenStore,
  RingUnclaimedTokenService,
  RING_ACCOUNT_LINK_URL,
  RING_REDIRECT_URI,
  RING_HOMEOWNER_DEFAULT_AGENCY_ID,
  RING_HOMEOWNER_FALLBACK_LATITUDE,
  RING_HOMEOWNER_FALLBACK_LONGITUDE,
  RING_TABLE_NAMES,
  decodeRingOAuthState,
  isRingAvailableCamerasEnabled,
  isRingEmergencyRequestsEnabled,
  isRingEnabled,
  maskEmailForRing,
  normalizeRingReturnUrl,
  patchRingAppIntegrationCompleted,
  postRingAppIntegration,
  validateRingLinkTimestamp,
  RingAdapter,
  getRingCredentials,
  verifyRingWebhookSignature,
} from "rapid-cortex-integrations/ring";

export type {
  LinkedRingAccount,
  LinkedRingDevice,
  RingCameraListItem,
  RingConnectionStatus,
  RingDeviceType,
  RingEmergencyCameraRequest,
  RingEmergencyCameraSession,
  RingOAuthState,
  RingOAuthTokens,
  RingRequestDurationMinutes,
  RingRequestStatus,
  RingStreamStatus,
} from "rapid-cortex-integrations/ring";
