/**
 * Opportunity Intelligence watch seeds beyond the original transit list.
 * Persisted as WATCH#{id} on RAPID_IQ_PIPELINE_SIGNALS_TABLE (not a separate table).
 */

import type { RapidIqIntelMarket, RapidIqIntelWatch } from "./opportunity-intel-schemas.js";
import { RAPID_IQ_TRANSIT_WATCH_SEEDS, defaultTransitWatchKeywords } from "./transit-watches.js";

export type RapidIqVerticalWatchSeed = {
  id: string;
  market: RapidIqIntelMarket;
  name: string;
  agency: string;
  region: string;
  sourceUrls: string[];
  keywords: string[];
  minimumFitScore: number;
  preRfpFloor: number;
  webSearchEnabled: boolean;
  notes?: string;
};

export function sourceDomainsFromUrls(urls: readonly string[]): string[] {
  const domains = new Set<string>();
  for (const raw of urls) {
    try {
      const host = new URL(raw).hostname.replace(/^www\./i, "").toLowerCase();
      if (host) domains.add(host);
    } catch {
      /* skip invalid */
    }
  }
  domains.add("sam.gov");
  return [...domains];
}

export function verticalWatchSeedToIntelWatch(
  seed: RapidIqVerticalWatchSeed,
  now: string,
): RapidIqIntelWatch {
  return {
    id: seed.id,
    name: seed.name,
    agency: seed.agency,
    market: seed.market,
    enabled: true,
    keywords: seed.keywords,
    sourceDomains: sourceDomainsFromUrls(seed.sourceUrls),
    sourceUrls: [...seed.sourceUrls],
    minimumFitScore: seed.minimumFitScore,
    preRfpFloor: seed.preRfpFloor,
    webSearchEnabled: seed.webSearchEnabled,
    region: seed.region,
    notes: seed.notes,
    createdAt: now,
    updatedAt: now,
  };
}

function seed(
  partial: RapidIqVerticalWatchSeed,
): RapidIqVerticalWatchSeed {
  return partial;
}

const PSAP_KW = ["911", "PSAP", "emergency communications", "CAD", "dispatch", "NG911"];
const CAMPUS_KW = ["campus safety", "campus security", "emergency", "public safety", "RFP"];
const VENUE_KW = ["venue security", "crowd management", "event safety", "stadium security"];

export const PSAP_WATCH_SEEDS: RapidIqVerticalWatchSeed[] = [
  seed({
    id: "psap-dhs-fema-procurement",
    market: "PSAP",
    name: "DHS / FEMA Public Safety Procurement",
    agency: "DHS / FEMA Public Safety Procurement",
    region: "Federal",
    sourceUrls: [
      "https://www.fema.gov/grants/preparedness/emergency-communications",
      "https://www.dhs.gov/science-and-technology/procurement-solicitations",
    ],
    keywords: [...PSAP_KW, "ESInet"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "FEMA BRIC / SAFECOM / SCIP grants and DHS S&T solicitations",
  }),
  seed({
    id: "psap-firstnet-procurement",
    market: "PSAP",
    name: "FirstNet / AT&T FirstNet",
    agency: "FirstNet / AT&T FirstNet",
    region: "Federal",
    sourceUrls: [
      "https://www.firstnet.gov/procurement",
      "https://www.firstnet.gov/content/grant-funding",
    ],
    keywords: ["FirstNet", "public safety broadband", "PSAP", "911", "LTE", "dispatch"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-nena-procurement",
    market: "PSAP",
    name: "NENA — National Emergency Number Association",
    agency: "NENA — National Emergency Number Association",
    region: "National",
    sourceUrls: [
      "https://www.nena.org/page/Procurements",
      "https://www.nena.org/page/NG911_Now",
      "https://www.nena.org/page/RFP",
    ],
    keywords: ["911", "NG911", "PSAP", "ESInet", "i3", "MSAG", "GIS", "call handling"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "NENA posts member RFPs and industry procurement notices",
  }),
  seed({
    id: "psap-fulton-county-ga",
    market: "PSAP",
    name: "Fulton County Emergency Services (Atlanta)",
    agency: "Fulton County Emergency Services (Atlanta)",
    region: "Georgia",
    sourceUrls: [
      "https://www.fultoncountyga.gov/departments/purchasing/solicitations",
      "https://www.planetbids.com/portal/portal.cfm?CompanyID=27336",
    ],
    keywords: [...PSAP_KW, "public safety"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "Priority: home market",
  }),
  seed({
    id: "psap-gwinnett-county-ga",
    market: "PSAP",
    name: "Gwinnett County 911 / Public Safety",
    agency: "Gwinnett County 911 / Public Safety",
    region: "Georgia",
    sourceUrls: [
      "https://www.gwinnettcounty.com/web/gwinnett/departments/financialservices/purchasing/activesolicitationsandbids",
    ],
    keywords: ["911", "CAD", "emergency communications", "dispatch", "public safety software"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-cobb-county-ga",
    market: "PSAP",
    name: "Cobb County E-911",
    agency: "Cobb County E-911",
    region: "Georgia",
    sourceUrls: ["https://www.cobbcounty.org/finance/purchasing/bid-solicitations"],
    keywords: ["911", "dispatch", "CAD", "emergency communications", "PSAP"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-georgia-state-911",
    market: "PSAP",
    name: "Georgia Emergency Management and Homeland Security Agency",
    agency: "Georgia Emergency Management and Homeland Security Agency",
    region: "Georgia",
    sourceUrls: [
      "https://gema.georgia.gov/911-program",
      "https://doas.ga.gov/state-purchasing/active-solicitations",
    ],
    keywords: [...PSAP_KW, "ESInet", "statewide"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "Georgia statewide NG911 procurement — high priority",
  }),
  seed({
    id: "psap-harris-county-tx",
    market: "PSAP",
    name: "Harris County Emergency Services (Houston)",
    agency: "Harris County Emergency Services (Houston)",
    region: "Texas",
    sourceUrls: ["https://www.harriscountytx.gov/departments/purchasing/bids-rfps"],
    keywords: [...PSAP_KW, "public safety"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-dallas-county-tx",
    market: "PSAP",
    name: "Dallas County Emergency Communications",
    agency: "Dallas County Emergency Communications",
    region: "Texas",
    sourceUrls: ["https://www.dallascounty.org/departments/purchasing/rfp.php"],
    keywords: ["911", "emergency communications", "dispatch", "CAD", "public safety platform"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-texas-state-911",
    market: "PSAP",
    name: "Texas 9-1-1 Alliance / Texas DPS",
    agency: "Texas 9-1-1 Alliance / Texas DPS",
    region: "Texas",
    sourceUrls: ["https://www.texas911.org/procurement", "https://www.txsmartbuy.gov/sp"],
    keywords: [...PSAP_KW, "ESInet", "Texas"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-miami-dade-fl",
    market: "PSAP",
    name: "Miami-Dade County 911 / Public Safety",
    agency: "Miami-Dade County 911 / Public Safety",
    region: "Florida",
    sourceUrls: ["https://www.miamidade.gov/procurement/open-solicitations.asp"],
    keywords: [...PSAP_KW, "public safety"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-broward-county-fl",
    market: "PSAP",
    name: "Broward County Emergency Communications",
    agency: "Broward County Emergency Communications",
    region: "Florida",
    sourceUrls: ["https://www.broward.org/Purchasing/Pages/BidsSolicitations.aspx"],
    keywords: ["911", "dispatch", "emergency communications", "CAD", "public safety software"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-florida-state-911",
    market: "PSAP",
    name: "Florida Division of Emergency Management / E911",
    agency: "Florida Division of Emergency Management / E911",
    region: "Florida",
    sourceUrls: [
      "https://www.floridadisaster.org/dem/e911/",
      "https://www.myfloridamarketplace.com/bids",
    ],
    keywords: ["911", "NG911", "PSAP", "ESInet", "emergency communications", "Florida"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-cook-county-il",
    market: "PSAP",
    name: "Cook County OEMC / Chicago 911",
    agency: "Cook County OEMC / Chicago 911",
    region: "Illinois",
    sourceUrls: [
      "https://www.cookcountyil.gov/agency/bureau-of-finance/bids-contracts",
      "https://www.chicago.gov/city/en/depts/dps/provdrs/main.html",
    ],
    keywords: [...PSAP_KW, "public safety"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-franklin-county-oh",
    market: "PSAP",
    name: "Franklin County Emergency Management (Columbus OH)",
    agency: "Franklin County Emergency Management (Columbus OH)",
    region: "Ohio",
    sourceUrls: ["https://www.franklincountyohio.gov/Commissioners/Purchasing/Bid-Notices"],
    keywords: ["911", "CAD", "dispatch", "emergency communications", "public safety"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-la-county-ca",
    market: "PSAP",
    name: "Los Angeles County Sheriff / OES",
    agency: "Los Angeles County Sheriff / OES",
    region: "California",
    sourceUrls: [
      "https://camisvr.co.la.ca.us/lacobids/BidSearch/BidList",
      "https://bids.lacounty.gov",
    ],
    keywords: ["911", "PSAP", "CAD", "emergency communications", "dispatch", "public safety platform"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "psap-king-county-wa",
    market: "PSAP",
    name: "King County E-911 Program Office (Seattle)",
    agency: "King County E-911 Program Office (Seattle)",
    region: "Washington",
    sourceUrls: [
      "https://kingcounty.gov/depts/finance-business-operations/procurement/for-business/solicitations.aspx",
      "https://www.kingcounty.gov/services/programs/e911.aspx",
    ],
    keywords: ["911", "NG911", "PSAP", "CAD", "ESInet", "emergency communications"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "King County is an active NG911 upgrader",
  }),
];

export const CAMPUS_WATCH_SEEDS: RapidIqVerticalWatchSeed[] = [
  seed({
    id: "campus-iaclea",
    market: "CAMPUS",
    name: "IACLEA — International Association of Campus Law Enforcement",
    agency: "IACLEA — International Association of Campus Law Enforcement",
    region: "National",
    sourceUrls: ["https://www.iaclea.org/resources/", "https://www.iaclea.org/procurement/"],
    keywords: [...CAMPUS_KW, "university", "higher education"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "IACLEA posts member procurement notices; 1,000+ member institutions",
  }),
  seed({
    id: "campus-uga",
    market: "CAMPUS",
    name: "University of Georgia — Procurement",
    agency: "University of Georgia — Procurement",
    region: "Georgia",
    sourceUrls: ["https://busfin.uga.edu/procurement/purchasing/bids-rfps/"],
    keywords: [...CAMPUS_KW, "software"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "Active RC tenant — monitor for expansion or competitive displacement",
  }),
  seed({
    id: "campus-georgia-tech",
    market: "CAMPUS",
    name: "Georgia Institute of Technology — Procurement",
    agency: "Georgia Institute of Technology — Procurement",
    region: "Georgia",
    sourceUrls: ["https://procurement.gatech.edu/open-solicitations"],
    keywords: ["campus safety", "campus security", "emergency communications", "software", "public safety"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "campus-ut-system",
    market: "CAMPUS",
    name: "University of Texas System — Procurement",
    agency: "University of Texas System — Procurement",
    region: "Texas",
    sourceUrls: [
      "https://www.utsystem.edu/offices/procurement/bids-rfps",
      "https://www.utexas.edu/procurement/solicitations",
    ],
    keywords: [...CAMPUS_KW, "university"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "UT System covers 13 institutions — system-wide contracts are high value",
  }),
  seed({
    id: "campus-uc-system",
    market: "CAMPUS",
    name: "University of California System — Procurement",
    agency: "University of California System — Procurement",
    region: "California",
    sourceUrls: [
      "https://www.ucop.edu/procurement-services/for-vendors/opportunities.html",
      "https://supplier.ucop.edu/bids/",
    ],
    keywords: ["campus safety", "campus police", "emergency communications", "public safety", "university security"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "UC System has 10 campuses + medical centers; system-level procurement",
  }),
  seed({
    id: "campus-ucf",
    market: "CAMPUS",
    name: "University of Central Florida — Procurement",
    agency: "University of Central Florida — Procurement",
    region: "Florida",
    sourceUrls: [
      "https://bids.sciquest.com/apps/Router/PublicEvent?CustomerOrg=UCF",
      "https://www.ucf.edu/administration/procurement/",
    ],
    keywords: [...CAMPUS_KW, "software"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "UCF — largest single-campus enrollment in US; high-priority campus target",
  }),
  seed({
    id: "campus-fsu",
    market: "CAMPUS",
    name: "Florida State University — Procurement",
    agency: "Florida State University — Procurement",
    region: "Florida",
    sourceUrls: ["https://procurement.fsu.edu/solicitations/"],
    keywords: ["campus safety", "campus security", "emergency", "public safety", "software platform"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "campus-ohio-state",
    market: "CAMPUS",
    name: "Ohio State University — Procurement",
    agency: "Ohio State University — Procurement",
    region: "Ohio",
    sourceUrls: [
      "https://procurement.osu.edu/solicitations",
      "https://vendor.osu.edu/solicitations",
    ],
    keywords: [...CAMPUS_KW, "dispatch", "software"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "campus-michigan-state",
    market: "CAMPUS",
    name: "Michigan State University — Procurement",
    agency: "Michigan State University — Procurement",
    region: "Michigan",
    sourceUrls: ["https://procurement.msu.edu/bidding/current-bids/"],
    keywords: ["campus safety", "campus security", "emergency communications", "public safety software"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "Post-Nassar-era campus safety investment is ongoing at MSU",
  }),
  seed({
    id: "campus-penn-state",
    market: "CAMPUS",
    name: "Penn State University — Procurement",
    agency: "Penn State University — Procurement",
    region: "Pennsylvania",
    sourceUrls: [
      "https://guru.psu.edu/RFx/",
      "https://www.psu.edu/business/procurement-services/",
    ],
    keywords: [...CAMPUS_KW, "software"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "campus-csu-system",
    market: "CAMPUS",
    name: "California State University System — Procurement",
    agency: "California State University System — Procurement",
    region: "California",
    sourceUrls: [
      "https://www.calstate.edu/csu-system/administration/business-finance-services/cpdc/rfp/",
    ],
    keywords: ["campus safety", "campus security", "emergency communications", "public safety software", "university"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "CSU has 23 campuses — system contracts are large",
  }),
  seed({
    id: "campus-university-alabama",
    market: "CAMPUS",
    name: "University of Alabama System — Procurement",
    agency: "University of Alabama System — Procurement",
    region: "Alabama",
    sourceUrls: ["https://www.uasystem.edu/procurement/solicitations/"],
    keywords: [...CAMPUS_KW],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "campus-unc-system",
    market: "CAMPUS",
    name: "UNC System / NC State — Procurement",
    agency: "UNC System / NC State — Procurement",
    region: "North Carolina",
    sourceUrls: [
      "https://www.northcarolina.edu/procurement/",
      "https://procurement.oasis.ncsu.edu/sap/bc/webdynpro/sap/zncsu_esop_bidder",
    ],
    keywords: ["campus safety", "campus security", "emergency communications", "public safety", "software"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
];

export const VENUE_WATCH_SEEDS: RapidIqVerticalWatchSeed[] = [
  seed({
    id: "venue-asm-global",
    market: "VENUE",
    name: "ASM Global — Venue Operations & Procurement",
    agency: "ASM Global — Venue Operations & Procurement",
    region: "National",
    sourceUrls: ["https://www.asmglobal.com/vendors/", "https://www.asmglobal.com/procurement/"],
    keywords: [...VENUE_KW, "arena safety", "RFP"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "ASM Global manages 350+ venues worldwide",
  }),
  seed({
    id: "venue-aeg-global",
    market: "VENUE",
    name: "AEG — Anschutz Entertainment Group",
    agency: "AEG — Anschutz Entertainment Group",
    region: "National",
    sourceUrls: ["https://www.aegpresents.com/procurement/", "https://www.aeg.com/procurement"],
    keywords: [...VENUE_KW, "arena", "security software"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "venue-mercedes-benz-stadium",
    market: "VENUE",
    name: "Mercedes-Benz Stadium (Atlanta Falcons / Atlanta United)",
    agency: "Mercedes-Benz Stadium (Atlanta Falcons / Atlanta United)",
    region: "Georgia",
    sourceUrls: [
      "https://www.mercedesbenzstadium.com/procurement/",
      "https://www.atlantafalcons.com/community/stadium/procurement",
    ],
    keywords: [...VENUE_KW, "incident management"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "Home market priority. ASM Global managed.",
  }),
  seed({
    id: "venue-sofi-stadium",
    market: "VENUE",
    name: "SoFi Stadium (LA Rams / LA Chargers)",
    agency: "SoFi Stadium (LA Rams / LA Chargers)",
    region: "California",
    sourceUrls: ["https://www.sofistadium.com/procurement/"],
    keywords: [...VENUE_KW, "security software"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "LA28 Olympics venue.",
  }),
  seed({
    id: "venue-allegiant-stadium",
    market: "VENUE",
    name: "Allegiant Stadium (Las Vegas Raiders)",
    agency: "Allegiant Stadium (Las Vegas Raiders)",
    region: "Nevada",
    sourceUrls: ["https://www.allegiantstadium.com/procurement/"],
    keywords: [...VENUE_KW, "incident", "security platform"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "venue-att-stadium-dallas",
    market: "VENUE",
    name: "AT&T Stadium (Dallas Cowboys)",
    agency: "AT&T Stadium (Dallas Cowboys)",
    region: "Texas",
    sourceUrls: ["https://attstadium.com/procurement/", "https://www.dallascowboys.com/procurement"],
    keywords: [...VENUE_KW, "security software", "RFP"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "venue-metlife-stadium",
    market: "VENUE",
    name: "MetLife Stadium (NY Giants / NY Jets)",
    agency: "MetLife Stadium (NY Giants / NY Jets)",
    region: "New Jersey",
    sourceUrls: ["https://www.metlifestadium.com/stadium-info/procurement"],
    keywords: ["venue security", "stadium", "crowd management", "event safety", "security platform"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "Super Bowl LX venue (2026).",
  }),
  seed({
    id: "venue-hard-rock-stadium",
    market: "VENUE",
    name: "Hard Rock Stadium (Miami Dolphins)",
    agency: "Hard Rock Stadium (Miami Dolphins)",
    region: "Florida",
    sourceUrls: ["https://www.hardrockstadium.com/procurement/"],
    keywords: [...VENUE_KW, "security software"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "venue-raymond-james-tampa",
    market: "VENUE",
    name: "Raymond James Stadium (Tampa Bay Buccaneers)",
    agency: "Raymond James Stadium (Tampa Bay Buccaneers)",
    region: "Florida",
    sourceUrls: ["https://www.raymondjamesstadium.com/procurement"],
    keywords: [...VENUE_KW],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "venue-lumen-field-seattle",
    market: "VENUE",
    name: "Lumen Field (Seattle Seahawks / Sounders)",
    agency: "Lumen Field (Seattle Seahawks / Sounders)",
    region: "Washington",
    sourceUrls: [
      "https://www.soundersfc.com/lumen-field/procurement",
      "https://www.seahawks.com/stadium/procurement",
    ],
    keywords: [...VENUE_KW, "security software"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "venue-georgia-world-congress",
    market: "VENUE",
    name: "Georgia World Congress Center Authority",
    agency: "Georgia World Congress Center Authority",
    region: "Georgia",
    sourceUrls: [
      "https://www.gwcca.org/about/business-opportunities/",
      "https://www.gwcca.org/procurement/",
    ],
    keywords: [...VENUE_KW, "security software", "incident management", "RFP"],
    minimumFitScore: 6,
    preRfpFloor: 5,
    webSearchEnabled: true,
    notes: "Home market. GWCC is a state authority — procurement is public.",
  }),
  seed({
    id: "venue-mccormick-place-chicago",
    market: "VENUE",
    name: "Metropolitan Pier and Exposition Authority (McCormick Place)",
    agency: "Metropolitan Pier and Exposition Authority (McCormick Place)",
    region: "Illinois",
    sourceUrls: [
      "https://www.mpea.com/business/procurement/",
      "https://www.mpea.com/about/vendors-suppliers/",
    ],
    keywords: [...VENUE_KW, "convention center", "security software"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
  seed({
    id: "venue-javits-center-nyc",
    market: "VENUE",
    name: "Jacob K. Javits Convention Center",
    agency: "Jacob K. Javits Convention Center",
    region: "New York",
    sourceUrls: ["https://www.javitscenter.com/about/procurement/"],
    keywords: [...VENUE_KW, "security software", "incident", "RFP"],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: true,
  }),
];

export const VERTICAL_INTEL_WATCH_SEEDS: RapidIqVerticalWatchSeed[] = [
  ...PSAP_WATCH_SEEDS,
  ...CAMPUS_WATCH_SEEDS,
  ...VENUE_WATCH_SEEDS,
];

export const VERTICAL_WATCH_SEED_SUMMARY = {
  psap: PSAP_WATCH_SEEDS.length,
  campus: CAMPUS_WATCH_SEEDS.length,
  venue: VENUE_WATCH_SEEDS.length,
  transit: RAPID_IQ_TRANSIT_WATCH_SEEDS.length,
  verticalNew: VERTICAL_INTEL_WATCH_SEEDS.length,
} as const;

export function allIntelWatchRecords(now: string): RapidIqIntelWatch[] {
  const transitKw = defaultTransitWatchKeywords();
  const transit: RapidIqIntelWatch[] = RAPID_IQ_TRANSIT_WATCH_SEEDS.map((seed) => ({
    id: seed.id,
    name: seed.name,
    agency: seed.agency,
    market: "TRANSIT" as const,
    enabled: true,
    keywords: transitKw,
    sourceDomains: [...seed.sourceDomains],
    sourceUrls: [...seed.sourceUrls],
    minimumFitScore: 7,
    preRfpFloor: 5,
    webSearchEnabled: false,
    createdAt: now,
    updatedAt: now,
  }));
  return [...transit, ...VERTICAL_INTEL_WATCH_SEEDS.map((s) => verticalWatchSeedToIntelWatch(s, now))];
}
