export const VOICE_ERROR_CODES = {
  LANG_DETECT_TIMEOUT: "LANG_DETECT_TIMEOUT",
  LANG_DETECT_LOW_CONFIDENCE: "LANG_DETECT_LOW_CONFIDENCE",
  STT_TIMEOUT: "STT_TIMEOUT",
  STT_RATE_LIMIT: "STT_RATE_LIMIT",
  STT_AUTH_ERROR: "STT_AUTH_ERROR",
  STT_PROVIDER_5XX: "STT_PROVIDER_5XX",
  STT_INVALID_RESPONSE: "STT_INVALID_RESPONSE",
  STT_ALL_PROVIDERS_FAILED: "STT_ALL_PROVIDERS_FAILED",
  TRANSLATION_TIMEOUT: "TRANSLATION_TIMEOUT",
  TRANSLATION_RATE_LIMIT: "TRANSLATION_RATE_LIMIT",
  TRANSLATION_AUTH_ERROR: "TRANSLATION_AUTH_ERROR",
  TRANSLATION_PROVIDER_5XX: "TRANSLATION_PROVIDER_5XX",
  TRANSLATION_INVALID_RESPONSE: "TRANSLATION_INVALID_RESPONSE",
  TRANSLATION_ALL_PROVIDERS_FAILED: "TRANSLATION_ALL_PROVIDERS_FAILED",
  PROVIDER_CONFIG_ERROR: "PROVIDER_CONFIG_ERROR",
  UNKNOWN_PROVIDER_ERROR: "UNKNOWN_PROVIDER_ERROR",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  UNSUPPORTED_LANGUAGE: "UNSUPPORTED_LANGUAGE",
} as const;

export type VoiceErrorCode = (typeof VOICE_ERROR_CODES)[keyof typeof VOICE_ERROR_CODES];
