#!/usr/bin/env bash
# Source before `npm run dev:web` to turn on all NEXT_PUBLIC_ENABLE_* gates for test-agency / rcsuperadmin QA.
# Example: source scripts/env-web-pilot-test.sh && npm run dev:web -w rapid-cortex-web
set -euo pipefail

export NEXT_PUBLIC_ENABLE_PILOT_TEST_MODE=1
export NEXT_PUBLIC_APP_ENV=development

export NEXT_PUBLIC_ENABLE_QA_SCORING=1
export NEXT_PUBLIC_ENABLE_REPORTS=1
export NEXT_PUBLIC_ENABLE_SLA_BACKLOG=1
export NEXT_PUBLIC_ENABLE_WAR_ROOMS=1
export NEXT_PUBLIC_ENABLE_STAKEHOLDER_PAGES=1
export NEXT_PUBLIC_ENABLE_POST_INCIDENT_REVIEWS=1
export NEXT_PUBLIC_ENABLE_INCIDENT_MEDIA=1
export NEXT_PUBLIC_ENABLE_CALLER_MEDIA=1
export NEXT_PUBLIC_ENABLE_LIVE_VIDEO=1
export NEXT_PUBLIC_ENABLE_SOP_PROTOCOL_AI=1
export NEXT_PUBLIC_ENABLE_NON_EMERGENCY_TRIAGE=1
export NEXT_PUBLIC_ENABLE_DISPATCHER_WELLNESS=1
export NEXT_PUBLIC_ENABLE_CALLER_CARD=1
export NEXT_PUBLIC_ENABLE_SUPERVISOR_PERFORMANCE=1
export NEXT_PUBLIC_ENABLE_ADMIN_ANALYTICS=1
export NEXT_PUBLIC_ENABLE_CROSS_JURISDICTION_SHARES=1
export NEXT_PUBLIC_ENABLE_SEO_INTELLIGENCE=1
export NEXT_PUBLIC_ENABLE_DECEPTION_SHIELD_UI=1
export NEXT_PUBLIC_ENABLE_CAD_ADMIN=1
export NEXT_PUBLIC_ENABLE_CAD_WRITEBACK=1
export NEXT_PUBLIC_ENABLE_SILENT_TEXT=1
export NEXT_PUBLIC_ENABLE_PINPOINT=1
export NEXT_PUBLIC_ENABLE_SURGE=1
export NEXT_PUBLIC_ENABLE_EMERGENCY_CONNECT=1
export NEXT_PUBLIC_ENABLE_HOSPITAL_ROUTING=1
export NEXT_PUBLIC_ENABLE_HOSPITAL_PORTAL=1
export NEXT_PUBLIC_ENABLE_CALL_CONTROL=1
export NEXT_PUBLIC_ENABLE_NETWORK_ACCESS=1
export NEXT_PUBLIC_ENABLE_VENUE_INTELLIGENCE=1
export NEXT_PUBLIC_ENABLE_CONNECT_RING=true
export NEXT_PUBLIC_ENABLE_CONNECT_RING_AVAILABLE_CAMERAS=true
export NEXT_PUBLIC_ENABLE_CONNECT_RING_EMERGENCY_REQUESTS=true

echo "[env-web-pilot-test] Pilot test mode + feature flags exported."
