/**
 * Label → canonical feature id for public comparison table tooltips.
 * No imports so tests can load this without Next.js path aliases.
 */
export const PRICING_COMPARISON_ROW_FEATURE_IDS: Record<string, string> = {
  "Web application access": "web_application_access",
  "Desktop application access": "desktop_application_access",
  "Role-based access control": "role_based_access_control",
  "Agency admin console": "agency_admin_console",
  "Core reporting": "core_reporting",
  "Audit logs": "audit_logs",
  "AI-assisted intake": "ai_assisted_intake",
  "Live transcription": "live_transcription",
  "Call triage workflows": "call_triage_workflows",
  "Call / session history": "call_session_history",
  "Active incident view": "active_incident_view",
  "Dispatcher console": "dispatcher_console",
  "Channel / talk group monitoring": "channel_talk_group_monitoring",
  "Non-emergency intake queue": "non_emergency_intake_queue",
  "Backlog and SLA tracking": "backlog_sla_tracking",
  "Multilingual intake": "multilingual_intake",
  "Live translation": "live_translation",
  "Text-to-voice support": "text_to_voice_support",
  "Language auto-detection": "language_auto_detection",
  "Text-based multilingual workflows": "text_based_multilingual_workflows",
  "Caller photo upload": "caller_photo_upload",
  "Caller video upload": "caller_video_upload",
  "Live caller media streaming": "live_caller_media_streaming",
  "Media audit trail": "media_audit_trail",
  "Retention controls": "retention_controls",
  "QA review tools": "qa_review_tools",
  Scorecards: "scorecards",
  "Coaching notes": "coaching_notes",
  "Team performance dashboards": "team_performance_dashboards",
  "Call quality trends": "call_quality_trends",
  "Major incident management": "major_incident_management",
  "Command dashboard": "command_dashboard",
  "War rooms": "war_rooms",
  "Runbooks / playbooks": "runbooks_playbooks",
  "Incident timeline reconstruction": "incident_timeline_reconstruction",
  "Post-incident reviews": "post_incident_reviews",
  "Stakeholder status pages": "stakeholder_status_pages",
  "Monitoring integrations": "monitoring_integrations",
  "Alert correlation": "alert_correlation",
  "Escalation engine": "escalation_engine",
  "On-call routing": "on_call_routing",
  "SLO dashboards": "slo_dashboards",
  "Reliability reporting": "reliability_reporting",
  "Standard onboarding": "standard_onboarding",
  "Premium onboarding": "premium_onboarding",
  "Integration assistance": "integration_assistance",
  "Priority support": "priority_support",
  "Dedicated rollout planning": "dedicated_rollout_planning",
  "Multi-site deployment support": "multi_site_deployment_support",
  "Custom security / compliance review": "custom_security_compliance_review",
  "LiveLocation caller location (SMS GPS link)": "livelocation_secure_caller_share",
  "Surge View duplicate-call clustering": "surge_view_related_calls",
  "Operational maps (Mapbox workspace)": "operational_maps_mapbox",
  "Multi-vendor CAD adapter framework": "cad_vendor_adapter",
  "Low-latency CAD delivery (vendor + deployment)": "cad_delivery_latency_profiles",
  "Unit overlays on maps (when AVL / CAD exposes positions)": "cad_map_unit_overlay",
};
