import type { VenueCamera, VenueIncident, VenueStaffMember, VenueZone } from "./venue-types";

const now = Date.now();
const isoMinutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

export const FIXTURE_INCIDENTS: VenueIncident[] = [
  {
    id: "MBS-2026-000241",
    venueCode: "MBS",
    zoneCode: "RC201",
    zoneLabel: "Section 101 — Gate A",
    qrRcli: "RCLI-MBS-000001",
    qrLocationName: "Section 101 — Gate A",
    type: "medical",
    source: "qr",
    status: "open",
    description: "Guest reports possible dehydration and dizziness near row 11.",
    confidence: "high",
    assignedTo: null,
    cameraRefs: ["CAM-124-N", "CAM-124-S"],
    hasMedia: true,
    createdAt: isoMinutesAgo(8),
    updatedAt: isoMinutesAgo(4),
    resolvedAt: null,
  },
  {
    id: "MBS-2026-000242",
    venueCode: "MBS",
    zoneCode: "S210",
    zoneLabel: "Section 210",
    type: "security",
    source: "sms",
    status: "assigned",
    description: "Report of verbal altercation in aisle between rows 4-6.",
    confidence: "medium",
    assignedTo: "Mia Thompson",
    cameraRefs: ["CAM-210-E", "CAM-210-W"],
    hasMedia: false,
    createdAt: isoMinutesAgo(17),
    updatedAt: isoMinutesAgo(10),
    resolvedAt: null,
  },
  {
    id: "MBS-2026-000243",
    venueCode: "MBS",
    zoneCode: "RC202",
    zoneLabel: "Concourse C — Food Court",
    qrRcli: "RCLI-MBS-000002",
    qrLocationName: "Concourse C — Food Court",
    type: "lost_person",
    source: "qr",
    status: "responding",
    description: "Parent cannot locate 9-year-old near Gate B screening lane.",
    confidence: "high",
    assignedTo: "Jordan Blake",
    cameraRefs: ["CAM-GB-ENT", "CAM-GB-TURN"],
    hasMedia: false,
    createdAt: isoMinutesAgo(26),
    updatedAt: isoMinutesAgo(7),
    resolvedAt: null,
  },
  {
    id: "MBS-2026-000244",
    venueCode: "MBS",
    zoneCode: "C3",
    zoneLabel: "Concourse 3",
    type: "maintenance",
    source: "manual",
    status: "assigned",
    description: "Spilled beverage causing slip hazard near concession stand C3-14.",
    confidence: "medium",
    assignedTo: "Facilities Team Alpha",
    cameraRefs: ["CAM-C3-E", "CAM-C3-W"],
    hasMedia: true,
    createdAt: isoMinutesAgo(39),
    updatedAt: isoMinutesAgo(21),
    resolvedAt: null,
  },
  {
    id: "MBS-2026-000245",
    venueCode: "MBS",
    zoneCode: "S301",
    zoneLabel: "Section 301",
    type: "guest_services",
    source: "qr",
    status: "open",
    description: "Wheelchair assistance requested for guest needing escort to elevator.",
    confidence: "high",
    assignedTo: null,
    cameraRefs: ["CAM-301-N"],
    hasMedia: false,
    createdAt: isoMinutesAgo(53),
    updatedAt: isoMinutesAgo(44),
    resolvedAt: null,
  },
  {
    id: "MBS-2026-000246",
    venueCode: "MBS",
    zoneCode: "G-A",
    zoneLabel: "Gate A Entrance",
    type: "security",
    source: "sms",
    status: "responding",
    description: "Possible fake ticket dispute at turnstile lane 4.",
    confidence: "medium",
    assignedTo: "Sgt. Avery Cole",
    cameraRefs: ["CAM-GA-ENT", "CAM-GA-LOBBY"],
    hasMedia: false,
    createdAt: isoMinutesAgo(68),
    updatedAt: isoMinutesAgo(12),
    resolvedAt: null,
  },
  {
    id: "MBS-2026-000247",
    venueCode: "MBS",
    zoneCode: "S108",
    zoneLabel: "Section 108",
    type: "medical",
    source: "qr",
    status: "resolved",
    description: "Minor trip-and-fall treated on-site by medic team.",
    confidence: "high",
    assignedTo: "Medic Unit 2",
    cameraRefs: ["CAM-108-N", "CAM-108-S"],
    hasMedia: true,
    createdAt: isoMinutesAgo(94),
    updatedAt: isoMinutesAgo(41),
    resolvedAt: isoMinutesAgo(37),
  },
  {
    id: "MBS-2026-000248",
    venueCode: "MBS",
    zoneCode: "FIELD",
    zoneLabel: "Field Level Tunnel",
    type: "security",
    source: "sms",
    status: "escalated",
    description: "Unauthorized access attempt toward restricted tunnel checkpoint.",
    confidence: "high",
    assignedTo: "Command Lead",
    cameraRefs: ["CAM-FIELD-1", "CAM-FIELD-2"],
    hasMedia: true,
    createdAt: isoMinutesAgo(112),
    updatedAt: isoMinutesAgo(19),
    resolvedAt: null,
  },
];

export const FIXTURE_ZONES: VenueZone[] = [
  { id: "zone-101", venueCode: "MBS", code: "S101", label: "Section 101", level: "Lower Bowl", cameraIds: ["CAM-101-N"], qrUrl: "/report/MBS/S101", activeIncidents: 0 },
  { id: "zone-108", venueCode: "MBS", code: "S108", label: "Section 108", level: "Lower Bowl", cameraIds: ["CAM-108-N", "CAM-108-S"], qrUrl: "/report/MBS/S108", activeIncidents: 0 },
  { id: "zone-124", venueCode: "MBS", code: "S124", label: "Section 124", level: "Lower Bowl", cameraIds: ["CAM-124-N", "CAM-124-S"], qrUrl: "/report/MBS/S124", activeIncidents: 1 },
  { id: "zone-210", venueCode: "MBS", code: "S210", label: "Section 210", level: "Club Level", cameraIds: ["CAM-210-E", "CAM-210-W"], qrUrl: "/report/MBS/S210", activeIncidents: 1 },
  { id: "zone-301", venueCode: "MBS", code: "S301", label: "Section 301", level: "Upper Bowl", cameraIds: ["CAM-301-N"], qrUrl: "/report/MBS/S301", activeIncidents: 1 },
  { id: "zone-ga", venueCode: "MBS", code: "G-A", label: "Gate A", level: "Perimeter", cameraIds: ["CAM-GA-ENT", "CAM-GA-LOBBY"], qrUrl: "/report/MBS/G-A", activeIncidents: 1 },
  { id: "zone-gb", venueCode: "MBS", code: "G-B", label: "Gate B", level: "Perimeter", cameraIds: ["CAM-GB-ENT", "CAM-GB-TURN"], qrUrl: "/report/MBS/G-B", activeIncidents: 1 },
  { id: "zone-gc", venueCode: "MBS", code: "G-C", label: "Gate C", level: "Perimeter", cameraIds: ["CAM-GC-ENT"], qrUrl: "/report/MBS/G-C", activeIncidents: 0 },
  { id: "zone-gd", venueCode: "MBS", code: "G-D", label: "Gate D", level: "Perimeter", cameraIds: ["CAM-GD-ENT"], qrUrl: "/report/MBS/G-D", activeIncidents: 0 },
  { id: "zone-c1", venueCode: "MBS", code: "C1", label: "Concourse 1", level: "Main Concourse", cameraIds: ["CAM-C1-E"], qrUrl: "/report/MBS/C1", activeIncidents: 0 },
  { id: "zone-c3", venueCode: "MBS", code: "C3", label: "Concourse 3", level: "Main Concourse", cameraIds: ["CAM-C3-E", "CAM-C3-W"], qrUrl: "/report/MBS/C3", activeIncidents: 1 },
  { id: "zone-field", venueCode: "MBS", code: "FIELD", label: "Field Level", level: "Restricted", cameraIds: ["CAM-FIELD-1", "CAM-FIELD-2"], qrUrl: "/report/MBS/FIELD", activeIncidents: 1 },
];

export const FIXTURE_CAMERAS: VenueCamera[] = [
  { id: "CAM-101-N", name: "Section 101 North", zoneCode: "S101", status: "online", streamUrl: "kvs://mbs/101-n" },
  { id: "CAM-108-N", name: "Section 108 North", zoneCode: "S108", status: "online", streamUrl: "kvs://mbs/108-n" },
  { id: "CAM-108-S", name: "Section 108 South", zoneCode: "S108", status: "online", streamUrl: "kvs://mbs/108-s" },
  { id: "CAM-124-N", name: "Section 124 North", zoneCode: "S124", status: "online", streamUrl: "kvs://mbs/124-n" },
  { id: "CAM-124-S", name: "Section 124 South", zoneCode: "S124", status: "degraded", streamUrl: "kvs://mbs/124-s" },
  { id: "CAM-210-E", name: "Section 210 East", zoneCode: "S210", status: "online", streamUrl: "kvs://mbs/210-e" },
  { id: "CAM-210-W", name: "Section 210 West", zoneCode: "S210", status: "online", streamUrl: "kvs://mbs/210-w" },
  { id: "CAM-301-N", name: "Section 301 North", zoneCode: "S301", status: "offline", streamUrl: null },
  { id: "CAM-GA-ENT", name: "Gate A Entrance", zoneCode: "G-A", status: "online", streamUrl: "kvs://mbs/gate-a" },
  { id: "CAM-GA-LOBBY", name: "Gate A Lobby", zoneCode: "G-A", status: "online", streamUrl: "kvs://mbs/gate-a-lobby" },
  { id: "CAM-GB-ENT", name: "Gate B Entrance", zoneCode: "G-B", status: "online", streamUrl: "kvs://mbs/gate-b" },
  { id: "CAM-GB-TURN", name: "Gate B Turnstiles", zoneCode: "G-B", status: "online", streamUrl: "kvs://mbs/gate-b-turn" },
  { id: "CAM-C1-E", name: "Concourse 1 East", zoneCode: "C1", status: "online", streamUrl: "kvs://mbs/c1-e" },
  { id: "CAM-C3-E", name: "Concourse 3 East", zoneCode: "C3", status: "degraded", streamUrl: "kvs://mbs/c3-e" },
  { id: "CAM-C3-W", name: "Concourse 3 West", zoneCode: "C3", status: "online", streamUrl: "kvs://mbs/c3-w" },
  { id: "CAM-FIELD-1", name: "Field Tunnel 1", zoneCode: "FIELD", status: "offline", streamUrl: null },
];

export const FIXTURE_STAFF: VenueStaffMember[] = [
  { id: "staff-001", name: "Mia Thompson", role: "security", status: "responding", currentIncidentId: "MBS-2026-000242", zone: "S210" },
  { id: "staff-002", name: "Jordan Blake", role: "security", status: "responding", currentIncidentId: "MBS-2026-000243", zone: "G-B" },
  { id: "staff-003", name: "Sgt. Avery Cole", role: "supervisor", status: "responding", currentIncidentId: "MBS-2026-000246", zone: "G-A" },
  { id: "staff-004", name: "Noah Ramirez", role: "security", status: "available", currentIncidentId: null, zone: "S124" },
  { id: "staff-005", name: "Priya Shah", role: "security", status: "available", currentIncidentId: null, zone: "S101" },
  { id: "staff-006", name: "Elena Park", role: "guest_services", status: "responding", currentIncidentId: "MBS-2026-000245", zone: "S301" },
  { id: "staff-007", name: "Liam Carter", role: "security", status: "responding", currentIncidentId: "MBS-2026-000248", zone: "FIELD" },
  { id: "staff-008", name: "Taylor Brooks", role: "supervisor", status: "available", currentIncidentId: null, zone: "C1" },
  { id: "staff-009", name: "Renee Watson", role: "guest_services", status: "available", currentIncidentId: null, zone: "G-D" },
  { id: "staff-010", name: "Carlos Diaz", role: "security", status: "off_duty", currentIncidentId: null, zone: null },
];

export function getFixtureIncident(id: string): VenueIncident | undefined {
  return FIXTURE_INCIDENTS.find((incident) => incident.id === id);
}
