import type { JurisdictionSeed, ScanTier } from "./jurisdiction-registry.js";

/**
 * University systems + flagship / large-enrollment campuses.
 * Enrollment is used as the population proxy for tiering.
 */
export const UNIVERSITY_JURISDICTIONS: JurisdictionSeed[] = [
  // ── UNIVERSITY SYSTEMS (Tier 0) ──────────────────────────────────────────
  {
    jurisdictionId: "university_system#GA#usg",
    type: "university_system",
    name: "University System of Georgia",
    stateCode: "GA",
    stateName: "Georgia",
    population: 340000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "26 institutions — board meeting covers all campuses. Primary RC market.",
    agendaBaseUrl: "https://www.usg.edu",
    agendaPathHints: ["/board/meeting-materials", "/board/agendas", "/board/minutes"],
  },
  {
    jurisdictionId: "university_system#AL#ua-system",
    type: "university_system",
    name: "University of Alabama System",
    stateCode: "AL",
    stateName: "Alabama",
    population: 75000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "UA Tuscaloosa, UAB, UAH — system-level procurement",
    agendaBaseUrl: "https://www.uasystem.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },
  {
    jurisdictionId: "university_system#FL#sus",
    type: "university_system",
    name: "Florida Board of Governors (State University System)",
    stateCode: "FL",
    stateName: "Florida",
    population: 430000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "12 universities — FL Board of Governors covers all",
    agendaBaseUrl: "https://www.flbog.edu",
    agendaPathHints: ["/board/agendas", "/meetings"],
  },
  {
    jurisdictionId: "university_system#TX#ut-system",
    type: "university_system",
    name: "University of Texas System",
    stateCode: "TX",
    stateName: "Texas",
    population: 240000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "13 institutions — system-level technology contracts",
    agendaBaseUrl: "https://www.utsystem.edu",
    agendaPathHints: ["/board-of-regents/meetings", "/agendas"],
  },
  {
    jurisdictionId: "university_system#TX#tamu-system",
    type: "university_system",
    name: "Texas A&M University System",
    stateCode: "TX",
    stateName: "Texas",
    population: 155000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "11 universities + 8 agencies — major procurement authority",
    agendaBaseUrl: "https://www.tamus.edu",
    agendaPathHints: ["/board-of-regents/meetings", "/agendas"],
  },
  {
    jurisdictionId: "university_system#CA#csu",
    type: "university_system",
    name: "California State University System",
    stateCode: "CA",
    stateName: "California",
    population: 485000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "23 campuses — CSU Board of Trustees meets quarterly",
    agendaBaseUrl: "https://www.calstate.edu",
    agendaPathHints: ["/trustees/agendas", "/board"],
  },
  {
    jurisdictionId: "university_system#CA#uc",
    type: "university_system",
    name: "University of California System",
    stateCode: "CA",
    stateName: "California",
    population: 290000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "10 campuses — UC Regents agendas are detailed and public",
    agendaBaseUrl: "https://www.universityofcalifornia.edu",
    agendaPathHints: ["/regents/meetings", "/agendas"],
  },
  {
    jurisdictionId: "university_system#NY#suny",
    type: "university_system",
    name: "State University of New York (SUNY)",
    stateCode: "NY",
    stateName: "New York",
    population: 415000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "64 campuses — largest comprehensive university system in the US",
    agendaBaseUrl: "https://www.suny.edu",
    agendaPathHints: ["/board-of-trustees/agendas", "/meetings"],
  },
  {
    jurisdictionId: "university_system#NC#unc-system",
    type: "university_system",
    name: "University of North Carolina System",
    stateCode: "NC",
    stateName: "North Carolina",
    population: 240000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "17 institutions — system procurement office in Chapel Hill",
    agendaBaseUrl: "https://www.northcarolina.edu",
    agendaPathHints: ["/board-of-governors/agendas", "/meetings"],
  },
  {
    jurisdictionId: "university_system#OH#ohio-state-system",
    type: "university_system",
    name: "University System of Ohio",
    stateCode: "OH",
    stateName: "Ohio",
    population: 500000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "36 institutions — Inter-University Council procurement",
    agendaBaseUrl: "https://www.ohio.gov/government/agencies-and-departments/higher-education",
    agendaPathHints: ["/board/agendas", "/meetings"],
  },
  {
    jurisdictionId: "university_system#TN#thec",
    type: "university_system",
    name: "Tennessee Board of Regents",
    stateCode: "TN",
    stateName: "Tennessee",
    population: 200000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "40 institutions — community colleges + tech schools",
    agendaBaseUrl: "https://www.tbr.edu",
    agendaPathHints: ["/board/agendas", "/meetings"],
  },
  {
    jurisdictionId: "university_system#VA#vccs",
    type: "university_system",
    name: "Virginia Community College System",
    stateCode: "VA",
    stateName: "Virginia",
    population: 230000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "23 community colleges — statewide tech procurement decisions",
    agendaBaseUrl: "https://www.vccs.edu",
    agendaPathHints: ["/board/agendas", "/state-board"],
  },
  {
    jurisdictionId: "university_system#SC#sc-system",
    type: "university_system",
    name: "University of South Carolina System",
    stateCode: "SC",
    stateName: "South Carolina",
    population: 75000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "8 campuses — system board covers all",
    agendaBaseUrl: "https://www.sc.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },

  // ── FLAGSHIP / LARGE UNIVERSITIES ───────────────────────────────────────
  {
    jurisdictionId: "university#AL#ua",
    type: "university",
    name: "University of Alabama",
    stateCode: "AL",
    stateName: "Alabama",
    population: 38103,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Tuscaloosa — flagship, large campus police dept",
    agendaBaseUrl: "https://www.ua.edu",
    agendaPathHints: ["/trustees/agendas", "/administration/board"],
  },
  {
    jurisdictionId: "university#AL#uab",
    type: "university",
    name: "University of Alabama at Birmingham",
    stateCode: "AL",
    stateName: "Alabama",
    population: 22568,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Medical campus — high security need",
    agendaBaseUrl: "https://www.uab.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#AL#auburn",
    type: "university",
    name: "Auburn University",
    stateCode: "AL",
    stateName: "Alabama",
    population: 31764,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.auburn.edu",
    agendaPathHints: ["/administration/board/agendas"],
  },
  {
    jurisdictionId: "university#AK#uaa",
    type: "university",
    name: "University of Alaska Anchorage",
    stateCode: "AK",
    stateName: "Alaska",
    population: 14000,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.uaa.alaska.edu",
    agendaPathHints: ["/chancellor/board", "/administration"],
  },
  {
    jurisdictionId: "university#AZ#asu",
    type: "university",
    name: "Arizona State University",
    stateCode: "AZ",
    stateName: "Arizona",
    population: 83000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Largest university in US by enrollment",
    agendaBaseUrl: "https://www.asu.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-regents"],
  },
  {
    jurisdictionId: "university#AZ#uofa",
    type: "university",
    name: "University of Arizona",
    stateCode: "AZ",
    stateName: "Arizona",
    population: 47000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.arizona.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#AR#uark",
    type: "university",
    name: "University of Arkansas",
    stateCode: "AR",
    stateName: "Arkansas",
    population: 29000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Fayetteville — flagship",
    agendaBaseUrl: "https://www.uark.edu",
    agendaPathHints: ["/trustees/agendas", "/administration/board"],
  },
  {
    jurisdictionId: "university#CA#ucla",
    type: "university",
    name: "UCLA",
    stateCode: "CA",
    stateName: "California",
    population: 47000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.ucla.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#CA#ucberkeley",
    type: "university",
    name: "UC Berkeley",
    stateCode: "CA",
    stateName: "California",
    population: 45000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.berkeley.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#CA#usc",
    type: "university",
    name: "University of Southern California",
    stateCode: "CA",
    stateName: "California",
    population: 49000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Private — large campus police force",
    agendaBaseUrl: "https://www.usc.edu",
    agendaPathHints: ["/trustees", "/administration/board"],
  },
  {
    jurisdictionId: "university#CO#cu-boulder",
    type: "university",
    name: "University of Colorado Boulder",
    stateCode: "CO",
    stateName: "Colorado",
    population: 37000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.colorado.edu",
    agendaPathHints: ["/regents/agendas", "/administration/board"],
  },
  {
    jurisdictionId: "university#CO#csu",
    type: "university",
    name: "Colorado State University",
    stateCode: "CO",
    stateName: "Colorado",
    population: 34000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.colostate.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#CT#uconn",
    type: "university",
    name: "University of Connecticut",
    stateCode: "CT",
    stateName: "Connecticut",
    population: 27000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://uconn.edu",
    agendaPathHints: ["/trustees/agendas", "/administration/board"],
  },
  {
    jurisdictionId: "university#DE#udel",
    type: "university",
    name: "University of Delaware",
    stateCode: "DE",
    stateName: "Delaware",
    population: 23000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.udel.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#FL#uf",
    type: "university",
    name: "University of Florida",
    stateCode: "FL",
    stateName: "Florida",
    population: 57000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Flagship — largest university in FL",
    agendaBaseUrl: "https://www.ufl.edu",
    agendaPathHints: ["/trustees/meetings", "/board-of-trustees/agendas"],
  },
  {
    jurisdictionId: "university#FL#fsu",
    type: "university",
    name: "Florida State University",
    stateCode: "FL",
    stateName: "Florida",
    population: 45000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Tallahassee — state capital adjacent",
    agendaBaseUrl: "https://www.fsu.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#FL#ucf",
    type: "university",
    name: "University of Central Florida",
    stateCode: "FL",
    stateName: "Florida",
    population: 70000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Largest university campus in US by enrollment",
    agendaBaseUrl: "https://www.ucf.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },
  {
    jurisdictionId: "university#FL#usf",
    type: "university",
    name: "University of South Florida",
    stateCode: "FL",
    stateName: "Florida",
    population: 50000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Tampa — R1 research university",
    agendaBaseUrl: "https://www.usf.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#FL#fiu",
    type: "university",
    name: "Florida International University",
    stateCode: "FL",
    stateName: "Florida",
    population: 58000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Miami — very large urban campus",
    agendaBaseUrl: "https://www.fiu.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#GA#uga",
    type: "university",
    name: "University of Georgia",
    stateCode: "GA",
    stateName: "Georgia",
    population: 40118,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Athens — active RC pilot market",
    agendaBaseUrl: "https://www.uga.edu",
    agendaPathHints: ["/administration/board", "/usg/board/meeting-materials"],
  },
  {
    jurisdictionId: "university#GA#gsu",
    type: "university",
    name: "Georgia State University",
    stateCode: "GA",
    stateName: "Georgia",
    population: 52000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Atlanta — large urban campus, active security needs",
    agendaBaseUrl: "https://www.gsu.edu",
    agendaPathHints: ["/trustees/agendas", "/administration/board"],
  },
  {
    jurisdictionId: "university#GA#gt",
    type: "university",
    name: "Georgia Tech",
    stateCode: "GA",
    stateName: "Georgia",
    population: 21504,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Atlanta — tech-forward campus, strong RC fit",
    agendaBaseUrl: "https://www.gatech.edu",
    agendaPathHints: ["/administration/board", "/institute-communications"],
  },
  {
    jurisdictionId: "university#GA#gcsu",
    type: "university",
    name: "Georgia College & State University",
    stateCode: "GA",
    stateName: "Georgia",
    population: 7000,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    isActive: true,
    notes: "Milledgeville — state capital adjacent",
    agendaBaseUrl: "https://www.gcsu.edu",
    agendaPathHints: ["/administration/board"],
  },
  {
    jurisdictionId: "university#GA#kennesaw",
    type: "university",
    name: "Kennesaw State University",
    stateCode: "GA",
    stateName: "Georgia",
    population: 43000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "One of largest USG institutions",
    agendaBaseUrl: "https://www.kennesaw.edu",
    agendaPathHints: ["/administration/board"],
  },
  {
    jurisdictionId: "university#GA#csu",
    type: "university",
    name: "Columbus State University",
    stateCode: "GA",
    stateName: "Georgia",
    population: 8000,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    isActive: true,
    notes: "Columbus GA — RC HQ hometown. Pilot opportunity.",
    agendaBaseUrl: "https://www.columbusstate.edu",
    agendaPathHints: ["/administration/board"],
  },
  {
    jurisdictionId: "university#ID#uoi",
    type: "university",
    name: "University of Idaho",
    stateCode: "ID",
    stateName: "Idaho",
    population: 11000,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.uidaho.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#IL#uiuc",
    type: "university",
    name: "University of Illinois Urbana-Champaign",
    stateCode: "IL",
    stateName: "Illinois",
    population: 56000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Flagship — large campus police",
    agendaBaseUrl: "https://www.illinois.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },
  {
    jurisdictionId: "university#IL#uic",
    type: "university",
    name: "University of Illinois Chicago",
    stateCode: "IL",
    stateName: "Illinois",
    population: 33000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Urban campus — active security needs",
    agendaBaseUrl: "https://www.uic.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#IN#iu",
    type: "university",
    name: "Indiana University Bloomington",
    stateCode: "IN",
    stateName: "Indiana",
    population: 47000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.iu.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#IN#purdue",
    type: "university",
    name: "Purdue University",
    stateCode: "IN",
    stateName: "Indiana",
    population: 50000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "West Lafayette — large R1",
    agendaBaseUrl: "https://www.purdue.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },
  {
    jurisdictionId: "university#IA#uiowa",
    type: "university",
    name: "University of Iowa",
    stateCode: "IA",
    stateName: "Iowa",
    population: 32000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.uiowa.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#KS#ku",
    type: "university",
    name: "University of Kansas",
    stateCode: "KS",
    stateName: "Kansas",
    population: 27000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.ku.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#KY#uky",
    type: "university",
    name: "University of Kentucky",
    stateCode: "KY",
    stateName: "Kentucky",
    population: 30000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Lexington — flagship",
    agendaBaseUrl: "https://www.uky.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#KY#uofl",
    type: "university",
    name: "University of Louisville",
    stateCode: "KY",
    stateName: "Kentucky",
    population: 23000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Urban campus",
    agendaBaseUrl: "https://www.louisville.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#LA#lsu",
    type: "university",
    name: "Louisiana State University",
    stateCode: "LA",
    stateName: "Louisiana",
    population: 35000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Baton Rouge — flagship, major venue events",
    agendaBaseUrl: "https://www.lsu.edu",
    agendaPathHints: ["/administration/board/agendas"],
  },
  {
    jurisdictionId: "university#ME#umaine",
    type: "university",
    name: "University of Maine",
    stateCode: "ME",
    stateName: "Maine",
    population: 11000,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    isActive: true,
    notes: "Orono — flagship",
    agendaBaseUrl: "https://www.umaine.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#MD#umd",
    type: "university",
    name: "University of Maryland",
    stateCode: "MD",
    stateName: "Maryland",
    population: 41000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "College Park — near DC, high security awareness",
    agendaBaseUrl: "https://www.umd.edu",
    agendaPathHints: ["/regents/agendas", "/board-of-regents"],
  },
  {
    jurisdictionId: "university#MA#umass",
    type: "university",
    name: "UMass Amherst",
    stateCode: "MA",
    stateName: "Massachusetts",
    population: 32000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.umass.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#MA#bu",
    type: "university",
    name: "Boston University",
    stateCode: "MA",
    stateName: "Massachusetts",
    population: 36000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Private — urban campus, high security need",
    agendaBaseUrl: "https://www.bu.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },
  {
    jurisdictionId: "university#MA#northeastern",
    type: "university",
    name: "Northeastern University",
    stateCode: "MA",
    stateName: "Massachusetts",
    population: 21000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Boston — co-op/urban model",
    agendaBaseUrl: "https://www.northeastern.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#MI#umich",
    type: "university",
    name: "University of Michigan",
    stateCode: "MI",
    stateName: "Michigan",
    population: 48000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Ann Arbor — flagship",
    agendaBaseUrl: "https://www.umich.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#MI#msu",
    type: "university",
    name: "Michigan State University",
    stateCode: "MI",
    stateName: "Michigan",
    population: 50000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "High safety awareness post-2023",
    agendaBaseUrl: "https://msu.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },
  {
    jurisdictionId: "university#MN#umn",
    type: "university",
    name: "University of Minnesota",
    stateCode: "MN",
    stateName: "Minnesota",
    population: 54000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Twin Cities — flagship, multi-campus system",
    agendaBaseUrl: "https://www.umn.edu",
    agendaPathHints: ["/regents/agendas", "/board-of-regents"],
  },
  {
    jurisdictionId: "university#MS#olemiss",
    type: "university",
    name: "University of Mississippi",
    stateCode: "MS",
    stateName: "Mississippi",
    population: 22000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Oxford — flagship",
    agendaBaseUrl: "https://www.olemiss.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#MO#mizzou",
    type: "university",
    name: "University of Missouri",
    stateCode: "MO",
    stateName: "Missouri",
    population: 30000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Columbia — flagship",
    agendaBaseUrl: "https://www.umsystem.edu",
    agendaPathHints: ["/curators/agendas", "/board-of-curators"],
  },
  {
    jurisdictionId: "university#MT#umt",
    type: "university",
    name: "University of Montana",
    stateCode: "MT",
    stateName: "Montana",
    population: 9000,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.umt.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#NE#unl",
    type: "university",
    name: "University of Nebraska-Lincoln",
    stateCode: "NE",
    stateName: "Nebraska",
    population: 25000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.unl.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#NV#unlv",
    type: "university",
    name: "University of Nevada Las Vegas",
    stateCode: "NV",
    stateName: "Nevada",
    population: 32000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Vegas — high venue/event safety crossover",
    agendaBaseUrl: "https://www.unlv.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#NH#unh",
    type: "university",
    name: "University of New Hampshire",
    stateCode: "NH",
    stateName: "New Hampshire",
    population: 15000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.unh.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#NJ#rutgers",
    type: "university",
    name: "Rutgers University",
    stateCode: "NJ",
    stateName: "New Jersey",
    population: 71000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "State flagship — multi-campus system",
    agendaBaseUrl: "https://www.rutgers.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-governors/agendas"],
  },
  {
    jurisdictionId: "university#NM#unm",
    type: "university",
    name: "University of New Mexico",
    stateCode: "NM",
    stateName: "New Mexico",
    population: 21000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.unm.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#NY#columbia",
    type: "university",
    name: "Columbia University",
    stateCode: "NY",
    stateName: "New York",
    population: 35000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "NYC — urban campus, high security budget",
    agendaBaseUrl: "https://www.columbia.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#NY#nyu",
    type: "university",
    name: "New York University",
    stateCode: "NY",
    stateName: "New York",
    population: 60000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Private — large distributed campus, major security budget",
    agendaBaseUrl: "https://www.nyu.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#NY#cornell",
    type: "university",
    name: "Cornell University",
    stateCode: "NY",
    stateName: "New York",
    population: 25000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Ithaca — Ivy League, active campus safety program",
    agendaBaseUrl: "https://www.cornell.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#NC#unc",
    type: "university",
    name: "UNC Chapel Hill",
    stateCode: "NC",
    stateName: "North Carolina",
    population: 32000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Flagship",
    agendaBaseUrl: "https://www.unc.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#NC#ncsu",
    type: "university",
    name: "NC State University",
    stateCode: "NC",
    stateName: "North Carolina",
    population: 36000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Raleigh — tech-forward, strong RC fit",
    agendaBaseUrl: "https://www.ncsu.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#OH#osu",
    type: "university",
    name: "Ohio State University",
    stateCode: "OH",
    stateName: "Ohio",
    population: 61000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Columbus — largest campus in Ohio, major venue",
    agendaBaseUrl: "https://www.osu.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },
  {
    jurisdictionId: "university#OK#ou",
    type: "university",
    name: "University of Oklahoma",
    stateCode: "OK",
    stateName: "Oklahoma",
    population: 28000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Norman",
    agendaBaseUrl: "https://www.ou.edu",
    agendaPathHints: ["/trustees/agendas", "/regents/agendas"],
  },
  {
    jurisdictionId: "university#OR#uoregon",
    type: "university",
    name: "University of Oregon",
    stateCode: "OR",
    stateName: "Oregon",
    population: 21000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.uoregon.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#OR#oregonstate",
    type: "university",
    name: "Oregon State University",
    stateCode: "OR",
    stateName: "Oregon",
    population: 34000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://oregonstate.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#PA#psu",
    type: "university",
    name: "Penn State University",
    stateCode: "PA",
    stateName: "Pennsylvania",
    population: 91000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Largest PA university — multi-campus system",
    agendaBaseUrl: "https://www.psu.edu",
    agendaPathHints: ["/trustees/agendas", "/board-of-trustees"],
  },
  {
    jurisdictionId: "university#PA#pitt",
    type: "university",
    name: "University of Pittsburgh",
    stateCode: "PA",
    stateName: "Pennsylvania",
    population: 34000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Urban campus — Pittsburgh",
    agendaBaseUrl: "https://www.pitt.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#SC#usc",
    type: "university",
    name: "University of South Carolina",
    stateCode: "SC",
    stateName: "South Carolina",
    population: 36000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Columbia — flagship, state capital adjacent",
    agendaBaseUrl: "https://www.sc.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#SC#clemson",
    type: "university",
    name: "Clemson University",
    stateCode: "SC",
    stateName: "South Carolina",
    population: 27000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.clemson.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#TN#utk",
    type: "university",
    name: "University of Tennessee Knoxville",
    stateCode: "TN",
    stateName: "Tennessee",
    population: 35000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Flagship",
    agendaBaseUrl: "https://www.utk.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#TN#vanderbilt",
    type: "university",
    name: "Vanderbilt University",
    stateCode: "TN",
    stateName: "Tennessee",
    population: 15000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Private — Nashville, high endowment",
    agendaBaseUrl: "https://www.vanderbilt.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#TX#ut-austin",
    type: "university",
    name: "University of Texas at Austin",
    stateCode: "TX",
    stateName: "Texas",
    population: 51000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Flagship — Austin, major campus police dept",
    agendaBaseUrl: "https://www.utexas.edu",
    agendaPathHints: ["/trustees/agendas", "/regents/agendas"],
  },
  {
    jurisdictionId: "university#TX#tamu",
    type: "university",
    name: "Texas A&M University",
    stateCode: "TX",
    stateName: "Texas",
    population: 74000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "College Station — second largest in US",
    agendaBaseUrl: "https://www.tamu.edu",
    agendaPathHints: ["/board/agendas", "/trustees/agendas"],
  },
  {
    jurisdictionId: "university#TX#uh",
    type: "university",
    name: "University of Houston",
    stateCode: "TX",
    stateName: "Texas",
    population: 46000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Urban — Houston campus",
    agendaBaseUrl: "https://www.uh.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#TX#utsa",
    type: "university",
    name: "UT San Antonio",
    stateCode: "TX",
    stateName: "Texas",
    population: 34000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.utsa.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#UT#utah",
    type: "university",
    name: "University of Utah",
    stateCode: "UT",
    stateName: "Utah",
    population: 36000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "SLC — medical campus, high security profile",
    agendaBaseUrl: "https://www.utah.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#VA#uva",
    type: "university",
    name: "University of Virginia",
    stateCode: "VA",
    stateName: "Virginia",
    population: 25000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Charlottesville — flagship",
    agendaBaseUrl: "https://www.virginia.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#VA#vt",
    type: "university",
    name: "Virginia Tech",
    stateCode: "VA",
    stateName: "Virginia",
    population: 37000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "High campus safety awareness post-2007",
    agendaBaseUrl: "https://www.vt.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#WA#uw",
    type: "university",
    name: "University of Washington",
    stateCode: "WA",
    stateName: "Washington",
    population: 54000,
    tier: 0 as ScanTier,
    tierWeight: 4.0,
    intervalHours: 12,
    isActive: true,
    notes: "Seattle — flagship, large research campus",
    agendaBaseUrl: "https://www.washington.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#WA#wsu",
    type: "university",
    name: "Washington State University",
    stateCode: "WA",
    stateName: "Washington",
    population: 21000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: null,
    agendaBaseUrl: "https://www.wsu.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#WV#wvu",
    type: "university",
    name: "West Virginia University",
    stateCode: "WV",
    stateName: "West Virginia",
    population: 28000,
    tier: 2 as ScanTier,
    tierWeight: 2.0,
    intervalHours: 48,
    isActive: true,
    notes: "Morgantown — flagship",
    agendaBaseUrl: "https://www.wvu.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
  {
    jurisdictionId: "university#WI#uw-madison",
    type: "university",
    name: "University of Wisconsin-Madison",
    stateCode: "WI",
    stateName: "Wisconsin",
    population: 49000,
    tier: 1 as ScanTier,
    tierWeight: 3.0,
    intervalHours: 24,
    isActive: true,
    notes: "Flagship",
    agendaBaseUrl: "https://www.wisc.edu",
    agendaPathHints: ["/regents/agendas"],
  },
  {
    jurisdictionId: "university#WY#uw",
    type: "university",
    name: "University of Wyoming",
    stateCode: "WY",
    stateName: "Wyoming",
    population: 13000,
    tier: 3 as ScanTier,
    tierWeight: 1.0,
    intervalHours: 120,
    isActive: true,
    notes: "Only 4-year university in WY",
    agendaBaseUrl: "https://www.uwyo.edu",
    agendaPathHints: ["/trustees/agendas"],
  },
];
