import type { EmergencyPriorityTier, LanguageCapability, SupportedLanguage } from "./types.js";

function cap(over?: Partial<LanguageCapability>): LanguageCapability {
  const base: LanguageCapability = {
    translation: true,
    speechToText: false,
    textToSpeech: false,
    realTimeVoice: false,
    callerSms: true,
    dispatcherUi: false,
  };
  return { ...base, ...over };
}

/** Conservative RTL primary subtags (UI / script direction hints). */
const RTL_PRIMARIES = new Set([
  "ar",
  "arc",
  "ckb",
  "dv",
  "fa",
  "gv",
  "he",
  "ku",
  "ps",
  "sd",
  "ug",
  "ur",
  "yi",
]);

function directionForPrimary(primary: string): "ltr" | "rtl" {
  return RTL_PRIMARIES.has(primary) ? "rtl" : "ltr";
}

function tierForCode(canonical: string): EmergencyPriorityTier {
  const core = new Set([
    "en",
    "es",
    "zh",
    "zh-hans",
    "zh-hant",
    "vi",
    "tl",
    "ar",
    "ht",
    "fr",
    "pt",
    "ru",
    "ko",
  ]);
  const high = new Set([
    "uk",
    "pl",
    "de",
    "it",
    "hi",
    "ur",
    "pa",
    "bn",
    "gu",
    "ta",
    "te",
    "ja",
    "fa",
    "so",
    "sw",
    "am",
    "he",
    "th",
    "lo",
    "km",
    "my",
    "ne",
  ]);
  if (core.has(canonical)) return "core";
  if (high.has(canonical)) return "high";
  return "standard";
}

/** Explicit curated entries — names, natives, dialects. Supplemental ISO codes use Intl.DisplayNames. */
function explicitLanguages(): SupportedLanguage[] {
  return [
    {
      code: "en",
      name: "English",
      nativeName: "English",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "es",
      name: "Spanish",
      nativeName: "Español",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "zh",
      name: "Chinese",
      nativeName: "中文",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "zh-Hans",
      name: "Chinese (Simplified)",
      nativeName: "简体中文",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "zh-Hant",
      name: "Chinese (Traditional)",
      nativeName: "繁體中文",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "zh-TW",
      name: "Chinese (Traditional, Taiwan)",
      nativeName: "繁體中文",
      region: "TW",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "vi",
      name: "Vietnamese",
      nativeName: "Tiếng Việt",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "tl",
      name: "Filipino / Tagalog",
      nativeName: "Tagalog",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "ar",
      name: "Arabic",
      nativeName: "العربية",
      direction: "rtl",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "ht",
      name: "Haitian Creole",
      nativeName: "Kreyòl ayisyen",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "fr",
      name: "French",
      nativeName: "Français",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "pt",
      name: "Portuguese",
      nativeName: "Português",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "ru",
      name: "Russian",
      nativeName: "Русский",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "ko",
      name: "Korean",
      nativeName: "한국어",
      direction: "ltr",
      emergencyPriority: "core",
      capabilities: cap(),
    },
    {
      code: "uk",
      name: "Ukrainian",
      nativeName: "Українська",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "pl",
      name: "Polish",
      nativeName: "Polski",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "de",
      name: "German",
      nativeName: "Deutsch",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "it",
      name: "Italian",
      nativeName: "Italiano",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "hi",
      name: "Hindi",
      nativeName: "हिन्दी",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "ur",
      name: "Urdu",
      nativeName: "اردو",
      direction: "rtl",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "pa",
      name: "Punjabi",
      nativeName: "ਪੰਜਾਬੀ",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "bn",
      name: "Bangla (Bengali)",
      nativeName: "বাংলা",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "gu",
      name: "Gujarati",
      nativeName: "ગુજરાતી",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "ta",
      name: "Tamil",
      nativeName: "தமிழ்",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "te",
      name: "Telugu",
      nativeName: "తెలుగు",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "ja",
      name: "Japanese",
      nativeName: "日本語",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "fa",
      name: "Persian (Farsi)",
      nativeName: "فارسی",
      direction: "rtl",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "so",
      name: "Somali",
      nativeName: "Soomaali",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "sw",
      name: "Swahili",
      nativeName: "Kiswahili",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "am",
      name: "Amharic",
      nativeName: "አማርኛ",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "he",
      name: "Hebrew",
      nativeName: "עברית",
      direction: "rtl",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "th",
      name: "Thai",
      nativeName: "ไทย",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "lo",
      name: "Lao",
      nativeName: "ລາວ",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "km",
      name: "Khmer",
      nativeName: "ខ្មែរ",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "my",
      name: "Burmese (Myanmar)",
      nativeName: "မြန်မာဘာသာ",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "ne",
      name: "Nepali",
      nativeName: "नेपाली",
      direction: "ltr",
      emergencyPriority: "high",
      capabilities: cap(),
    },
    {
      code: "ckb",
      name: "Kurdish (Sorani)",
      nativeName: "کوردی",
      direction: "rtl",
      emergencyPriority: "standard",
      capabilities: cap(),
    },
  ];
}

const SUPPLEMENTAL_ISO = [
  "aa",
  "ab",
  "ae",
  "af",
  "ak",
  "an",
  "as",
  "av",
  "ay",
  "az",
  "ba",
  "be",
  "bg",
  "bh",
  "bi",
  "bm",
  "bo",
  "br",
  "bs",
  "ca",
  "ce",
  "ch",
  "co",
  "cr",
  "cs",
  "cu",
  "cv",
  "cy",
  "da",
  "dv",
  "dz",
  "ee",
  "el",
  "eo",
  "et",
  "eu",
  "ff",
  "fi",
  "fj",
  "fo",
  "fy",
  "ga",
  "gd",
  "gl",
  "gn",
  "gv",
  "ha",
  "ho",
  "hr",
  "hu",
  "hy",
  "hz",
  "ia",
  "id",
  "ie",
  "ig",
  "ii",
  "ik",
  "io",
  "is",
  "iu",
  "jv",
  "ka",
  "kg",
  "ki",
  "kj",
  "kk",
  "kl",
  "kn",
  "ks",
  "ku",
  "kv",
  "kw",
  "ky",
  "la",
  "lb",
  "lg",
  "li",
  "ln",
  "lt",
  "lu",
  "lv",
  "mg",
  "mh",
  "mi",
  "mk",
  "ml",
  "mn",
  "mr",
  "ms",
  "mt",
  "na",
  "nb",
  "nd",
  "ng",
  "nl",
  "nn",
  "no",
  "nr",
  "nv",
  "ny",
  "oc",
  "oj",
  "om",
  "or",
  "os",
  "pi",
  "ps",
  "qu",
  "rm",
  "rn",
  "ro",
  "rw",
  "sa",
  "sc",
  "sd",
  "se",
  "sg",
  "si",
  "sk",
  "sl",
  "sm",
  "sn",
  "sq",
  "sr",
  "ss",
  "su",
  "sv",
  "tg",
  "ti",
  "tk",
  "tn",
  "to",
  "tr",
  "ts",
  "tt",
  "tw",
  "ty",
  "uz",
  "ve",
  "vo",
  "wa",
  "wo",
  "xh",
  "yo",
  "za",
  "zu",
];

function supplementalLanguages(intlNames: Intl.DisplayNames): SupportedLanguage[] {
  const explicit = new Set(explicitLanguages().map((l) => l.code.toLowerCase()));
  const out: SupportedLanguage[] = [];
  for (const code of SUPPLEMENTAL_ISO) {
    if (explicit.has(code)) continue;
    let name = code;
    try {
      name = intlNames.of(code) || code;
    } catch {
      name = code;
    }
    const dir = directionForPrimary(code);
    const canonical = code;
    out.push({
      code: canonical,
      name,
      nativeName: undefined,
      direction: dir,
      emergencyPriority: "standard",
      capabilities: cap(),
    });
  }
  return out;
}

/** Build canonical default registry (explicit + supplemental ISO codes). */
export function buildDefaultSupportedLanguages(): SupportedLanguage[] {
  const intlNames = new Intl.DisplayNames(["en"], { type: "language" });
  const primary = explicitLanguages();
  const extra = supplementalLanguages(intlNames);
  const merged = [...primary, ...extra];
  for (const row of merged) {
    const p = row.code.split("-")[0]?.toLowerCase() ?? row.code.toLowerCase();
    if (!row.direction) {
      row.direction = directionForPrimary(p);
    }
    if (!row.emergencyPriority) {
      row.emergencyPriority = tierForCode(row.code.toLowerCase());
    }
  }
  return merged;
}
