.PHONY: build-function
build-function:
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r dist node_modules package.json "$(ARTIFACTS_DIR)/"

.DEFAULT:
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r dist node_modules package.json "$(ARTIFACTS_DIR)/"
